Repository kubernetes-sigs/secrets-store-csi-driver, pull requests merged in 2020-08, with the labels that each got.

#272 helm: move tolerations block inside OS conditional in helm chart
  manifest_staging/charts/secrets-store-csi-driver/templates/secrets-store-csi-driver-windows.yaml
  manifest_staging/charts/secrets-store-csi-driver/templates/secrets-store-csi-driver.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#276 test: move tests to subdir for provider
  test/bats/azure.bats
  test/bats/tests/azure/azure_synck8s_v1alpha1_secretproviderclass.yaml
  test/bats/tests/azure/azure_v1alpha1_secretproviderclass.yaml
  test/bats/tests/azure/azure_v1alpha1_secretproviderclass_ns.yaml
  test/bats/tests/azure/job_templates/kubernetes_windows.json
  test/bats/tests/azure/nginx-deployment-synck8s-azure.yaml
  test/bats/tests/azure/nginx-pod-secrets-store-inline-volume-crd.yaml
  test/bats/tests/nginx-pod-secrets-store-inline-volume.yaml
  test/bats/tests/vault/nginx-deployment-synck8s.yaml
  test/bats/tests/vault/nginx-pod-vault-inline-volume-secretproviderclass.yaml
  test/bats/tests/vault/vault.yaml
  test/bats/tests/vault/vault_synck8s_v1alpha1_secretproviderclass.yaml
  test/bats/tests/vault/vault_v1alpha1_secretproviderclass.yaml
  test/bats/tests/vault/vault_v1alpha1_secretproviderclass_ns.yaml
  test/bats/vault.bats
Labels: approved, cncf-cla: yes, lgtm, size/M

#275 chore: regenerate manifests to remove unused rbac permissions
  config/rbac/role.yaml
  controllers/secretproviderclasspodstatus_controller.go
  manifest_staging/charts/secrets-store-csi-driver/templates/role.yaml
  manifest_staging/deploy/rbac-secretproviderclass.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#278 doc: add release, go report, go version badge
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#274 feat: add preserveUnknownFields=false marker
  Makefile
  config/crd/bases/secrets-store.csi.x-k8s.io_secretproviderclasses.yaml
  config/crd/bases/secrets-store.csi.x-k8s.io_secretproviderclasspodstatuses.yaml
  manifest_staging/charts/secrets-store-csi-driver/templates/secrets-store.csi.x-k8s.io_secretproviderclasses.yaml
  manifest_staging/charts/secrets-store-csi-driver/templates/secrets-store.csi.x-k8s.io_secretproviderclasspodstatuses.yaml
  manifest_staging/deploy/secrets-store.csi.x-k8s.io_secretproviderclasses.yaml
  manifest_staging/deploy/secrets-store.csi.x-k8s.io_secretproviderclasspodstatuses.yaml
  test/bats/tests/vault/vault_v1alpha1_secretproviderclass_ns.yaml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/S

#260 helm: make all images configurable
  manifest_staging/charts/secrets-store-csi-driver/README.md
  manifest_staging/charts/secrets-store-csi-driver/templates/secrets-store-csi-driver-windows.yaml
  manifest_staging/charts/secrets-store-csi-driver/templates/secrets-store-csi-driver.yaml
  manifest_staging/charts/secrets-store-csi-driver/values.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#261 test: add tests for multiple secret provider class
  test/bats/azure.bats
  test/bats/tests/azure/azure_v1alpha1_multiple_secretproviderclass.yaml
  test/bats/tests/azure/nginx-pod-azure-inline-volume-multiple-spc.yaml
  test/bats/tests/vault/nginx-pod-vault-inline-volume-multiple-spc.yaml
  test/bats/tests/vault/vault_v1alpha1_multiple_secretproviderclass.yaml
  test/bats/vault.bats
Labels: approved, cncf-cla: yes, lgtm, size/L

#279 helm: add support for envs in helm chart
  manifest_staging/charts/secrets-store-csi-driver/README.md
  manifest_staging/charts/secrets-store-csi-driver/templates/secrets-store-csi-driver-windows.yaml
  manifest_staging/charts/secrets-store-csi-driver/templates/secrets-store-csi-driver.yaml
  manifest_staging/charts/secrets-store-csi-driver/values.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#273 feat: add `metadata.label` to synced secret
  apis/v1alpha1/secretproviderclass_types.go
  config/crd/bases/secrets-store.csi.x-k8s.io_secretproviderclasses.yaml
  controllers/secretproviderclasspodstatus_controller.go
  controllers/secretproviderclasspodstatus_controller_test.go
  manifest_staging/charts/secrets-store-csi-driver/templates/secrets-store.csi.x-k8s.io_secretproviderclasses.yaml
  manifest_staging/deploy/secrets-store.csi.x-k8s.io_secretproviderclasses.yaml
  test/bats/azure.bats
  test/bats/tests/azure/azure_synck8s_v1alpha1_secretproviderclass.yaml
  test/bats/tests/vault/vault_synck8s_v1alpha1_secretproviderclass.yaml
  test/bats/vault.bats
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#282 chore: update golangci-lint to v1.30.0
  .golangci.yml
  Makefile
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#283 doc: fixing links where files were moved to a new subdirectory.
  README.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#284 ci: remove az cli req
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#240 helm: chart best practices
  manifest_staging/charts/secrets-store-csi-driver/templates/_helpers.tpl
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#266 roles: split secret sync a separate role: secretprovidersyncing-role
  Makefile
  config/rbac-syncsecret/kustomization.yaml
  config/rbac-syncsecret/role.yaml
  config/rbac-syncsecret/role_binding.yaml
  config/rbac/role.yaml
  controllers/secretproviderclasspodstatus_controller.go
  controllers/syncsecret/syncsecret.go
  manifest_staging/charts/secrets-store-csi-driver/README.md
  manifest_staging/charts/secrets-store-csi-driver/templates/role-syncsecret.yaml
  manifest_staging/charts/secrets-store-csi-driver/templates/role-syncsecret_binding.yaml
  manifest_staging/charts/secrets-store-csi-driver/templates/role.yaml
  manifest_staging/charts/secrets-store-csi-driver/values.yaml
  manifest_staging/deploy/rbac-secretproviderclass.yaml
  manifest_staging/deploy/rbac-secretprovidersyncing.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#294 chore: bump version to v0.0.13
  Makefile
  docker/Makefile
  pkg/secrets-store/secrets-store.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#295 release: update manifest and helm charts for v0.0.13
  README.md
  charts/index.yaml
  charts/secrets-store-csi-driver-0.0.13.tgz
  charts/secrets-store-csi-driver/Chart.yaml
  charts/secrets-store-csi-driver/README.md
  charts/secrets-store-csi-driver/templates/_helpers.tpl
  charts/secrets-store-csi-driver/templates/role-syncsecret.yaml
  charts/secrets-store-csi-driver/templates/role-syncsecret_binding.yaml
  charts/secrets-store-csi-driver/templates/role.yaml
  charts/secrets-store-csi-driver/templates/secrets-store-csi-driver-windows.yaml
  charts/secrets-store-csi-driver/templates/secrets-store-csi-driver.yaml
  charts/secrets-store-csi-driver/templates/secrets-store.csi.x-k8s.io_secretproviderclasses.yaml
  charts/secrets-store-csi-driver/templates/secrets-store.csi.x-k8s.io_secretproviderclasspodstatuses.yaml
  charts/secrets-store-csi-driver/values.yaml
  deploy/rbac-secretproviderclass.yaml
  deploy/rbac-secretprovidersyncing.yaml
  deploy/secrets-store-csi-driver-windows.yaml
  deploy/secrets-store-csi-driver.yaml
  deploy/secrets-store.csi.x-k8s.io_secretproviderclasses.yaml
  deploy/secrets-store.csi.x-k8s.io_secretproviderclasspodstatuses.yaml
  manifest_staging/charts/secrets-store-csi-driver/Chart.yaml
  manifest_staging/charts/secrets-store-csi-driver/README.md
  manifest_staging/charts/secrets-store-csi-driver/values.yaml
  manifest_staging/deploy/secrets-store-csi-driver-windows.yaml
  manifest_staging/deploy/secrets-store-csi-driver.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L
