Repository kubernetes-sigs/secrets-store-csi-driver, pull requests merged in 2020-12, with the labels that each got.

#397 add tam7t as reviewer
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#383 feat: create target path in node publish
  go.mod
  go.sum
  pkg/csi-common/controllerserver-default.go
  pkg/csi-common/utils.go
  pkg/secrets-store/nodeserver.go
  pkg/secrets-store/nodeserver_test.go
  pkg/secrets-store/utils.go
  test/sanity/sanity_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#386 deploy: set namespace as kube-system
  README.md
  config/rbac-syncsecret/role_binding.yaml
  config/rbac/role_binding.yaml
  config/rbac/serviceaccount.yaml
  manifest_staging/deploy/rbac-secretproviderclass.yaml
  manifest_staging/deploy/rbac-secretprovidersyncing.yaml
  manifest_staging/deploy/secrets-store-csi-driver-windows.yaml
  manifest_staging/deploy/secrets-store-csi-driver.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#400 docs: update install doc for crds to check
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#394 feat: Reuse provider grpc clients
  cmd/secrets-store-csi-driver/main.go
  pkg/csi-common/server.go
  pkg/errors/errors.go
  pkg/rotation/reconciler.go
  pkg/rotation/reconciler_test.go
  pkg/secrets-store/nodeserver.go
  pkg/secrets-store/nodeserver_test.go
  pkg/secrets-store/provider_client.go
  pkg/secrets-store/provider_client_test.go
  pkg/secrets-store/secrets-store.go
  pkg/secrets-store/utils_test.go
  test/sanity/sanity_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#396 feat: add pprof profiling
  Makefile
  cmd/secrets-store-csi-driver/main.go
  pkg/csi-common/driver.go
  pkg/rotation/reconciler.go
  pkg/secrets-store/secrets-store.go
  pkg/secrets-store/secrets-store_test.go
  pkg/version/version.go
  test/sanity/sanity_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#402 feat: csidriver object api version v1
  Makefile
  manifest_staging/charts/secrets-store-csi-driver/templates/_helpers.tpl
  manifest_staging/charts/secrets-store-csi-driver/templates/csidriver.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#404 fix: windows image build with buildx
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#405 chore: bump driver version to v0.0.18
  Makefile
  docker/Makefile
  docker/build.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#406 release: update manifest and helm charts for v0.0.18
  Makefile
  charts/index.yaml
  charts/secrets-store-csi-driver-0.0.18.tgz
  charts/secrets-store-csi-driver/Chart.yaml
  charts/secrets-store-csi-driver/README.md
  charts/secrets-store-csi-driver/templates/_helpers.tpl
  charts/secrets-store-csi-driver/templates/csidriver.yaml
  charts/secrets-store-csi-driver/values.yaml
  deploy/rbac-secretproviderclass.yaml
  deploy/rbac-secretprovidersyncing.yaml
  deploy/secrets-store-csi-driver-windows.yaml
  deploy/secrets-store-csi-driver.yaml
  manifest_staging/charts/secrets-store-csi-driver/Chart.yaml
  manifest_staging/charts/secrets-store-csi-driver/README.md
  manifest_staging/charts/secrets-store-csi-driver/values.yaml
  manifest_staging/deploy/secrets-store-csi-driver-windows.yaml
  manifest_staging/deploy/secrets-store-csi-driver.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M
