Repository kubernetes-sigs/secrets-store-csi-driver, pull requests merged in 2020-11, with the labels that each got.

#371 fix: validate SPCPS targetPaths match Pod UIDs
  controllers/secretproviderclasspodstatus_controller.go
  controllers/secretproviderclasspodstatus_controller_test.go
  go.mod
  pkg/errors/errors.go
  pkg/rotation/reconciler.go
  pkg/rotation/reconciler_test.go
  pkg/secrets-store/nodeserver.go
  pkg/secrets-store/nodeserver_test.go
  pkg/secrets-store/utils.go
  pkg/util/fileutil/filesystem.go
  pkg/util/fileutil/filesystem_test.go
  pkg/util/k8sutil/volume.go
  pkg/util/k8sutil/volume_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XL

#365 feat: update deps and switch to klog
  cmd/secrets-store-csi-driver/main.go
  controllers/secretproviderclasspodstatus_controller.go
  controllers/secretproviderclasspodstatus_controller_test.go
  go.mod
  go.sum
  manifest_staging/charts/secrets-store-csi-driver/README.md
  manifest_staging/charts/secrets-store-csi-driver/templates/secrets-store-csi-driver-windows.yaml
  manifest_staging/charts/secrets-store-csi-driver/templates/secrets-store-csi-driver.yaml
  manifest_staging/charts/secrets-store-csi-driver/values.yaml
  manifest_staging/deploy/secrets-store-csi-driver-windows.yaml
  manifest_staging/deploy/secrets-store-csi-driver.yaml
  pkg/client/clientset/versioned/clientset.go
  pkg/client/clientset/versioned/typed/apis/v1alpha1/fake/fake_secretproviderclass.go
  pkg/client/clientset/versioned/typed/apis/v1alpha1/fake/fake_secretproviderclasspodstatus.go
  pkg/client/clientset/versioned/typed/apis/v1alpha1/secretproviderclass.go
  pkg/client/clientset/versioned/typed/apis/v1alpha1/secretproviderclasspodstatus.go
  pkg/client/informers/externalversions/apis/v1alpha1/secretproviderclass.go
  pkg/client/informers/externalversions/apis/v1alpha1/secretproviderclasspodstatus.go
  pkg/csi-common/controllerserver-default.go
  pkg/csi-common/driver.go
  pkg/csi-common/identityserver-default.go
  pkg/csi-common/nodeserver-default.go
  pkg/csi-common/server.go
  pkg/csi-common/utils.go
  pkg/k8s/store_test.go
  pkg/metrics/exporter.go
  pkg/rotation/reconciler.go
  pkg/rotation/reconciler_test.go
  pkg/secrets-store/nodeserver.go
  pkg/secrets-store/nodeserver_test.go
  pkg/secrets-store/provider_client.go
  pkg/secrets-store/secrets-store.go
  pkg/secrets-store/utils.go
  pkg/version/version.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/XL

#373 fix: handle pod termination during reconcile
  controllers/secretproviderclasspodstatus_controller.go
  pkg/rotation/reconciler.go
  pkg/rotation/reconciler_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#374 chore: update otel to v0.13.0
  cmd/secrets-store-csi-driver/main.go
  go.mod
  go.sum
  pkg/metrics/exporter.go
  pkg/metrics/prometheus_exporter.go
  pkg/rotation/stats_reporter.go
  pkg/secrets-store/stats_reporter.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#376 chore: bump driver version to v0.0.17
  Makefile
  docker/Makefile
  pkg/secrets-store/secrets-store.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#377 release: update manifest and helm charts for v0.0.17
  charts/index.yaml
  charts/secrets-store-csi-driver-0.0.17.tgz
  charts/secrets-store-csi-driver/Chart.yaml
  charts/secrets-store-csi-driver/README.md
  charts/secrets-store-csi-driver/templates/secrets-store-csi-driver-windows.yaml
  charts/secrets-store-csi-driver/templates/secrets-store-csi-driver.yaml
  charts/secrets-store-csi-driver/values.yaml
  deploy/secrets-store-csi-driver-windows.yaml
  deploy/secrets-store-csi-driver.yaml
  manifest_staging/charts/secrets-store-csi-driver/Chart.yaml
  manifest_staging/charts/secrets-store-csi-driver/README.md
  manifest_staging/charts/secrets-store-csi-driver/values.yaml
  manifest_staging/deploy/secrets-store-csi-driver-windows.yaml
  manifest_staging/deploy/secrets-store-csi-driver.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#380 Fix vault bats tests for running against v0.0.6 of the provider
  test/bats/tests/vault/vault_synck8s_v1alpha1_secretproviderclass.yaml
  test/bats/tests/vault/vault_v1alpha1_multiple_secretproviderclass.yaml
  test/bats/tests/vault/vault_v1alpha1_secretproviderclass.yaml
  test/bats/tests/vault/vault_v1alpha1_secretproviderclass_ns.yaml
  test/bats/vault.bats
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#381 docs: add mailing list url to readme
  README.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#360 docs: add netlify book configuration
  README.md
  docs/book/Makefile
  docs/book/OWNERS
  docs/book/book.toml
  docs/book/install-and-build.sh
  docs/book/src/SUMMARY.md
  docs/book/src/introduction.md
  docs/book/src/known-limitations.md
  docs/book/src/providers.md
  docs/book/src/testing.md
  docs/book/src/topics/metrics.md
  docs/book/src/topics/new-provider.md
  docs/book/src/topics/rotation.md
  docs/book/src/topics/topics.md
  docs/book/src/usage.md
  docs/book/theme/css/general.css
  docs/book/theme/favicon.png
  docs/book/theme/highlight.css
  docs/book/util-embed.sh
  docs/book/util-releaselink.sh
  docs/book/util-tabulate.sh
  netlify.toml
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#387 chore: best-effort cleanup socket
  cmd/secrets-store-csi-driver/main.go
  controllers/secretproviderclasspodstatus_controller.go
  pkg/csi-common/server.go
  pkg/csi-common/utils.go
  pkg/secrets-store/secrets-store.go
  test/sanity/sanity_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#388 fix: skip pods in succeeded or failed phase
  controllers/secretproviderclasspodstatus_controller.go
  pkg/rotation/reconciler.go
  pkg/rotation/reconciler_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#391 docs: update doc link for azure tls sample
  sample/ingress-controller-tls/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#393 fix: set key type to rsa or ec
  pkg/util/secretutil/secret.go
  pkg/util/secretutil/secret_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L
