Repository kubernetes-sigs/secrets-store-csi-driver, pull requests merged in 2020-05, with the labels that each got.

#192 Add sample for ingress controller with TLS
  sample/ingress-controller-tls/README.md
  sample/ingress-controller-tls/deployment-app-one.yaml
  sample/ingress-controller-tls/deployment-app-two.yaml
  sample/ingress-controller-tls/ingress.yaml
  sample/ingress-controller-tls/secretproviderclass-azure-tls.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#195 return early if mock provider and add mnt comments
  pkg/secrets-store/nodeserver.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#197 bump version to v0.0.10
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#199 Update crd, yaml, chart for v0.0.10
  README.md
  charts/index.yaml
  charts/secrets-store-csi-driver-0.0.10.tgz
  charts/secrets-store-csi-driver/Chart.yaml
  charts/secrets-store-csi-driver/README.md
  charts/secrets-store-csi-driver/templates/secrets-store.csi.x-k8s.io_secretproviderclasses.yaml
  charts/secrets-store-csi-driver/values.yaml
  deploy/secrets-store-csi-driver-windows.yaml
  deploy/secrets-store-csi-driver.yaml
  deploy/secrets-store.csi.x-k8s.io_secretproviderclasses.yaml
  pkg/secrets-store/secrets-store.go
  secretProviderClass/api/v1alpha1/secretproviderclass_types.go
  secretProviderClass/config/crd/bases/secrets-store.csi.x-k8s.io_secretproviderclasses.yaml
  test/bats/azure.bats
  test/bats/vault.bats
Labels: approved, cncf-cla: yes, lgtm, size/L

#202 Update doc, test to sync alias
  README.md
  test/bats/azure.bats
  test/bats/tests/azure_synck8s_v1alpha1_secretproviderclass.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#185 Inital metrics integration with opentelemetry
  docs/README.metrics.md
  go.mod
  go.sum
  pkg/metrics/exporter.go
  pkg/metrics/prometheus_exporter.go
  pkg/secrets-store/errors.go
  pkg/secrets-store/nodeserver.go
  pkg/secrets-store/secrets-store.go
  pkg/secrets-store/stats_reporter.go
  pkg/secrets-store/utils.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#205 update base image with debian base
  Dockerfile
  Makefile
  windows.Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/M

#207 feat: allow kubelet root dir to be configurable
  charts/secrets-store-csi-driver/README.md
  charts/secrets-store-csi-driver/templates/secrets-store-csi-driver-windows.yaml
  charts/secrets-store-csi-driver/templates/secrets-store-csi-driver.yaml
  charts/secrets-store-csi-driver/values.yaml
  pkg/secrets-store/nodeserver.go
  pkg/secrets-store/utils.go
  pkg/secrets-store/utils_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#208 chore: add slack channel for csi-secrets-store
  README.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/S

#210 chore: bump version to v0.0.11
  Makefile
  pkg/secrets-store/secrets-store.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#211 update manifests and helm chart for v0.0.11
  charts/index.yaml
  charts/secrets-store-csi-driver-0.0.11.tgz
  charts/secrets-store-csi-driver/Chart.yaml
  charts/secrets-store-csi-driver/README.md
  charts/secrets-store-csi-driver/values.yaml
  deploy/secrets-store-csi-driver-windows.yaml
  deploy/secrets-store-csi-driver.yaml
  sample/ingress-controller-tls/secretproviderclass-azure-tls.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#213 test: update azure key tests for latest release 0.0.6
  test/bats/azure.bats
Labels: approved, cncf-cla: yes, lgtm, size/S

#212 docs: add docs for ingress tls with vault
  sample/ingress-controller-tls/README.md
  sample/ingress-controller-tls/deployment-app-one.yaml
  sample/ingress-controller-tls/deployment-app-two.yaml
  sample/ingress-controller-tls/ingress.yaml
  sample/ingress-controller-tls/secretproviderclass-azure-tls.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L
