Repository kubernetes-sigs/secrets-store-csi-driver, pull requests merged in 2020-03, with the labels that each got.

#161 update makefile for e2e
  .travis.yml
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/M

#160 update repo path to sigs.k8s.io
  Makefile
  README.md
  charts/secrets-store-csi-driver/Chart.yaml
  charts/secrets-store-csi-driver/templates/NOTES.txt
  cmd/secrets-store-csi-driver/main.go
  go.mod
  pkg/secrets-store/controllerserver.go
  pkg/secrets-store/identityserver.go
  pkg/secrets-store/nodeserver.go
  pkg/secrets-store/secrets-store.go
  pkg/secrets-store/secrets-store_test.go
  secretProviderClass/PROJECT
  secretProviderClass/go.mod
  test/sanity/sanity_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#162 update OWNERS
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#163 Update driver name to k8s.io
  README.md
  charts/secrets-store-csi-driver/templates/csidriver.yaml
  charts/secrets-store-csi-driver/templates/secrets-store-csi-driver.yaml
  cmd/secrets-store-csi-driver/main.go
  deploy/csidriver-1.15.yaml
  deploy/csidriver.yaml
  deploy/secrets-store-csi-driver.yaml
  test/bats/tests/nginx-pod-secrets-store-inline-volume-crd.yaml
  test/bats/tests/nginx-pod-secrets-store-inline-volume.yaml
  test/bats/tests/nginx-pod-vault-inline-volume-secretproviderclass.yaml
  test/sanity/sanity_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#165 remove travis badge
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#166 add build badge based on postsubmit
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#171 bump version to v0.0.8
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#172 update manifests and release for v0.0.8
  charts/secrets-store-csi-driver/values.yaml
  deploy/secrets-store-csi-driver.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#174 bump csi-node-driver-registrar to v1.2.0
  charts/secrets-store-csi-driver/templates/secrets-store-csi-driver.yaml
  deploy/secrets-store-csi-driver.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#173 add liveness probe sidecar to deploy manifest
  deploy/secrets-store-csi-driver.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#175 Update README for recommended k8s version
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#164 add support for windows
  Makefile
  deploy/secrets-store-csi-driver-windows.yaml
  go.mod
  go.sum
  pkg/csi-common/server.go
  pkg/secrets-store/nodeserver.go
  pkg/secrets-store/nodeserver_test.go
  pkg/secrets-store/secrets-store.go
  windows.Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/L

#177 bump version to 0.0.9
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#178 update manifests and release for v0.0.9
  Makefile
  charts/secrets-store-csi-driver/Chart.yaml
  charts/secrets-store-csi-driver/values.yaml
  deploy/secrets-store-csi-driver.yaml
  pkg/secrets-store/secrets-store.go
  test/bats/vault.bats
Labels: approved, cncf-cla: yes, lgtm, size/S
