Repository kubernetes-sigs/secrets-store-csi-driver, pull requests merged in 2020-04, with the labels that each got.

#180 update azure e2e tests
  test/bats/azure.bats
Labels: approved, cncf-cla: yes, lgtm, size/S

#184 helm: switch to using version instead of gitversion
  charts/secrets-store-csi-driver/templates/csidriver.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#191 Add Chart packages
  README.md
  charts/index.yaml
  charts/secrets-store-csi-driver-0.0.9.tgz
  charts/secrets-store-csi-driver/Chart.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#193 Add gh issue and PR templates
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#183 restructure docs and add windows instructions
  README.md
  charts/secrets-store-csi-driver/README.md
Labels: approved, cncf-cla: yes, lgtm, size/L
