Repository kubernetes-sigs/secrets-store-csi-driver, pull requests merged in 2020-07, with the labels that each got.

#238 set context for provider binary calls
  pkg/secrets-store/nodeserver.go
  pkg/secrets-store/nodeserver_test.go
  pkg/secrets-store/secrets-store.go
  pkg/secrets-store/utils_test.go
  pkg/version/version.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#244 doc: add note about community call
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#248 chore: update to livenessprobe v2.0.0
  charts/secrets-store-csi-driver/README.md
  charts/secrets-store-csi-driver/templates/secrets-store-csi-driver.yaml
  charts/secrets-store-csi-driver/values.yaml
  deploy/secrets-store-csi-driver.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#250 Update community meeting
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#251 chore: bump version to v0.0.12
  Makefile
  docker/Makefile
  pkg/secrets-store/secrets-store.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#252 chore: increase cloud build timeout to 1800s
  docker/cloudbuild.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#253 release: update manifests and helm chart for v0.0.12
  charts/index.yaml
  charts/secrets-store-csi-driver-0.0.12.tgz
  charts/secrets-store-csi-driver/Chart.yaml
  charts/secrets-store-csi-driver/README.md
  charts/secrets-store-csi-driver/values.yaml
  deploy/secrets-store-csi-driver-windows.yaml
  deploy/secrets-store-csi-driver.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#254 feat: allow metrics addr to be configurable in helm
  README.md
  charts/index.yaml
  charts/secrets-store-csi-driver-0.0.12.tgz
  charts/secrets-store-csi-driver/README.md
  charts/secrets-store-csi-driver/templates/secrets-store-csi-driver-windows.yaml
  charts/secrets-store-csi-driver/templates/secrets-store-csi-driver.yaml
  charts/secrets-store-csi-driver/values.yaml
  deploy/secrets-store-csi-driver-windows.yaml
  deploy/secrets-store-csi-driver.yaml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/S

#259 Add stripping sensitive information while logging the grpc request
  go.mod
  pkg/csi-common/utils.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#258 doc: add release doc and targets
  Makefile
  docs/RELEASE.md
  manifest_staging/charts/secrets-store-csi-driver/Chart.yaml
  manifest_staging/charts/secrets-store-csi-driver/README.md
  manifest_staging/charts/secrets-store-csi-driver/templates/NOTES.txt
  manifest_staging/charts/secrets-store-csi-driver/templates/_helpers.tpl
  manifest_staging/charts/secrets-store-csi-driver/templates/csidriver.yaml
  manifest_staging/charts/secrets-store-csi-driver/templates/role.yaml
  manifest_staging/charts/secrets-store-csi-driver/templates/role_binding.yaml
  manifest_staging/charts/secrets-store-csi-driver/templates/secrets-store-csi-driver-windows.yaml
  manifest_staging/charts/secrets-store-csi-driver/templates/secrets-store-csi-driver.yaml
  manifest_staging/charts/secrets-store-csi-driver/templates/secrets-store.csi.x-k8s.io_secretproviderclasses.yaml
  manifest_staging/charts/secrets-store-csi-driver/templates/secrets-store.csi.x-k8s.io_secretproviderclasspodstatuses.yaml
  manifest_staging/charts/secrets-store-csi-driver/templates/serviceaccount.yaml
  manifest_staging/charts/secrets-store-csi-driver/values.yaml
  manifest_staging/deploy/csidriver-1.15.yaml
  manifest_staging/deploy/csidriver.yaml
  manifest_staging/deploy/rbac-secretproviderclass.yaml
  manifest_staging/deploy/secrets-store-csi-driver-windows.yaml
  manifest_staging/deploy/secrets-store-csi-driver.yaml
  manifest_staging/deploy/secrets-store.csi.x-k8s.io_secretproviderclasses.yaml
  manifest_staging/deploy/secrets-store.csi.x-k8s.io_secretproviderclasspodstatuses.yaml
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XXL

#267 attributes: pass csi.storage.k8s.io/serviceAccount.name
  pkg/secrets-store/nodeserver.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#270 test: check pod ready status before getting name
  Makefile
  test/bats/azure.bats
  test/bats/vault.bats
Labels: approved, cncf-cla: yes, kind/flake, lgtm, size/S

#262 helm: add tolerations to helm charts
  manifest_staging/charts/secrets-store-csi-driver/README.md
  manifest_staging/charts/secrets-store-csi-driver/templates/secrets-store-csi-driver-windows.yaml
  manifest_staging/charts/secrets-store-csi-driver/templates/secrets-store-csi-driver.yaml
  manifest_staging/charts/secrets-store-csi-driver/values.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#264 fix: use namespace for spc lookup + unit tests
  cmd/secrets-store-csi-driver/main.go
  go.sum
  pkg/secrets-store/nodeserver.go
  pkg/secrets-store/nodeserver_test.go
  pkg/secrets-store/secrets-store.go
  pkg/secrets-store/utils.go
  pkg/secrets-store/utils_test.go
  test/bats/azure.bats
  test/bats/tests/azure_v1alpha1_secretproviderclass_ns.yaml
  test/bats/tests/vault_v1alpha1_secretproviderclass_ns.yaml
  test/bats/vault.bats
  test/sanity/sanity_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XL
