Repository kubernetes-sigs/secrets-store-csi-driver, pull requests merged in 2020-06, with the labels that each got.

#189 Adds image automated build
  Makefile
  docker/BASEIMAGE
  docker/BASEIMAGE_CORE
  docker/Dockerfile
  docker/Makefile
  docker/build.sh
  docker/cloudbuild.yaml
  docker/windows.Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/L

#218 set DOCKER_CLI_EXPERIMENTAL in makefile
  docker/Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#219 Set HOME=/root for cloudbuild
  docker/cloudbuild.yaml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS

#220 set gcr_cloud_build for buildx
  docker/cloudbuild.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#225 image: Switch from manifest-tool to docker manifest
  docker/build.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#232 chore: update node selector and make it configurable
  Makefile
  charts/secrets-store-csi-driver/README.md
  charts/secrets-store-csi-driver/templates/secrets-store-csi-driver-windows.yaml
  charts/secrets-store-csi-driver/templates/secrets-store-csi-driver.yaml
  charts/secrets-store-csi-driver/values.yaml
  deploy/secrets-store-csi-driver-windows.yaml
  deploy/secrets-store-csi-driver.yaml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/M

#234 Update and fix e2e-vault
  Makefile
  test/bats/tests/vault.yaml
  test/bats/vault.bats
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#224 Use controller to reconcile k8s secrets
  Makefile
  PROJECT
  apis/v1alpha1/groupversion_info.go
  apis/v1alpha1/secretproviderclass_types.go
  apis/v1alpha1/secretproviderclasspodstatus_types.go
  apis/v1alpha1/zz_generated.deepcopy.go
  charts/secrets-store-csi-driver/templates/secrets-store.csi.x-k8s.io_secretproviderclasses.yaml
  charts/secrets-store-csi-driver/templates/secrets-store.csi.x-k8s.io_secretproviderclasspodstatuses.yaml
  cmd/secrets-store-csi-driver/main.go
  config/crd/bases/secrets-store.csi.x-k8s.io_secretproviderclasses.yaml
  config/crd/bases/secrets-store.csi.x-k8s.io_secretproviderclasspodstatuses.yaml
  config/rbac/kustomization.yaml
  config/rbac/role.yaml
  config/rbac/role_binding.yaml
  config/rbac/serviceaccount.yaml
  controllers/secretproviderclasspodstatus_controller.go
  controllers/secretproviderclasspodstatus_controller_test.go
  controllers/utils.go
  controllers/utils_test.go
  deploy/rbac-secretproviderclass.yaml
  deploy/secrets-store.csi.x-k8s.io_secretproviderclasses.yaml
  deploy/secrets-store.csi.x-k8s.io_secretproviderclasspodstatuses.yaml
  go.mod
  go.sum
  hack/boilerplate.go.txt
  pkg/secrets-store/nodeserver.go
  pkg/secrets-store/secrets-store.go
  pkg/secrets-store/utils.go
  pkg/secrets-store/utils_test.go
  secretProviderClass/.gitignore
  secretProviderClass/Makefile
  secretProviderClass/PROJECT
  secretProviderClass/api/v1alpha1/zz_generated.deepcopy.go
  secretProviderClass/config/rbac/role.yaml
  secretProviderClass/go.mod
  secretProviderClass/go.sum
  test/bats/azure.bats
  test/bats/vault.bats
Labels: approved, cncf-cla: yes, lgtm, size/XXL
