Repository kubernetes-sigs/secrets-store-csi-driver, pull requests merged in 2020-10, with the labels that each got.

#325 chore: remove unused PodUID field in secretproviderclasspodstatus
  apis/v1alpha1/secretproviderclasspodstatus_types.go
  config/crd/bases/secrets-store.csi.x-k8s.io_secretproviderclasspodstatuses.yaml
  manifest_staging/charts/secrets-store-csi-driver/templates/secrets-store.csi.x-k8s.io_secretproviderclasspodstatuses.yaml
  manifest_staging/deploy/secrets-store.csi.x-k8s.io_secretproviderclasspodstatuses.yaml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/XS

#327 feat: add trimspace to sanitize yaml fields
  controllers/secretproviderclasspodstatus_controller.go
  pkg/rotation/reconciler.go
  pkg/util/secretutil/secret.go
  pkg/util/secretutil/secret_test.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/L

#328 chore: update e2e helm install for grpc supported provider
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#326 chore: update default rotation poll interval to 2m
  cmd/secrets-store-csi-driver/main.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/XS

#332 chore: change health check port to 8095
  cmd/secrets-store-csi-driver/main.go
  manifest_staging/charts/secrets-store-csi-driver/README.md
  manifest_staging/charts/secrets-store-csi-driver/values.yaml
  manifest_staging/deploy/secrets-store-csi-driver-windows.yaml
  manifest_staging/deploy/secrets-store-csi-driver.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#331 docs: add doc for auto rotation
  README.md
  docs/README.metrics.md
  docs/README.rotation.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/M

#323 feat: add event recorder for secrets creation and rotation
  cmd/secrets-store-csi-driver/main.go
  config/rbac/role.yaml
  controllers/secretproviderclasspodstatus_controller.go
  controllers/secretproviderclasspodstatus_controller_test.go
  manifest_staging/charts/secrets-store-csi-driver/templates/role.yaml
  manifest_staging/deploy/rbac-secretproviderclass.yaml
  pkg/k8s/pod.go
  pkg/k8s/secret.go
  pkg/k8s/secretproviderclass.go
  pkg/k8s/secretproviderclasspodstatus.go
  pkg/k8s/store_test.go
  pkg/rotation/reconciler.go
  pkg/rotation/reconciler_test.go
  pkg/secrets-store/nodeserver.go
  pkg/secrets-store/secrets-store.go
  pkg/util/secretutil/secret.go
  pkg/util/secretutil/secret_test.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/XL

#334 chore: bump version to v0.0.15
  Makefile
  docker/Makefile
  pkg/secrets-store/secrets-store.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#336 release: update manifest and helm charts for v0.0.15
  charts/index.yaml
  charts/secrets-store-csi-driver-0.0.15.tgz
  charts/secrets-store-csi-driver/Chart.yaml
  charts/secrets-store-csi-driver/README.md
  charts/secrets-store-csi-driver/templates/role.yaml
  charts/secrets-store-csi-driver/templates/secrets-store-csi-driver-windows.yaml
  charts/secrets-store-csi-driver/templates/secrets-store-csi-driver.yaml
  charts/secrets-store-csi-driver/templates/secrets-store.csi.x-k8s.io_secretproviderclasspodstatuses.yaml
  charts/secrets-store-csi-driver/values.yaml
  deploy/rbac-secretproviderclass.yaml
  deploy/secrets-store-csi-driver-windows.yaml
  deploy/secrets-store-csi-driver.yaml
  deploy/secrets-store.csi.x-k8s.io_secretproviderclasspodstatuses.yaml
  manifest_staging/charts/secrets-store-csi-driver/Chart.yaml
  manifest_staging/charts/secrets-store-csi-driver/README.md
  manifest_staging/charts/secrets-store-csi-driver/values.yaml
  manifest_staging/deploy/secrets-store-csi-driver-windows.yaml
  manifest_staging/deploy/secrets-store-csi-driver.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#339 fix: marshal secrets for non node publish secret ref
  pkg/rotation/reconciler.go
  pkg/secrets-store/provider_client_test.go
  provider/fake/fake_server.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#342 release: update manifest and helm charts for v0.0.16
  charts/index.yaml
  charts/secrets-store-csi-driver-0.0.16.tgz
  charts/secrets-store-csi-driver/Chart.yaml
  charts/secrets-store-csi-driver/README.md
  charts/secrets-store-csi-driver/values.yaml
  deploy/secrets-store-csi-driver-windows.yaml
  deploy/secrets-store-csi-driver.yaml
  manifest_staging/charts/secrets-store-csi-driver/Chart.yaml
  manifest_staging/charts/secrets-store-csi-driver/README.md
  manifest_staging/charts/secrets-store-csi-driver/values.yaml
  manifest_staging/deploy/secrets-store-csi-driver-windows.yaml
  manifest_staging/deploy/secrets-store-csi-driver.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#340 GCP plugin: integration tests
  Makefile
  test/bats/gcp.bats
  test/bats/tests/gcp/gcp_v1alpha1_secretproviderclass.yaml
  test/bats/tests/gcp/nginx-pod-secrets-store-inline-volume-crd.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#337 Add priorityClassName to daemonsets.
  manifest_staging/charts/secrets-store-csi-driver/README.md
  manifest_staging/charts/secrets-store-csi-driver/templates/secrets-store-csi-driver-windows.yaml
  manifest_staging/charts/secrets-store-csi-driver/templates/secrets-store-csi-driver.yaml
  manifest_staging/charts/secrets-store-csi-driver/values.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#351 deploy: add gcp as grpcSupportedProviders by default
  manifest_staging/charts/secrets-store-csi-driver/values.yaml
  manifest_staging/deploy/secrets-store-csi-driver.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#348 readme: add link to GCP provider
  README.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#352 feat: add gosec linter and fix warnings
  .golangci.yml
  pkg/errors/errors.go
  pkg/secrets-store/nodeserver.go
  pkg/secrets-store/utils.go
  pkg/util/secretutil/secret.go
  test/bats/azure.bats
  test/bats/vault.bats
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/M

#359 test: make tests more deterministic and retries
  test/bats/azure.bats
  test/bats/helpers.bash
  test/bats/vault.bats
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/M

#358 Switch to using official images for containers
  manifest_staging/charts/secrets-store-csi-driver/README.md
  manifest_staging/charts/secrets-store-csi-driver/values.yaml
  manifest_staging/deploy/secrets-store-csi-driver-windows.yaml
  manifest_staging/deploy/secrets-store-csi-driver.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#362 Allow the 'updateStrategy' of the Daemonset to be configured in Helm
  manifest_staging/charts/secrets-store-csi-driver/README.md
  manifest_staging/charts/secrets-store-csi-driver/templates/secrets-store-csi-driver-windows.yaml
  manifest_staging/charts/secrets-store-csi-driver/templates/secrets-store-csi-driver.yaml
  manifest_staging/charts/secrets-store-csi-driver/values.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#366 chore: remove lifecycle prestop command
  manifest_staging/charts/secrets-store-csi-driver/templates/secrets-store-csi-driver-windows.yaml
  manifest_staging/charts/secrets-store-csi-driver/templates/secrets-store-csi-driver.yaml
  manifest_staging/deploy/secrets-store-csi-driver-windows.yaml
  manifest_staging/deploy/secrets-store-csi-driver.yaml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/M
