Repository kubernetes-sigs/secrets-store-csi-driver, pull requests merged in 2021-07, with the labels that each got.

#616 master to main rename
  docs/RELEASE.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#627 docs: link and mention optional features
  docs/book/src/concepts.md
  docs/book/src/getting-started/installation.md
  docs/book/src/introduction.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#626 test: add kubernetes.io/os nodeselector for azure tests
  test/bats/azure.bats
  test/bats/tests/azure/deployment-synck8s-azure.yaml
  test/bats/tests/azure/deployment-two-synck8s-azure.yaml
  test/bats/tests/azure/pod-azure-inline-volume-multiple-spc.yaml
  test/bats/tests/azure/pod-secrets-store-inline-volume-crd.yaml
  test/bats/tests/azure/rotation/pod-synck8s-azure.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#471 Initial implementation of token request
  go.mod
  pkg/secrets-store/nodeserver.go
  pkg/secrets-store/nodeserver_test.go
  test/e2eprovider/server.go
  test/e2eprovider/server_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#629 helm: move default annotations out of conditional
  manifest_staging/charts/secrets-store-csi-driver/templates/secrets-store-csi-driver-windows.yaml
  manifest_staging/charts/secrets-store-csi-driver/templates/secrets-store-csi-driver.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#628 e2e: use kubectl wait to check if pods ready
  test/bats/aws.bats
  test/bats/gcp.bats
Labels: approved, cncf-cla: yes, lgtm, size/S

#602 feat: implements e2e upgrade test
  Makefile
  test/bats/azure.bats
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S, tide/merge-method-squash

#599 e2e: ensure pod deletion is successful
  test/bats/aws.bats
  test/bats/azure.bats
  test/bats/gcp.bats
  test/bats/helpers.bash
  test/bats/vault.bats
Labels: approved, cncf-cla: yes, lgtm, size/L

#625 Fix Windows nodes compatibility issues in pod definition
  deploy/secrets-store-csi-driver-windows.yaml
  manifest_staging/charts/secrets-store-csi-driver/templates/secrets-store-csi-driver-windows.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S, tide/merge-method-squash

#630 chore: revert changes from deploy and add to manifest_staging
  deploy/secrets-store-csi-driver-windows.yaml
  manifest_staging/deploy/secrets-store-csi-driver-windows.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#632 tests: include more debug info in artifacts
  test/bats/helpers.bash
Labels: approved, cncf-cla: yes, lgtm, size/XS

#631 docs: use testgrid for readme test status
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#638 e2e: get logs for sidecar containers
  test/bats/helpers.bash
  test/bats/tests/azure/job_templates/kubernetes_windows.json
Labels: approved, cncf-cla: yes, lgtm, size/S

#623 Crd upgrade via helm hooks
  Makefile
  docker/Makefile
  docker/build.sh
  docker/crd.Dockerfile
  manifest_staging/charts/secrets-store-csi-driver/templates/crds-upgrade-hook.yaml
  manifest_staging/charts/secrets-store-csi-driver/values.yaml
  test/scripts/initialize_eks_cluster.bash
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L, tide/merge-method-squash

#641 test: gcp use workload id instead of node publish
  test/bats/azure.bats
  test/bats/gcp.bats
  test/bats/helpers.bash
  test/bats/tests/gcp/gcp_v1alpha1_secretproviderclass.yaml
  test/bats/tests/gcp/pod-secrets-store-inline-volume-crd.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#643 chore: switch to using distroless base image for driver-crds
  Makefile
  docker/cloudbuild.yaml
  docker/crd.Dockerfile
  manifest_staging/charts/secrets-store-csi-driver/templates/crds-upgrade-hook.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#642 docs: adds note about crd upgrade
  docs/book/src/getting-started/upgrades.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, ok-to-test, size/XS, tide/merge-method-squash

#645 dockerfile: fix CVE-2021-33910
  docker/Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#647 chore: switch to using manifest_staging charts in the build
  docker/build.sh
  test/bats/azure.bats
Labels: approved, cncf-cla: yes, lgtm, size/S

#651 chore: bump version to v0.1.0 in release-0.1
  Makefile
  docker/Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#652 fix: add ARCH build arg for driver-crds
  docker/build.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#653 Automated cherry pick of #652: fix: add ARCH build arg for driver-crds
  docker/build.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#654 chore: add cherry_pick_pull script from kubernetes
  hack/cherry_pick_pull.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#657 e2e: add driver-crd image to e2e-helm-upgrade target
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#662 Automated cherry pick of #660: release: update manifests for v0.1.0
  Makefile
  charts/index.yaml
  charts/secrets-store-csi-driver-0.1.0.tgz
  charts/secrets-store-csi-driver/Chart.yaml
  charts/secrets-store-csi-driver/README.md
  charts/secrets-store-csi-driver/crds/secrets-store.csi.x-k8s.io_secretproviderclasses.yaml
  charts/secrets-store-csi-driver/crds/secrets-store.csi.x-k8s.io_secretproviderclasspodstatuses.yaml
  charts/secrets-store-csi-driver/templates/crds-upgrade-hook.yaml
  charts/secrets-store-csi-driver/templates/csidriver.yaml
  charts/secrets-store-csi-driver/templates/keep-crds-upgrade-hook.yaml
  charts/secrets-store-csi-driver/templates/secrets-store-csi-driver-windows.yaml
  charts/secrets-store-csi-driver/templates/secrets-store-csi-driver.yaml
  charts/secrets-store-csi-driver/values.yaml
  config/crd/bases/secrets-store.csi.x-k8s.io_secretproviderclasses.yaml
  deploy/secrets-store-csi-driver-windows.yaml
  deploy/secrets-store-csi-driver.yaml
  deploy/secrets-store.csi.x-k8s.io_secretproviderclasses.yaml
  manifest_staging/charts/secrets-store-csi-driver/Chart.yaml
  manifest_staging/charts/secrets-store-csi-driver/README.md
  manifest_staging/charts/secrets-store-csi-driver/crds/secrets-store.csi.x-k8s.io_secretproviderclasses.yaml
  manifest_staging/charts/secrets-store-csi-driver/values.yaml
  manifest_staging/deploy/secrets-store-csi-driver-windows.yaml
  manifest_staging/deploy/secrets-store-csi-driver.yaml
  manifest_staging/deploy/secrets-store.csi.x-k8s.io_secretproviderclasses.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#660 release: update manifests for v0.1.0
  Makefile
  charts/index.yaml
  charts/secrets-store-csi-driver-0.1.0.tgz
  charts/secrets-store-csi-driver/Chart.yaml
  charts/secrets-store-csi-driver/README.md
  charts/secrets-store-csi-driver/crds/secrets-store.csi.x-k8s.io_secretproviderclasses.yaml
  charts/secrets-store-csi-driver/crds/secrets-store.csi.x-k8s.io_secretproviderclasspodstatuses.yaml
  charts/secrets-store-csi-driver/templates/crds-upgrade-hook.yaml
  charts/secrets-store-csi-driver/templates/csidriver.yaml
  charts/secrets-store-csi-driver/templates/keep-crds-upgrade-hook.yaml
  charts/secrets-store-csi-driver/templates/secrets-store-csi-driver-windows.yaml
  charts/secrets-store-csi-driver/templates/secrets-store-csi-driver.yaml
  charts/secrets-store-csi-driver/values.yaml
  config/crd/bases/secrets-store.csi.x-k8s.io_secretproviderclasses.yaml
  deploy/secrets-store-csi-driver-windows.yaml
  deploy/secrets-store-csi-driver.yaml
  deploy/secrets-store.csi.x-k8s.io_secretproviderclasses.yaml
  docker/Makefile
  manifest_staging/charts/secrets-store-csi-driver/Chart.yaml
  manifest_staging/charts/secrets-store-csi-driver/README.md
  manifest_staging/charts/secrets-store-csi-driver/crds/secrets-store.csi.x-k8s.io_secretproviderclasses.yaml
  manifest_staging/charts/secrets-store-csi-driver/values.yaml
  manifest_staging/deploy/secrets-store-csi-driver-windows.yaml
  manifest_staging/deploy/secrets-store-csi-driver.yaml
  manifest_staging/deploy/secrets-store.csi.x-k8s.io_secretproviderclasses.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#650 docs: add details on v0.1.0 upgrades
  docs/book/src/getting-started/upgrades.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#664 test: use kubectl exec instead of cp
  test/bats/azure.bats
  test/bats/gcp.bats
Labels: approved, cncf-cla: yes, lgtm, size/S

#666 Automated cherry pick of #664: test: use kubectl exec instead of cp
  test/bats/azure.bats
  test/bats/gcp.bats
Labels: approved, cncf-cla: yes, lgtm, size/S

#607 Update Membership.md with more roles/details
  docs/MEMBERSHIP.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, ok-to-test, size/L, tide/merge-method-squash

#635 chore: update golangci-lint
  .golangci.yml
  controllers/secretproviderclasspodstatus_controller.go
  hack/tools/go.mod
  hack/tools/go.sum
  pkg/rotation/reconciler_test.go
  pkg/util/fileutil/writer_test.go
  pkg/version/version.go
Labels: approved, cncf-cla: yes, lgtm, size/XL, tide/merge-method-squash

#671 helm: add option to configure fullnameOverride
  manifest_staging/charts/secrets-store-csi-driver/templates/_helpers.tpl
Labels: approved, cncf-cla: yes, lgtm, size/XS

#667 docs: update load test doc for filtered watch secret
  docs/book/src/load-tests.md
Labels: approved, cncf-cla: yes, lgtm, size/XS
