Repository kubernetes-sigs/secrets-store-csi-driver, pull requests merged in 2021-02, with the labels that each got.

#439 feat: enable 2004 builds for windows images
  docker/BASEIMAGE
  docker/BASEIMAGE_CORE
Labels: approved, cncf-cla: yes, lgtm, size/XS

#399 docs: update contents in docs site
  .gitignore
  README.md
  docs/book/src/SUMMARY.md
  docs/book/src/concepts.md
  docs/book/src/getting-started/getting-started.md
  docs/book/src/getting-started/installation.md
  docs/book/src/getting-started/usage.md
  docs/book/src/images/diagram.png
  docs/book/src/introduction.md
  docs/book/src/known-limitations.md
  docs/book/src/providers.md
  docs/book/src/testing.md
  docs/book/src/topics/metrics.md
  docs/book/src/topics/new-provider.md
  docs/book/src/topics/secret-auto-rotation.md
  docs/book/src/topics/set-as-env-var.md
  docs/book/src/topics/sync-as-kubernetes-secret.md
  docs/book/src/topics/topics.md
  docs/book/src/troubleshooting.md
  docs/book/src/usage.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XL

#440 helm: add value for setting pod annotations
  manifest_staging/charts/secrets-store-csi-driver/README.md
  manifest_staging/charts/secrets-store-csi-driver/templates/secrets-store-csi-driver-windows.yaml
  manifest_staging/charts/secrets-store-csi-driver/templates/secrets-store-csi-driver.yaml
  manifest_staging/charts/secrets-store-csi-driver/values.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#444 helm: add podLabels parameter
  manifest_staging/charts/secrets-store-csi-driver/README.md
  manifest_staging/charts/secrets-store-csi-driver/templates/secrets-store-csi-driver-windows.yaml
  manifest_staging/charts/secrets-store-csi-driver/templates/secrets-store-csi-driver.yaml
  manifest_staging/charts/secrets-store-csi-driver/values.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#449 chore: update klog to v2.5.0
  go.mod
  go.sum
  manifest_staging/charts/secrets-store-csi-driver/README.md
  manifest_staging/charts/secrets-store-csi-driver/templates/secrets-store-csi-driver-windows.yaml
  manifest_staging/charts/secrets-store-csi-driver/templates/secrets-store-csi-driver.yaml
  manifest_staging/charts/secrets-store-csi-driver/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#448 fix: set rsa key type for pkcs1 key
  pkg/util/secretutil/secret.go
  pkg/util/secretutil/secret_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#451 feat: set secrets-store default container for log
  manifest_staging/charts/secrets-store-csi-driver/templates/secrets-store-csi-driver-windows.yaml
  manifest_staging/charts/secrets-store-csi-driver/templates/secrets-store-csi-driver.yaml
  manifest_staging/deploy/secrets-store-csi-driver-windows.yaml
  manifest_staging/deploy/secrets-store-csi-driver.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#445 docs: update readme to reference docs site
  README.md
  docs/book/src/introduction.md
  img/diagram.png
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/L

#441 ci: add image scan as part of CI
  .gitignore
  .golangci.yml
  Makefile
  hack/tools/go.mod
  hack/tools/go.sum
  hack/tools/tools.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#454 release: bump version to v0.0.20
  Makefile
  docker/BASEIMAGE
  docker/BASEIMAGE_CORE
  docker/Dockerfile
  docker/Makefile
Labels: approved, cncf-cla: yes, lgtm, size/S

#456 chore: increase cloudbuild timeout to 1h
  docker/cloudbuild.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#455 release: update manifest and helm charts for v0.0.20
  charts/index.yaml
  charts/secrets-store-csi-driver-0.0.20.tgz
  charts/secrets-store-csi-driver/Chart.yaml
  charts/secrets-store-csi-driver/README.md
  charts/secrets-store-csi-driver/templates/NOTES.txt
  charts/secrets-store-csi-driver/templates/secrets-store-csi-driver-windows.yaml
  charts/secrets-store-csi-driver/templates/secrets-store-csi-driver.yaml
  charts/secrets-store-csi-driver/values.yaml
  deploy/secrets-store-csi-driver-windows.yaml
  deploy/secrets-store-csi-driver.yaml
  manifest_staging/charts/secrets-store-csi-driver/Chart.yaml
  manifest_staging/charts/secrets-store-csi-driver/README.md
  manifest_staging/charts/secrets-store-csi-driver/templates/NOTES.txt
  manifest_staging/charts/secrets-store-csi-driver/values.yaml
  manifest_staging/deploy/secrets-store-csi-driver-windows.yaml
  manifest_staging/deploy/secrets-store-csi-driver.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#452 docs: update ingress sample url for azure provider
  sample/ingress-controller-tls/README.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS
