Repository kubernetes-sigs/secrets-store-csi-driver, pull requests merged in 2021-01, with the labels that each got.

#419 docs: update PR template for chart updates
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#412 helm: add support to set annotations
  manifest_staging/charts/secrets-store-csi-driver/README.md
  manifest_staging/charts/secrets-store-csi-driver/templates/secrets-store-csi-driver-windows.yaml
  manifest_staging/charts/secrets-store-csi-driver/templates/secrets-store-csi-driver.yaml
  manifest_staging/charts/secrets-store-csi-driver/values.yaml
Labels: approved, cncf-cla: yes, helm, kind/feature, lgtm, size/S

#417 chore: add azure provider to grpc supported providers
  manifest_staging/charts/secrets-store-csi-driver/README.md
  manifest_staging/charts/secrets-store-csi-driver/values.yaml
  manifest_staging/deploy/secrets-store-csi-driver-windows.yaml
  manifest_staging/deploy/secrets-store-csi-driver.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#409 feat(values): add kubernetesRootDir
  manifest_staging/charts/secrets-store-csi-driver/Chart.yaml
  manifest_staging/charts/secrets-store-csi-driver/README.md
  manifest_staging/charts/secrets-store-csi-driver/templates/secrets-store-csi-driver-windows.yaml
  manifest_staging/charts/secrets-store-csi-driver/templates/secrets-store-csi-driver.yaml
  manifest_staging/charts/secrets-store-csi-driver/values.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#421 feat: use common port for all metrics
  go.mod
  pkg/metrics/exporter.go
  pkg/metrics/prometheus_exporter.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/S

#422 fix: CVE-2020-27350, CVE-2020-29362
  Makefile
  docker/Dockerfile
  docker/Makefile
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS

#424 chore: update node-driver-registrar and liveness-probe images
  manifest_staging/charts/secrets-store-csi-driver/README.md
  manifest_staging/charts/secrets-store-csi-driver/templates/secrets-store-csi-driver-windows.yaml
  manifest_staging/charts/secrets-store-csi-driver/templates/secrets-store-csi-driver.yaml
  manifest_staging/charts/secrets-store-csi-driver/values.yaml
  manifest_staging/deploy/secrets-store-csi-driver-windows.yaml
  manifest_staging/deploy/secrets-store-csi-driver.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#425 chore: bump driver version to v0.0.19
  Makefile
  docker/Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#426 release: update manifest and helm charts for v0.0.19
  charts/index.yaml
  charts/secrets-store-csi-driver-0.0.19.tgz
  charts/secrets-store-csi-driver/Chart.yaml
  charts/secrets-store-csi-driver/README.md
  charts/secrets-store-csi-driver/templates/secrets-store-csi-driver-windows.yaml
  charts/secrets-store-csi-driver/templates/secrets-store-csi-driver.yaml
  charts/secrets-store-csi-driver/values.yaml
  deploy/secrets-store-csi-driver-windows.yaml
  deploy/secrets-store-csi-driver.yaml
  manifest_staging/charts/secrets-store-csi-driver/README.md
  manifest_staging/charts/secrets-store-csi-driver/values.yaml
  manifest_staging/deploy/secrets-store-csi-driver-windows.yaml
  manifest_staging/deploy/secrets-store-csi-driver.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#431 Update e2e tests for gRPC Vault provider release
  Makefile
  test/bats/vault.bats
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#428 chore: update debian-base image to buster-v1.3.0
  Makefile
  docker/BASEIMAGE
  docker/Dockerfile
  docker/Makefile
Labels: approved, cncf-cla: yes, lgtm, size/S

#436 Update mdbook to 0.4.5 to fix CVE-2020-26297
  docs/book/install-and-build.sh
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#437 chore: remove host network
  manifest_staging/charts/secrets-store-csi-driver/templates/secrets-store-csi-driver.yaml
  manifest_staging/deploy/secrets-store-csi-driver.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#434 chore: add vault provider to grpc supported providers
  manifest_staging/charts/secrets-store-csi-driver/README.md
  manifest_staging/charts/secrets-store-csi-driver/values.yaml
  manifest_staging/deploy/secrets-store-csi-driver.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#433 chore: remove deprecated logic of invoking provider binary
  cmd/secrets-store-csi-driver/main.go
  manifest_staging/charts/secrets-store-csi-driver/README.md
  manifest_staging/charts/secrets-store-csi-driver/values.yaml
  pkg/errors/errors.go
  pkg/secrets-store/nodeserver.go
  pkg/secrets-store/nodeserver_test.go
  pkg/secrets-store/secrets-store.go
  pkg/secrets-store/utils.go
  pkg/secrets-store/utils_test.go
  pkg/version/version.go
  pkg/version/version_test.go
  test/sanity/sanity_test.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/XL
