Repository kubernetes-sigs/secrets-store-csi-driver, pull requests merged in 2021-05, with the labels that each got.

#524 chore: update to using k8s.io/mount-utils
  go.mod
  go.sum
  pkg/secrets-store/nodeserver.go
  pkg/secrets-store/nodeserver_test.go
  pkg/secrets-store/secrets-store.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#526 cleanup: remove windows file deletion on unmount
  pkg/secrets-store/nodeserver.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#512 feat: allow maxCallRecvMsgSize to be increased for large secret mounts
  cmd/secrets-store-csi-driver/main.go
  docs/book/src/troubleshooting.md
  manifest_staging/charts/secrets-store-csi-driver/README.md
  manifest_staging/charts/secrets-store-csi-driver/templates/secrets-store-csi-driver-windows.yaml
  manifest_staging/charts/secrets-store-csi-driver/templates/secrets-store-csi-driver.yaml
  manifest_staging/charts/secrets-store-csi-driver/values.yaml
  pkg/secrets-store/provider_client.go
  pkg/secrets-store/provider_client_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#519 chore: update sidecar images and set imagePullPolicy to IfNotPresent
  manifest_staging/charts/secrets-store-csi-driver/README.md
  manifest_staging/charts/secrets-store-csi-driver/values.yaml
  manifest_staging/deploy/secrets-store-csi-driver-windows.yaml
  manifest_staging/deploy/secrets-store-csi-driver.yaml
  test/bats/tests/vault/vault.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#532 test: include nested path in secret sync and update vault suite
  Makefile
  test/bats/tests/vault/vault.yaml
  test/bats/tests/vault/vault_synck8s_v1alpha1_secretproviderclass.yaml
  test/bats/tests/vault/vault_v1alpha1_multiple_secretproviderclass.yaml
  test/bats/tests/vault/vault_v1alpha1_secretproviderclass.yaml
  test/bats/tests/vault/vault_v1alpha1_secretproviderclass_ns.yaml
  test/bats/vault.bats
Labels: approved, cncf-cla: yes, lgtm, size/L

#520 feat: use the atomic file writer
  pkg/secrets-store/nodeserver_test.go
  pkg/secrets-store/provider_client_test.go
  pkg/util/fileutil/atomic_writer.go
  pkg/util/fileutil/atomic_writer_test.go
  pkg/util/fileutil/filesystem.go
  pkg/util/fileutil/filesystem_test.go
  pkg/util/fileutil/writer.go
  pkg/util/fileutil/writer_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#543 chore: update release docs and makefile targets
  Makefile
  docs/RELEASE.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#544 Bump versions for v0.0.22
  Makefile
  docker/Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#545 fix: windows targetpath cleanup as part of node unpublish
  docker/cloudbuild.yaml
  pkg/secrets-store/nodeserver.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#547 build: make manifests dependencies
  Makefile
  hack/tools/go.mod
  hack/tools/go.sum
Labels: approved, cncf-cla: yes, lgtm, size/L

#548 release: update manifests and helm chart for v0.0.22
  charts/index.yaml
  charts/secrets-store-csi-driver-0.0.22.tgz
  charts/secrets-store-csi-driver/Chart.yaml
  charts/secrets-store-csi-driver/README.md
  charts/secrets-store-csi-driver/templates/_helpers.tpl
  charts/secrets-store-csi-driver/templates/podsecuritypolicy.yaml
  charts/secrets-store-csi-driver/templates/role.yaml
  charts/secrets-store-csi-driver/templates/secrets-store-csi-driver-windows.yaml
  charts/secrets-store-csi-driver/templates/secrets-store-csi-driver.yaml
  charts/secrets-store-csi-driver/templates/secrets-store.csi.x-k8s.io_secretproviderclasses.yaml
  charts/secrets-store-csi-driver/templates/secrets-store.csi.x-k8s.io_secretproviderclasspodstatuses.yaml
  charts/secrets-store-csi-driver/values.yaml
  config/crd/bases/secrets-store.csi.x-k8s.io_secretproviderclasses.yaml
  config/crd/bases/secrets-store.csi.x-k8s.io_secretproviderclasspodstatuses.yaml
  deploy/csidriver.yaml
  deploy/secrets-store-csi-driver-windows.yaml
  deploy/secrets-store-csi-driver.yaml
  deploy/secrets-store.csi.x-k8s.io_secretproviderclasses.yaml
  deploy/secrets-store.csi.x-k8s.io_secretproviderclasspodstatuses.yaml
  manifest_staging/charts/secrets-store-csi-driver/Chart.yaml
  manifest_staging/charts/secrets-store-csi-driver/README.md
  manifest_staging/charts/secrets-store-csi-driver/templates/secrets-store.csi.x-k8s.io_secretproviderclasses.yaml
  manifest_staging/charts/secrets-store-csi-driver/templates/secrets-store.csi.x-k8s.io_secretproviderclasspodstatuses.yaml
  manifest_staging/charts/secrets-store-csi-driver/values.yaml
  manifest_staging/deploy/secrets-store-csi-driver-windows.yaml
  manifest_staging/deploy/secrets-store-csi-driver.yaml
  manifest_staging/deploy/secrets-store.csi.x-k8s.io_secretproviderclasses.yaml
  manifest_staging/deploy/secrets-store.csi.x-k8s.io_secretproviderclasspodstatuses.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XL

#552 release: add a link to branch compare
  docs/RELEASE.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#557 ci: enable shellcheck and fix errors
  Makefile
  hack/update-codegen.sh
  hack/verify-codegen.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#553 docs: set-as-env-var pod indent
  docs/book/src/topics/set-as-env-var.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, ok-to-test, size/M

#560 chore: add psp snippet to manifests target
  Makefile
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/XS

#539 Helm chart: provide ability to add volume and volumeMounts
  manifest_staging/charts/secrets-store-csi-driver/README.md
  manifest_staging/charts/secrets-store-csi-driver/templates/secrets-store-csi-driver-windows.yaml
  manifest_staging/charts/secrets-store-csi-driver/templates/secrets-store-csi-driver.yaml
  manifest_staging/charts/secrets-store-csi-driver/values.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M, tide/merge-method-squash

#537 Add test coverage report into Makefile for unit test
  Makefile
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#562 fix: CVE-2021-3520
  Makefile
  docker/BASEIMAGE
  docker/Dockerfile
  docker/Makefile
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/S

#565 chore: update to debian-base v1.7.0
  docker/BASEIMAGE
  docker/Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#566 chore: remove deprecated --grpc-supported-providers and --debug flag
  cmd/secrets-store-csi-driver/main.go
  manifest_staging/charts/secrets-store-csi-driver/README.md
  manifest_staging/charts/secrets-store-csi-driver/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#538 Add golang verison validate at Makefile
  Makefile
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#554 helm: add image pull secrets
  manifest_staging/charts/secrets-store-csi-driver/README.md
  manifest_staging/charts/secrets-store-csi-driver/templates/secrets-store-csi-driver-windows.yaml
  manifest_staging/charts/secrets-store-csi-driver/templates/secrets-store-csi-driver.yaml
  manifest_staging/charts/secrets-store-csi-driver/values.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S, tide/merge-method-squash

#533 add aws integration tests
  Makefile
  test/bats/aws.bats
  test/bats/tests/aws/BasicTestMount.yaml
  test/bats/tests/aws/BasicTestMountSPC.yaml
  test/scripts/initialize_eks_cluster.bash
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L
