Repository kubernetes-sigs/secrets-store-csi-driver, pull requests merged in 2021-04, with the labels that each got.

#496 chore: update debian base to buster-v1.5.0
  docker/BASEIMAGE
  docker/Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#497 docs: add load test spec and results
  docs/book/src/SUMMARY.md
  docs/book/src/load-tests.md
  docs/design/README.md
  manifest_staging/deploy/secrets-store-csi-driver-windows.yaml
  manifest_staging/deploy/secrets-store-csi-driver.yaml
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/M

#495 chore: bump version to v0.0.21
  Makefile
  docker/Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#498 release: update manifest and helm charts for v0.0.21
  Makefile
  charts/index.yaml
  charts/secrets-store-csi-driver-0.0.21.tgz
  charts/secrets-store-csi-driver/Chart.yaml
  charts/secrets-store-csi-driver/README.md
  charts/secrets-store-csi-driver/templates/secrets-store-csi-driver-windows.yaml
  charts/secrets-store-csi-driver/templates/secrets-store-csi-driver.yaml
  charts/secrets-store-csi-driver/values.yaml
  deploy/csidriver-1.15.yaml
  deploy/secrets-store-csi-driver-windows.yaml
  deploy/secrets-store-csi-driver.yaml
  docs/book/src/load-tests.md
  manifest_staging/charts/secrets-store-csi-driver/Chart.yaml
  manifest_staging/charts/secrets-store-csi-driver/README.md
  manifest_staging/charts/secrets-store-csi-driver/values.yaml
  manifest_staging/deploy/secrets-store-csi-driver-windows.yaml
  manifest_staging/deploy/secrets-store-csi-driver.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#504 docs: fix indentation in load tests
  docs/book/src/load-tests.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#509 docs: add test scenarios currently supported
  test/README.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/S

#508 feat: add optional healthcheck for provider plugins
  cmd/secrets-store-csi-driver/main.go
  manifest_staging/charts/secrets-store-csi-driver/README.md
  manifest_staging/charts/secrets-store-csi-driver/templates/secrets-store-csi-driver-windows.yaml
  manifest_staging/charts/secrets-store-csi-driver/templates/secrets-store-csi-driver.yaml
  manifest_staging/charts/secrets-store-csi-driver/values.yaml
  manifest_staging/deploy/secrets-store-csi-driver-windows.yaml
  manifest_staging/deploy/secrets-store-csi-driver.yaml
  pkg/secrets-store/provider_client.go
  pkg/secrets-store/provider_client_test.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/L

#513 Add node affinity
  manifest_staging/charts/secrets-store-csi-driver/README.md
  manifest_staging/charts/secrets-store-csi-driver/templates/secrets-store-csi-driver-windows.yaml
  manifest_staging/charts/secrets-store-csi-driver/templates/secrets-store-csi-driver.yaml
  manifest_staging/charts/secrets-store-csi-driver/values.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#516 fix: GetMountedFiles() returns map that key includes sub directory
  pkg/util/fileutil/filesystem.go
  pkg/util/fileutil/filesystem_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#505 docs: kube-system, upgrades, best-practices
  docs/book/src/SUMMARY.md
  docs/book/src/getting-started/installation.md
  docs/book/src/getting-started/upgrades.md
  docs/book/src/topics/best-practices.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/L

#478 Added Pod Security Policy to the chart
  manifest_staging/charts/secrets-store-csi-driver/README.md
  manifest_staging/charts/secrets-store-csi-driver/templates/_helpers.tpl
  manifest_staging/charts/secrets-store-csi-driver/templates/podsecuritypolicy.yaml
  manifest_staging/charts/secrets-store-csi-driver/templates/role.yaml
  manifest_staging/charts/secrets-store-csi-driver/values.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#518 fix: updates CSIDriver api ver to storage.k8s.io/v1
  manifest_staging/deploy/csidriver.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS
