Repository kubernetes-sigs/secrets-store-csi-driver, pull requests merged in 2021-08, with the labels that each got.

#614 chore: Add metrics port definition to DS
  manifest_staging/charts/secrets-store-csi-driver/templates/secrets-store-csi-driver-windows.yaml
  manifest_staging/charts/secrets-store-csi-driver/templates/secrets-store-csi-driver.yaml
  manifest_staging/deploy/secrets-store-csi-driver-windows.yaml
  manifest_staging/deploy/secrets-store-csi-driver.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#673 chore: Migrate from deprecated io/ioutil package to using os package
  pkg/util/fileutil/atomic_writer.go
  pkg/util/fileutil/atomic_writer_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S, tide/merge-method-squash

#669 test: adds make target for deploy manifest
  Makefile
  test/bats/azure.bats
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M, tide/merge-method-squash

#679 Add pre-install to upgrade hook so existing CRDs on helm install can …
  manifest_staging/charts/secrets-store-csi-driver/templates/crds-upgrade-hook.yaml
Labels: cncf-cla: yes, size/XS, approved, lgtm

#681 chore: update debian base to buster-v1.9.0
  docker/BASEIMAGE
  docker/Dockerfile
Labels: cncf-cla: yes, size/XS, approved, lgtm

#683 helm: use same toleration and nodeselector for crd-hook jobs
  manifest_staging/charts/secrets-store-csi-driver/templates/crds-upgrade-hook.yaml
  manifest_staging/charts/secrets-store-csi-driver/templates/keep-crds-upgrade-hook.yaml
Labels: cncf-cla: yes, approved, ok-to-test, lgtm, size/S

#685 chore: bump version to v0.2.0 in release-0.2
  Makefile
  docker/Makefile
Labels: cncf-cla: yes, size/XS, approved, lgtm

#690 Automated cherry pick of #689: release: update manifest and helm charts for v0.2.0
  charts/index.yaml
  charts/secrets-store-csi-driver-0.2.0.tgz
  charts/secrets-store-csi-driver/Chart.yaml
  charts/secrets-store-csi-driver/README.md
  charts/secrets-store-csi-driver/crds/secrets-store.csi.x-k8s.io_secretproviderclasses.yaml
  charts/secrets-store-csi-driver/crds/secrets-store.csi.x-k8s.io_secretproviderclasspodstatuses.yaml
  charts/secrets-store-csi-driver/templates/_helpers.tpl
  charts/secrets-store-csi-driver/templates/crds-upgrade-hook.yaml
  charts/secrets-store-csi-driver/templates/keep-crds-upgrade-hook.yaml
  charts/secrets-store-csi-driver/templates/secrets-store-csi-driver-windows.yaml
  charts/secrets-store-csi-driver/templates/secrets-store-csi-driver.yaml
  charts/secrets-store-csi-driver/values.yaml
  config/crd/bases/secrets-store.csi.x-k8s.io_secretproviderclasses.yaml
  config/crd/bases/secrets-store.csi.x-k8s.io_secretproviderclasspodstatuses.yaml
  deploy/secrets-store-csi-driver-windows.yaml
  deploy/secrets-store-csi-driver.yaml
  deploy/secrets-store.csi.x-k8s.io_secretproviderclasses.yaml
  deploy/secrets-store.csi.x-k8s.io_secretproviderclasspodstatuses.yaml
  manifest_staging/charts/secrets-store-csi-driver/Chart.yaml
  manifest_staging/charts/secrets-store-csi-driver/README.md
  manifest_staging/charts/secrets-store-csi-driver/crds/secrets-store.csi.x-k8s.io_secretproviderclasses.yaml
  manifest_staging/charts/secrets-store-csi-driver/crds/secrets-store.csi.x-k8s.io_secretproviderclasspodstatuses.yaml
  manifest_staging/charts/secrets-store-csi-driver/values.yaml
  manifest_staging/deploy/secrets-store-csi-driver-windows.yaml
  manifest_staging/deploy/secrets-store-csi-driver.yaml
  manifest_staging/deploy/secrets-store.csi.x-k8s.io_secretproviderclasses.yaml
  manifest_staging/deploy/secrets-store.csi.x-k8s.io_secretproviderclasspodstatuses.yaml
Labels: cncf-cla: yes, size/L, approved, lgtm

#689 release: update manifest and helm charts for v0.2.0
  Makefile
  charts/index.yaml
  charts/secrets-store-csi-driver-0.2.0.tgz
  charts/secrets-store-csi-driver/Chart.yaml
  charts/secrets-store-csi-driver/README.md
  charts/secrets-store-csi-driver/crds/secrets-store.csi.x-k8s.io_secretproviderclasses.yaml
  charts/secrets-store-csi-driver/crds/secrets-store.csi.x-k8s.io_secretproviderclasspodstatuses.yaml
  charts/secrets-store-csi-driver/templates/_helpers.tpl
  charts/secrets-store-csi-driver/templates/crds-upgrade-hook.yaml
  charts/secrets-store-csi-driver/templates/keep-crds-upgrade-hook.yaml
  charts/secrets-store-csi-driver/templates/secrets-store-csi-driver-windows.yaml
  charts/secrets-store-csi-driver/templates/secrets-store-csi-driver.yaml
  charts/secrets-store-csi-driver/values.yaml
  config/crd/bases/secrets-store.csi.x-k8s.io_secretproviderclasses.yaml
  config/crd/bases/secrets-store.csi.x-k8s.io_secretproviderclasspodstatuses.yaml
  deploy/secrets-store-csi-driver-windows.yaml
  deploy/secrets-store-csi-driver.yaml
  deploy/secrets-store.csi.x-k8s.io_secretproviderclasses.yaml
  deploy/secrets-store.csi.x-k8s.io_secretproviderclasspodstatuses.yaml
  docker/Makefile
  manifest_staging/charts/secrets-store-csi-driver/Chart.yaml
  manifest_staging/charts/secrets-store-csi-driver/README.md
  manifest_staging/charts/secrets-store-csi-driver/crds/secrets-store.csi.x-k8s.io_secretproviderclasses.yaml
  manifest_staging/charts/secrets-store-csi-driver/crds/secrets-store.csi.x-k8s.io_secretproviderclasspodstatuses.yaml
  manifest_staging/charts/secrets-store-csi-driver/values.yaml
  manifest_staging/deploy/secrets-store-csi-driver-windows.yaml
  manifest_staging/deploy/secrets-store-csi-driver.yaml
  manifest_staging/deploy/secrets-store.csi.x-k8s.io_secretproviderclasses.yaml
  manifest_staging/deploy/secrets-store.csi.x-k8s.io_secretproviderclasspodstatuses.yaml
Labels: cncf-cla: yes, size/L, approved, lgtm

#649 chore: update release docs with release branches
  docs/RELEASE.md
Labels: cncf-cla: yes, approved, lgtm, size/S

#691 chore: update node-driver-registrar to v2.3.0 and enable liveness probe
  manifest_staging/charts/secrets-store-csi-driver/README.md
  manifest_staging/charts/secrets-store-csi-driver/templates/secrets-store-csi-driver-windows.yaml
  manifest_staging/charts/secrets-store-csi-driver/templates/secrets-store-csi-driver.yaml
  manifest_staging/charts/secrets-store-csi-driver/values.yaml
  manifest_staging/deploy/secrets-store-csi-driver-windows.yaml
  manifest_staging/deploy/secrets-store-csi-driver.yaml
Labels: cncf-cla: yes, approved, lgtm, size/M

#692 helm: adding annotations to upgrade jobs
  Makefile
  manifest_staging/charts/secrets-store-csi-driver/README.md
  manifest_staging/charts/secrets-store-csi-driver/templates/crds-upgrade-hook.yaml
  manifest_staging/charts/secrets-store-csi-driver/templates/keep-crds-upgrade-hook.yaml
  manifest_staging/charts/secrets-store-csi-driver/values.yaml
Labels: cncf-cla: yes, approved, ok-to-test, tide/merge-method-squash, lgtm, size/S

#693 ci: add workflow for publishing helm charts
  .github/workflows/chart.yaml
  Makefile
Labels: cncf-cla: yes, approved, lgtm, size/M

#701 chore: update opentelemetry library to v0.20.0
  go.mod
  go.sum
  pkg/rotation/stats_reporter.go
  pkg/secrets-store/stats_reporter.go
Labels: cncf-cla: yes, size/L, approved, lgtm

#703 fix: remove constraints on secret type name
  pkg/util/secretutil/secret.go
  pkg/util/secretutil/secret_test.go
Labels: cncf-cla: yes, approved, lgtm, size/M

#697 chore: make `--filtered-watch-secret` flag no-op
  cmd/secrets-store-csi-driver/main.go
  pkg/k8s/store.go
  pkg/k8s/store_test.go
  pkg/rotation/reconciler.go
  pkg/rotation/reconciler_test.go
Labels: cncf-cla: yes, approved, lgtm, size/M

#702 refactor: remove csi-common package and update driver
  Makefile
  cmd/secrets-store-csi-driver/main.go
  go.mod
  go.sum
  pkg/csi-common/controllerserver-default.go
  pkg/csi-common/driver.go
  pkg/csi-common/driver_test.go
  pkg/csi-common/identityserver-default.go
  pkg/csi-common/identityserver-default_test.go
  pkg/csi-common/nodeserver-default.go
  pkg/csi-common/nodeserver-default_test.go
  pkg/csi-common/utils.go
  pkg/csi-common/utils_test.go
  pkg/secrets-store/controllerserver.go
  pkg/secrets-store/identityserver.go
  pkg/secrets-store/identityserver_test.go
  pkg/secrets-store/nodeserver.go
  pkg/secrets-store/nodeserver_test.go
  pkg/secrets-store/secrets-store.go
  pkg/secrets-store/secrets-store_test.go
  pkg/secrets-store/server.go
  pkg/secrets-store/server_test.go
  pkg/secrets-store/utils.go
  test/sanity/sanity_test.go
Labels: cncf-cla: yes, approved, size/XXL, lgtm

#698 test: set first pod ready wait timeout to 300s
  test/bats/azure.bats
Labels: cncf-cla: yes, size/XS, approved, lgtm

#695 helm: update chart repo to `https://kuberentes-sigs.github.io/secrets-store-csi-driver/charts`
  charts/secrets-store-csi-driver/README.md
  docs/book/src/getting-started/installation.md
  docs/book/src/getting-started/upgrades.md
  docs/book/theme/favicon.png
  manifest_staging/charts/secrets-store-csi-driver/README.md
Labels: cncf-cla: yes, approved, lgtm, size/M

#714 chore: use N1_HIGHCPU_8 for cloudbuild and update cloudbuild image
  docker/cloudbuild.yaml
Labels: cncf-cla: yes, size/XS, approved, lgtm

#633 tests: aws support for RELEASE tests
  test/scripts/initialize_eks_cluster.bash
Labels: cncf-cla: yes, approved, lgtm, size/S

#715 chore: bump version to v0.3.0 in release-0.3
  Makefile
  docker/Makefile
Labels: cncf-cla: yes, size/XS, approved, lgtm

#717 Automated cherry pick of #716: release: update manifests and helm chart for v0.3.0
  Makefile
  charts/secrets-store-csi-driver/Chart.yaml
  charts/secrets-store-csi-driver/README.md
  charts/secrets-store-csi-driver/templates/crds-upgrade-hook.yaml
  charts/secrets-store-csi-driver/templates/keep-crds-upgrade-hook.yaml
  charts/secrets-store-csi-driver/templates/secrets-store-csi-driver-windows.yaml
  charts/secrets-store-csi-driver/templates/secrets-store-csi-driver.yaml
  charts/secrets-store-csi-driver/values.yaml
  deploy/secrets-store-csi-driver-windows.yaml
  deploy/secrets-store-csi-driver.yaml
  manifest_staging/charts/secrets-store-csi-driver/Chart.yaml
  manifest_staging/charts/secrets-store-csi-driver/README.md
  manifest_staging/charts/secrets-store-csi-driver/values.yaml
  manifest_staging/deploy/secrets-store-csi-driver-windows.yaml
  manifest_staging/deploy/secrets-store-csi-driver.yaml
Labels: cncf-cla: yes, size/L, approved, lgtm

#716 release: update manifests and helm chart for v0.3.0
  Makefile
  charts/secrets-store-csi-driver/Chart.yaml
  charts/secrets-store-csi-driver/README.md
  charts/secrets-store-csi-driver/templates/crds-upgrade-hook.yaml
  charts/secrets-store-csi-driver/templates/keep-crds-upgrade-hook.yaml
  charts/secrets-store-csi-driver/templates/secrets-store-csi-driver-windows.yaml
  charts/secrets-store-csi-driver/templates/secrets-store-csi-driver.yaml
  charts/secrets-store-csi-driver/values.yaml
  deploy/secrets-store-csi-driver-windows.yaml
  deploy/secrets-store-csi-driver.yaml
  manifest_staging/charts/secrets-store-csi-driver/Chart.yaml
  manifest_staging/charts/secrets-store-csi-driver/README.md
  manifest_staging/charts/secrets-store-csi-driver/values.yaml
  manifest_staging/deploy/secrets-store-csi-driver-windows.yaml
  manifest_staging/deploy/secrets-store-csi-driver.yaml
Labels: cncf-cla: yes, size/L, approved, lgtm

#718 chore: update RELEASE docs based on v0.3.0 experience
  docs/RELEASE.md
Labels: cncf-cla: yes, approved, lgtm, size/M

#719 chore: missed updates from #716
  Makefile
  docker/Makefile
Labels: cncf-cla: yes, size/XS, approved, lgtm
