Repository kubernetes-sigs/secrets-store-csi-driver, pull requests merged in 2021-06, with the labels that each got.

#571 Added GOPROXY propagation to container builds
  Makefile
  docker/Dockerfile
  docker/windows.Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/M

#564 add tam7t as approver
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#510 fix(helm/values) - default syncSecret.enable to false
  Makefile
  manifest_staging/charts/secrets-store-csi-driver/README.md
  manifest_staging/charts/secrets-store-csi-driver/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#574 docs: fix the default volume path for providers
  docs/book/src/providers.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#577 Replace golang.org/x/net/context with context
  pkg/csi-common/controllerserver-default.go
  pkg/csi-common/identityserver-default.go
  pkg/csi-common/nodeserver-default.go
  pkg/csi-common/utils.go
  pkg/secrets-store/controllerserver.go
  pkg/secrets-store/identityserver.go
  pkg/secrets-store/nodeserver.go
  pkg/secrets-store/nodeserver_test.go
  pkg/secrets-store/utils.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#517 Add AWS Provider
  docs/book/src/concepts.md
  docs/book/src/introduction.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, ok-to-test, size/XS, tide/merge-method-squash

#581 chore: generate log if grpc message size larger than max
  pkg/secrets-store/provider_client.go
  pkg/secrets-store/provider_client_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#575 feat: add arm64 build
  Makefile
  docker/BASEIMAGE
  docker/Dockerfile
  docker/windows.Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/M

#563 docs: add membership criteria and getting involved section
  README.md
  docs/MEMBERSHIP.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/M

#584 docs: add aws provider ref in install provider
  docs/book/src/getting-started/installation.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#586 chore: enable qemu for multi-arch
  Makefile
  docker/build.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#587 feat: add rbac role and binding for rotation
  Makefile
  config/rbac-rotation/kustomization.yaml
  config/rbac-rotation/role.yaml
  config/rbac-rotation/role_binding.yaml
  docs/book/src/getting-started/installation.md
  manifest_staging/charts/secrets-store-csi-driver/templates/role-rotation.yaml
  manifest_staging/charts/secrets-store-csi-driver/templates/role-rotation_binding.yaml
  manifest_staging/deploy/rbac-secretproviderrotation.yaml
  pkg/rotation/reconciler.go
  test/bats/aws.bats
  test/bats/azure.bats
  test/bats/gcp.bats
  test/bats/vault.bats
Labels: approved, cncf-cla: yes, lgtm, size/L

#589 chore: bump version to v0.0.23
  Makefile
  docker/Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#590 release: update manifest and helm charts for v0.0.23
  charts/index.yaml
  charts/secrets-store-csi-driver-0.0.23.tgz
  charts/secrets-store-csi-driver/Chart.yaml
  charts/secrets-store-csi-driver/README.md
  charts/secrets-store-csi-driver/templates/role-rotation.yaml
  charts/secrets-store-csi-driver/templates/role-rotation_binding.yaml
  charts/secrets-store-csi-driver/templates/secrets-store-csi-driver-windows.yaml
  charts/secrets-store-csi-driver/templates/secrets-store-csi-driver.yaml
  charts/secrets-store-csi-driver/values.yaml
  deploy/rbac-secretproviderrotation.yaml
  deploy/secrets-store-csi-driver-windows.yaml
  deploy/secrets-store-csi-driver.yaml
  manifest_staging/charts/secrets-store-csi-driver/Chart.yaml
  manifest_staging/charts/secrets-store-csi-driver/README.md
  manifest_staging/charts/secrets-store-csi-driver/values.yaml
  manifest_staging/deploy/secrets-store-csi-driver-windows.yaml
  manifest_staging/deploy/secrets-store-csi-driver.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#591 docs: add upgrade instruction for v0.0.23
  docs/book/src/getting-started/upgrades.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#556 Debugging
  .gitignore
  .local/Dockerfile
  .local/README.md
  .local/debug-driver.yaml
  .local/kind-config.yaml
  .local/persistent-volume.yaml
  README.md
  pkg/version/version.go
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, ok-to-test, size/L, tide/merge-method-squash

#594 chore: set filtered-watch-secret to true by default for nodePublishSecretRef
  cmd/secrets-store-csi-driver/main.go
  manifest_staging/charts/secrets-store-csi-driver/README.md
  manifest_staging/charts/secrets-store-csi-driver/values.yaml
  manifest_staging/deploy/secrets-store-csi-driver-windows.yaml
  manifest_staging/deploy/secrets-store-csi-driver.yaml
  pkg/rotation/reconciler.go
  test/bats/azure.bats
  test/bats/gcp.bats
Labels: approved, cncf-cla: yes, lgtm, size/L

#593 chore: upgrades controller-runtime to v0.9.0
  Makefile
  cmd/secrets-store-csi-driver/main.go
  go.mod
  go.sum
  pkg/cache/README.md
  pkg/cache/cache.go
  pkg/cache/doc.go
  pkg/cache/informer_cache.go
  pkg/cache/internal/cache_reader.go
  pkg/cache/internal/deleg_map.go
  pkg/cache/internal/informers_map.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XXL, tide/merge-method-squash

#596 test: add e2e for `--filtered-watch-secret=false`
  test/bats/azure.bats
  test/bats/gcp.bats
Labels: approved, cncf-cla: yes, lgtm, size/M

#603 chore: update to debian-base v1.7.2 and update packages to fix CVEs
  Makefile
  docker/BASEIMAGE
  docker/Dockerfile
  docker/Makefile
Labels: approved, cncf-cla: yes, lgtm, size/S

#289 Move crds to crds dir for helm3 and installCRDs flag for supporting h…
  manifest_staging/charts/secrets-store-csi-driver/Chart.yaml
  manifest_staging/charts/secrets-store-csi-driver/README.md
  manifest_staging/charts/secrets-store-csi-driver/crds/secrets-store.csi.x-k8s.io_secretproviderclasses.yaml
  manifest_staging/charts/secrets-store-csi-driver/crds/secrets-store.csi.x-k8s.io_secretproviderclasspodstatuses.yaml
  manifest_staging/charts/secrets-store-csi-driver/templates/csidriver.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S, tide/merge-method-squash

#608 feat: use DynamicRESTMapper for manager
  cmd/secrets-store-csi-driver/main.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#606 chore: add warning message for sync secret forbidden error
  controllers/secretproviderclasspodstatus_controller.go
  pkg/rotation/reconciler.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#609 chore: update debian base to buster-v1.8.0
  Makefile
  docker/BASEIMAGE
  docker/Dockerfile
  docker/build.sh
  docker/windows.Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/S, tide/merge-method-squash

#555 Release management
  docs/Release_Management.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, ok-to-test, size/M, tide/merge-method-squash

#598 chore: removes local cache used for rotation
  cmd/secrets-store-csi-driver/main.go
  pkg/k8s/pod.go
  pkg/k8s/secretproviderclass.go
  pkg/k8s/secretproviderclasspodstatus.go
  pkg/k8s/store.go
  pkg/k8s/store_test.go
  pkg/rotation/reconciler.go
  pkg/rotation/reconciler_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XL, tide/merge-method-squash

#612 Possibility to annotate the created secret with CSI driver
  apis/v1alpha1/secretproviderclass_types.go
  config/crd/bases/secrets-store.csi.x-k8s.io_secretproviderclasses.yaml
  controllers/secretproviderclasspodstatus_controller.go
  controllers/secretproviderclasspodstatus_controller_test.go
  manifest_staging/charts/secrets-store-csi-driver/crds/secrets-store.csi.x-k8s.io_secretproviderclasses.yaml
  manifest_staging/deploy/secrets-store.csi.x-k8s.io_secretproviderclasses.yaml
  test/bats/tests/vault/vault_synck8s_v1alpha1_secretproviderclass.yaml
  test/bats/vault.bats
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M
