Repository kubernetes-sigs/secrets-store-csi-driver, pull requests merged in 2021-09, with the labels that each got.

#720 docs: fix typo in docs
  docs/book/src/getting-started/installation.md
  docs/book/src/getting-started/upgrades.md
  manifest_staging/charts/secrets-store-csi-driver/README.md
Labels: cncf-cla: yes, approved, kind/documentation, lgtm, size/S

#721 docs: fix typo in chart url
  charts/secrets-store-csi-driver/README.md
Labels: cncf-cla: yes, size/XS, approved, lgtm

#686 docs: Update Release_Management.md
  docs/Release_Management.md
Labels: cncf-cla: yes, approved, lgtm, size/S

#726 chore: rename references from master to main
  .github/PULL_REQUEST_TEMPLATE.md
  docker/cloudbuild.yaml
  docs/RELEASE.md
  docs/Release_Management.md
  docs/book/src/getting-started/installation.md
  docs/book/src/getting-started/usage.md
  docs/book/src/providers.md
Labels: cncf-cla: yes, approved, lgtm, size/M

#727 chore: add LICENSE to all files
  docker/Dockerfile
  docker/crd.Dockerfile
  docker/windows.Dockerfile
  pkg/metrics/exporter.go
  pkg/metrics/prometheus_exporter.go
  pkg/rotation/stats_reporter.go
  pkg/secrets-store/mocks/stats_reporter_mock.go
  pkg/secrets-store/stats_reporter.go
  pkg/util/fileutil/atomic_writer.go
  pkg/util/fileutil/writer.go
  pkg/version/version.go
  pkg/version/version_test.go
  test/e2eprovider/Dockerfile
  test/e2eprovider/e2e_provider.go
  test/e2eprovider/server/server.go
  test/e2eprovider/server/server_test.go
  test/e2eprovider/types/types.go
  test/sanity/sanity_test.go
  test/scripts/e2e_provider.sh
  test/scripts/initialize_eks_cluster.bash
Labels: cncf-cla: yes, size/L, approved, lgtm

#732 chore: remove deprecated --prometheus-port flag
  pkg/metrics/exporter.go
Labels: cncf-cla: yes, size/XS, approved, lgtm

#731 docs: add detail about pprof and metrics endpoint
  docs/book/src/topics/metrics.md
  docs/book/src/troubleshooting.md
Labels: cncf-cla: yes, approved, lgtm, size/S

#730 ci: add workflow for e2e using staging images
  .github/workflows/e2e.yaml
  Makefile
  docs/RELEASE.md
Labels: cncf-cla: yes, approved, tide/merge-method-squash, lgtm, size/M

#736 chore: use structured logging and update imports order
  cmd/secrets-store-csi-driver/main.go
  controllers/secretproviderclasspodstatus_controller.go
  controllers/secretproviderclasspodstatus_controller_test.go
  pkg/k8s/store.go
  pkg/k8s/store_test.go
  pkg/metrics/exporter.go
  pkg/metrics/prometheus_exporter.go
  pkg/rotation/reconciler.go
  pkg/rotation/reconciler_test.go
  pkg/secrets-store/controllerserver.go
  pkg/secrets-store/identityserver.go
  pkg/secrets-store/nodeserver.go
  pkg/secrets-store/provider_client.go
  pkg/secrets-store/provider_client_test.go
  pkg/secrets-store/secrets-store.go
  pkg/secrets-store/server.go
  pkg/util/fileutil/atomic_writer.go
  pkg/util/fileutil/filesystem_test.go
  pkg/util/secretutil/secret_test.go
  provider/fake/fake_server.go
  test/e2eprovider/e2e_provider.go
  test/e2eprovider/server/server_test.go
  test/sanity/sanity_test.go
Labels: cncf-cla: yes, size/L, approved, lgtm

#735 feat: create or update secretproviderclasspodstatus post mount
  cmd/secrets-store-csi-driver/main.go
  controllers/secretproviderclasspodstatus_controller_test.go
  pkg/rotation/reconciler.go
  pkg/rotation/reconciler_test.go
  pkg/secrets-store/nodeserver.go
  pkg/secrets-store/nodeserver_test.go
  pkg/secrets-store/secrets-store.go
  pkg/secrets-store/utils.go
  pkg/secrets-store/utils_test.go
  pkg/util/spcpsutil/spcps.go
  pkg/util/spcpsutil/spcps_test.go
  test/sanity/sanity_test.go
Labels: cncf-cla: yes, size/L, approved, lgtm

#737 docs: update design docs status
  docs/design/README.md
Labels: cncf-cla: yes, size/XS, approved, lgtm

#729 chore: update the initialDelaySeconds and timeoutSeconds for node-driver-registrar livenessprobe
  manifest_staging/charts/secrets-store-csi-driver/templates/secrets-store-csi-driver-windows.yaml
  manifest_staging/charts/secrets-store-csi-driver/templates/secrets-store-csi-driver.yaml
  manifest_staging/charts/secrets-store-csi-driver/values.yaml
  manifest_staging/deploy/secrets-store-csi-driver-windows.yaml
  manifest_staging/deploy/secrets-store-csi-driver.yaml
Labels: cncf-cla: yes, approved, lgtm, size/M

#738 chore: use `kubectl.kubernetes.io/default-container` annotation
  .local/debug-driver.yaml
  manifest_staging/charts/secrets-store-csi-driver/templates/secrets-store-csi-driver-windows.yaml
  manifest_staging/charts/secrets-store-csi-driver/templates/secrets-store-csi-driver.yaml
  manifest_staging/deploy/secrets-store-csi-driver-windows.yaml
  manifest_staging/deploy/secrets-store-csi-driver.yaml
Labels: cncf-cla: yes, approved, lgtm, size/S

#741 feat: adds support for inplace upgrade test
  test/bats/e2e-provider.bats
Labels: cncf-cla: yes, approved, lgtm, size/M

#742 chore: update to debian-base:bullseye-v1.0.0
  Makefile
  docker/BASEIMAGE
  docker/Dockerfile
Labels: cncf-cla: yes, approved, lgtm, size/S

#744 chore: bump version to v1.0.0-rc.0 in release-1.0
  Makefile
  docker/Makefile
Labels: cncf-cla: yes, size/XS, approved, lgtm

#754 Automated cherry pick of #753: release: update manifest and helm charts for v1.0.0-rc.0
  charts/secrets-store-csi-driver/Chart.yaml
  charts/secrets-store-csi-driver/README.md
  charts/secrets-store-csi-driver/templates/secrets-store-csi-driver-windows.yaml
  charts/secrets-store-csi-driver/templates/secrets-store-csi-driver.yaml
  charts/secrets-store-csi-driver/values.yaml
  deploy/secrets-store-csi-driver-windows.yaml
  deploy/secrets-store-csi-driver.yaml
  manifest_staging/charts/secrets-store-csi-driver/Chart.yaml
  manifest_staging/charts/secrets-store-csi-driver/README.md
  manifest_staging/charts/secrets-store-csi-driver/values.yaml
  manifest_staging/deploy/secrets-store-csi-driver-windows.yaml
  manifest_staging/deploy/secrets-store-csi-driver.yaml
Labels: cncf-cla: yes, approved, lgtm, size/M

#753 release: update manifest and helm charts for v1.0.0-rc.0
  Makefile
  charts/secrets-store-csi-driver/Chart.yaml
  charts/secrets-store-csi-driver/README.md
  charts/secrets-store-csi-driver/templates/secrets-store-csi-driver-windows.yaml
  charts/secrets-store-csi-driver/templates/secrets-store-csi-driver.yaml
  charts/secrets-store-csi-driver/values.yaml
  deploy/secrets-store-csi-driver-windows.yaml
  deploy/secrets-store-csi-driver.yaml
  docker/Makefile
  manifest_staging/charts/secrets-store-csi-driver/Chart.yaml
  manifest_staging/charts/secrets-store-csi-driver/README.md
  manifest_staging/charts/secrets-store-csi-driver/values.yaml
  manifest_staging/deploy/secrets-store-csi-driver-windows.yaml
  manifest_staging/deploy/secrets-store-csi-driver.yaml
Labels: cncf-cla: yes, approved, lgtm, size/M

#752 fix: inplace upgrade test
  test/bats/e2e-provider.bats
  test/e2eprovider/server/server.go
Labels: cncf-cla: yes, size/XS, approved, tide/merge-method-squash, kind/failing-test, lgtm

#756 feat: adds windows server 2022
  Makefile
  docker/BASEIMAGE
  docker/BASEIMAGE_CORE
Labels: cncf-cla: yes, size/XS, approved, ok-to-test, tide/merge-method-squash, lgtm

#757 Automated cherry pick of #756: feat: adds windows server 2022
  Makefile
  docker/BASEIMAGE
  docker/BASEIMAGE_CORE
Labels: cncf-cla: yes, size/XS, approved, ok-to-test, tide/merge-method-squash, lgtm

#758 tests: add e2e test for vault rotation
  test/bats/tests/vault/pod-vault-rotation.yaml
  test/bats/vault.bats
Labels: cncf-cla: yes, approved, lgtm, size/M
