Repository kubernetes-sigs/secrets-store-csi-driver, pull requests merged in 2021-11, with the labels that each got.

#797 docs: Update helm README.md with linux crd image values
  manifest_staging/charts/secrets-store-csi-driver/README.md
Labels: cncf-cla: yes, size/XS, approved, ok-to-test, tide/merge-method-squash, lgtm

#798 chore: use TARGETARCH for image build and makefile update
  Makefile
  docker/build.sh
  docker/crd.Dockerfile
Labels: cncf-cla: yes, approved, lgtm, size/M

#800 docs: update features and add toc
  .gitignore
  README.md
  docs/book/Makefile
  docs/book/book.toml
  docs/book/install-and-build.sh
  docs/book/src/concepts.md
  docs/book/src/design-docs.md
  docs/book/src/getting-started/upgrades.md
  docs/book/src/introduction.md
  docs/book/src/known-limitations.md
  docs/book/src/providers.md
  docs/book/src/release-management.md
  docs/book/src/troubleshooting.md
  docs/book/util-embed.sh
  docs/book/util-releaselink.sh
  docs/book/util-tabulate.sh
  netlify.toml
  third_party/japaric/trust/LICENSE
  third_party/japaric/trust/crate_install.sh
Labels: cncf-cla: yes, approved, lgtm, size/XL

#802 chore: upgrade kubernetes deps
  go.mod
  go.sum
Labels: cncf-cla: yes, approved, lgtm, size/M

#803 chore: bump livenessprobe image to v2.5.0
  manifest_staging/charts/secrets-store-csi-driver/README.md
  manifest_staging/charts/secrets-store-csi-driver/values.yaml
  manifest_staging/deploy/secrets-store-csi-driver-windows.yaml
  manifest_staging/deploy/secrets-store-csi-driver.yaml
Labels: cncf-cla: yes, approved, lgtm, size/S

#804 chore: remove deprecated `--filtered-watch-secret` flag
  .local/Dockerfile
  Makefile
  cmd/secrets-store-csi-driver/main.go
  manifest_staging/charts/secrets-store-csi-driver/README.md
  manifest_staging/charts/secrets-store-csi-driver/templates/secrets-store-csi-driver-windows.yaml
  manifest_staging/charts/secrets-store-csi-driver/templates/secrets-store-csi-driver.yaml
  manifest_staging/charts/secrets-store-csi-driver/values.yaml
  manifest_staging/deploy/secrets-store-csi-driver-windows.yaml
  manifest_staging/deploy/secrets-store-csi-driver.yaml
  pkg/rotation/reconciler_test.go
  test/bats/azure.bats
Labels: cncf-cla: yes, approved, lgtm, size/M

#807 chore: bump node-driver-registrar image to v2.4.0
  manifest_staging/charts/secrets-store-csi-driver/README.md
  manifest_staging/charts/secrets-store-csi-driver/values.yaml
  manifest_staging/deploy/secrets-store-csi-driver-windows.yaml
  manifest_staging/deploy/secrets-store-csi-driver.yaml
Labels: cncf-cla: yes, approved, lgtm, size/S

#808 ci: add markdown-link-check workflow
  .github/workflows/markdown-link-check.yaml
  README.md
  docs/MEMBERSHIP.md
  docs/book/src/concepts.md
  docs/book/src/getting-started/usage.md
  sample/ingress-controller-tls/README.md
Labels: cncf-cla: yes, approved, lgtm, size/M

#814 images: use k8s-staging-test-infra/gcb-docker-gcloud
  docker/cloudbuild.yaml
Labels: cncf-cla: yes, size/XS, approved, lgtm
