Repository kubernetes-sigs/secrets-store-csi-driver, pull requests merged in 2021-10, with the labels that each got.

#762 chore: enable additional linters
  .golangci.yml
Labels: cncf-cla: yes, size/XS, approved, ok-to-test, tide/merge-method-squash, lgtm

#724 docs: providers support matrix
  docs/book/src/providers.md
Labels: cncf-cla: yes, size/XS, approved, tide/merge-method-squash, lgtm

#751 docs: add supported kubernetes versions
  docs/Release_Management.md
  docs/book/src/getting-started/installation.md
Labels: cncf-cla: yes, approved, kind/documentation, lgtm, size/S

#764 test: log the secrets-store API version
  test/bats/e2e-provider.bats
  test/bats/helpers.bash
Labels: cncf-cla: yes, size/XS, approved, lgtm

#767 chore: bump version 1.0.0 rc.1
  Makefile
  docker/Makefile
Labels: cncf-cla: yes, size/XS, approved, lgtm

#769 fix: update base image core for ltsc2022
  docker/BASEIMAGE
Labels: cncf-cla: yes, size/XS, approved, lgtm

#770 Automated cherry pick of #769: fix: update base image core for ltsc2022
  docker/BASEIMAGE
Labels: cncf-cla: yes, size/XS, approved, lgtm

#773 Automated cherry pick of #772: release: update manifests and helm chart for 1.0.0-rc.1
  charts/secrets-store-csi-driver/Chart.yaml
  charts/secrets-store-csi-driver/README.md
  charts/secrets-store-csi-driver/crds/secrets-store.csi.x-k8s.io_secretproviderclasses.yaml
  charts/secrets-store-csi-driver/crds/secrets-store.csi.x-k8s.io_secretproviderclasspodstatuses.yaml
  charts/secrets-store-csi-driver/values.yaml
  deploy/secrets-store-csi-driver-windows.yaml
  deploy/secrets-store-csi-driver.yaml
  deploy/secrets-store.csi.x-k8s.io_secretproviderclasses.yaml
  deploy/secrets-store.csi.x-k8s.io_secretproviderclasspodstatuses.yaml
  manifest_staging/charts/secrets-store-csi-driver/Chart.yaml
  manifest_staging/charts/secrets-store-csi-driver/README.md
  manifest_staging/charts/secrets-store-csi-driver/values.yaml
  manifest_staging/deploy/secrets-store-csi-driver-windows.yaml
  manifest_staging/deploy/secrets-store-csi-driver.yaml
Labels: cncf-cla: yes, size/L, approved, lgtm

#772 release: update manifests and helm chart for 1.0.0-rc.1
  Makefile
  charts/secrets-store-csi-driver/Chart.yaml
  charts/secrets-store-csi-driver/README.md
  charts/secrets-store-csi-driver/crds/secrets-store.csi.x-k8s.io_secretproviderclasses.yaml
  charts/secrets-store-csi-driver/crds/secrets-store.csi.x-k8s.io_secretproviderclasspodstatuses.yaml
  charts/secrets-store-csi-driver/values.yaml
  deploy/secrets-store-csi-driver-windows.yaml
  deploy/secrets-store-csi-driver.yaml
  deploy/secrets-store.csi.x-k8s.io_secretproviderclasses.yaml
  deploy/secrets-store.csi.x-k8s.io_secretproviderclasspodstatuses.yaml
  docker/Makefile
  manifest_staging/charts/secrets-store-csi-driver/Chart.yaml
  manifest_staging/charts/secrets-store-csi-driver/README.md
  manifest_staging/charts/secrets-store-csi-driver/values.yaml
  manifest_staging/deploy/secrets-store-csi-driver-windows.yaml
  manifest_staging/deploy/secrets-store-csi-driver.yaml
Labels: cncf-cla: yes, size/L, approved, lgtm

#774 test: add k8s test matrix for staging e2e
  .github/workflows/e2e.yaml
Labels: cncf-cla: yes, size/XS, approved, lgtm
