Repository kubernetes-sigs/secrets-store-csi-driver, pull requests merged in 2021-03, with the labels that each got.

#461 proto: add helpers and tools to install proto utilities
  Makefile
  hack/tools/go.mod
  hack/tools/go.sum
  hack/tools/tools.go
  provider/v1alpha1/service.pb.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#466 docs: fix urls in providers doc
  docs/book/src/providers.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/S

#468 docs: add design docs url and remove old docs
  docs/README.limitations.md
  docs/README.metrics.md
  docs/README.new-provider.md
  docs/README.rotation.md
  docs/design/README.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/L

#470 fix: CVE-2021-24032
  Makefile
  docker/Dockerfile
  docker/Makefile
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS

#465 docs: update doc links in usage doc
  docs/book/src/getting-started/usage.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#473 chore: upgrade to controller-runtime v0.8.2
  cmd/secrets-store-csi-driver/main.go
  controllers/secretproviderclasspodstatus_controller.go
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/L

#458 feat: add filtered watch for reconcile
  cmd/secrets-store-csi-driver/main.go
  controllers/secretproviderclasspodstatus_controller.go
  controllers/secretproviderclasspodstatus_controller_test.go
  pkg/cache/README.md
  pkg/cache/cache.go
  pkg/cache/doc.go
  pkg/cache/informer_cache.go
  pkg/cache/internal/cache_reader.go
  pkg/cache/internal/deleg_map.go
  pkg/cache/internal/informers_map.go
  pkg/k8s/store.go
  pkg/k8s/store_test.go
  pkg/rotation/reconciler.go
  pkg/rotation/reconciler_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#462 feat: connect to plugins at runtime instead of configuration
  Makefile
  cmd/secrets-store-csi-driver/main.go
  docs/book/src/providers.md
  manifest_staging/charts/secrets-store-csi-driver/README.md
  manifest_staging/charts/secrets-store-csi-driver/templates/secrets-store-csi-driver-windows.yaml
  manifest_staging/charts/secrets-store-csi-driver/templates/secrets-store-csi-driver.yaml
  manifest_staging/charts/secrets-store-csi-driver/values.yaml
  manifest_staging/deploy/secrets-store-csi-driver-windows.yaml
  manifest_staging/deploy/secrets-store-csi-driver.yaml
  pkg/rotation/reconciler.go
  pkg/rotation/reconciler_test.go
  pkg/secrets-store/nodeserver.go
  pkg/secrets-store/nodeserver_test.go
  pkg/secrets-store/provider_client.go
  pkg/secrets-store/provider_client_test.go
  pkg/secrets-store/secrets-store.go
  provider/fake/fake_server.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#479 test: add e2e for filtered watch secret
  manifest_staging/charts/secrets-store-csi-driver/README.md
  manifest_staging/charts/secrets-store-csi-driver/templates/secrets-store-csi-driver-windows.yaml
  manifest_staging/charts/secrets-store-csi-driver/templates/secrets-store-csi-driver.yaml
  manifest_staging/charts/secrets-store-csi-driver/values.yaml
  test/bats/azure.bats
  test/bats/gcp.bats
  test/bats/vault.bats
Labels: approved, cncf-cla: yes, lgtm, size/M

#484 test: update vault e2e to use versioned deployment
  test/bats/vault.bats
Labels: approved, cncf-cla: yes, lgtm, size/XS

#486 chore: remove v1.15 yamls and update doc
  docs/book/src/concepts.md
  docs/book/src/getting-started/installation.md
  docs/book/src/introduction.md
  manifest_staging/deploy/csidriver-1.15.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#487 test: add make target for installing chart releases
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/M

#491 ci: add helm deploy target for windows tests
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#493 fix: prevent duplicate owner references
  controllers/secretproviderclasspodstatus_controller.go
  controllers/secretproviderclasspodstatus_controller_test.go
  test/bats/azure.bats
  test/bats/vault.bats
Labels: approved, cncf-cla: yes, lgtm, size/S

#490 dial: grpc naming is not compatible with windows unix socket
  pkg/secrets-store/provider_client.go
  test/bats/azure.bats
Labels: approved, cncf-cla: yes, lgtm, size/S

#488 chore: update servercore reference to windows-servercore-cache
  Makefile
  docker/BASEIMAGE_CORE
  docker/windows.Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/S

#480 test: update tests to use multi-os image
  test/bats/azure.bats
  test/bats/gcp.bats
  test/bats/tests/azure/deployment-synck8s-azure.yaml
  test/bats/tests/azure/deployment-two-synck8s-azure.yaml
  test/bats/tests/azure/pod-azure-inline-volume-multiple-spc.yaml
  test/bats/tests/azure/pod-secrets-store-inline-volume-crd.yaml
  test/bats/tests/azure/rotation/pod-synck8s-azure.yaml
  test/bats/tests/gcp/pod-secrets-store-inline-volume-crd.yaml
  test/bats/tests/vault/deployment-synck8s.yaml
  test/bats/tests/vault/deployment-two-synck8s.yaml
  test/bats/tests/vault/pod-vault-inline-volume-multiple-spc.yaml
  test/bats/tests/vault/pod-vault-inline-volume-secretproviderclass.yaml
  test/bats/vault.bats
Labels: approved, cncf-cla: yes, lgtm, size/L

#494 docs: use multi-os image for examples and update urls
  docs/book/src/getting-started/usage.md
  docs/book/src/topics/set-as-env-var.md
  docs/book/src/topics/sync-as-kubernetes-secret.md
  sample/ingress-controller-tls/README.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/M

#481 feat: allow providers to have the driver write files
  pkg/errors/errors.go
  pkg/secrets-store/nodeserver_test.go
  pkg/secrets-store/provider_client.go
  pkg/secrets-store/provider_client_test.go
  pkg/test_utils/tmpdir/tmpdir.go
  pkg/util/fileutil/filesystem.go
  pkg/util/fileutil/filesystem_test.go
  pkg/util/fileutil/writer.go
  pkg/util/fileutil/writer_test.go
  provider/fake/fake_server.go
  provider/v1alpha1/service.pb.go
  provider/v1alpha1/service.proto
Labels: approved, cncf-cla: yes, lgtm, size/XL
