Repository kubernetes-sigs/secrets-store-csi-driver, pull requests merged in 2022-10, with the labels that each got.

#1058 fix: handles pfx certs in k8s secrets sync
  go.mod
  go.sum
  pkg/util/secretutil/secret.go
  pkg/util/secretutil/secret_test.go
Labels: kind/bug, cncf-cla: yes, size/L, approved, lgtm

#1059 security: fix CVE-2022-32149
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/e2eprovider/go.mod
  test/e2eprovider/go.sum
Labels: kind/bug, cncf-cla: yes, approved, ok-to-test, tide/merge-method-squash, lgtm, size/S

#1060 chore: use kubectl 1.25.x in driver-crds
  Makefile
  docker/crd.Dockerfile
Labels: kind/feature, cncf-cla: yes, size/XS, approved, lgtm

#1061 chore: use `golang:1.19` builder for driver
  docker/Dockerfile
Labels: kind/bug, cncf-cla: yes, size/XS, approved, lgtm

#1062 chore: add dependabot.yml
  .github/dependabot.yml
Labels: kind/feature, cncf-cla: yes, approved, lgtm, size/S

#1081 ci: add codeql action
  .github/workflows/codeql.yaml
Labels: kind/feature, cncf-cla: yes, approved, lgtm, size/M

#1086 fix: escape dot in target path regex
  .github/workflows/codeql.yaml
  pkg/util/fileutil/filesystem.go
  pkg/util/fileutil/filesystem_test.go
Labels: kind/bug, cncf-cla: yes, size/XS, approved, lgtm
