Repository kubernetes-sigs/secrets-store-csi-driver, pull requests merged in 2022-05, with the labels that each got.

#944 ci: fix markdown link check workflow failures
  .github/workflows/markdown-link-check.yaml
  .markdownlinkcheck.json
  docs/book/src/SUMMARY.md
Labels: cncf-cla: yes, approved, lgtm, size/S

#945 chore: update pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: cncf-cla: yes, approved, lgtm, size/S

#943 test: cleanup provider tests (part 1)
  test/bats/aws.bats
  test/bats/azure.bats
  test/bats/gcp.bats
  test/bats/vault.bats
Labels: cncf-cla: yes, size/L, approved, lgtm

#946 chore: bump kind version to v0.13.0 to support kubernetes v1.24
  Makefile
Labels: kind/feature, cncf-cla: yes, size/XS, approved, lgtm

#954 security: fix CVE-2022-1292
  docker/Dockerfile
Labels: cncf-cla: yes, size/XS, approved, lgtm

#955 ci: fix aws eks cluster creation
  Makefile
  test/scripts/initialize_eks_cluster.bash
Labels: cncf-cla: yes, approved, kind/failing-test, lgtm, size/S

#956 chore: bump `node-driver-registrar:v2.5.1` and `livenessprobe:v2.7.0`
  manifest_staging/charts/secrets-store-csi-driver/README.md
  manifest_staging/charts/secrets-store-csi-driver/templates/secrets-store-csi-driver-windows.yaml
  manifest_staging/charts/secrets-store-csi-driver/templates/secrets-store-csi-driver.yaml
  manifest_staging/charts/secrets-store-csi-driver/values.yaml
  manifest_staging/deploy/secrets-store-csi-driver-windows.yaml
  manifest_staging/deploy/secrets-store-csi-driver.yaml
Labels: kind/feature, cncf-cla: yes, approved, lgtm, size/M

#957 docs: include security explanations for root/privileged/and pod tokens
  docs/book/src/concepts.md
Labels: cncf-cla: yes, approved, kind/documentation, lgtm, size/S

#951 add nilekhc to reviewers
  OWNERS
Labels: cncf-cla: yes, size/XS, approved, lgtm

#958 ci: add kubernetes 1.24 in e2e matrix
  .github/workflows/e2e.yaml
Labels: kind/feature, cncf-cla: yes, size/XS, approved, lgtm

#959 chore: update debian-base to bullseye-v1.3.0
  docker/Dockerfile
Labels: kind/feature, cncf-cla: yes, size/XS, approved, lgtm

#961 security: fix CVE-2022-1664
  docker/Dockerfile
Labels: kind/bug, cncf-cla: yes, size/XS, approved, lgtm

#962 chore: add `crds.podLabels` for helm hook jobs
  manifest_staging/charts/secrets-store-csi-driver/README.md
  manifest_staging/charts/secrets-store-csi-driver/templates/crds-upgrade-hook.yaml
  manifest_staging/charts/secrets-store-csi-driver/templates/csidriver.yaml
  manifest_staging/charts/secrets-store-csi-driver/templates/keep-crds-upgrade-hook.yaml
  manifest_staging/charts/secrets-store-csi-driver/templates/secrets-store-csi-driver-windows.yaml
  manifest_staging/charts/secrets-store-csi-driver/templates/secrets-store-csi-driver.yaml
  manifest_staging/charts/secrets-store-csi-driver/values.yaml
Labels: kind/feature, cncf-cla: yes, approved, ok-to-test, tide/merge-method-squash, kind/cleanup, lgtm, size/M
