Repository kubernetes-sigs/secrets-store-csi-driver, pull requests merged in 2022-09, with the labels that each got.

#1040 chore: support kubernetes v1.25.0
  Makefile
  cmd/secrets-store-csi-driver/main.go
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  pkg/client/clientset/versioned/fake/register.go
  pkg/client/clientset/versioned/scheme/register.go
  pkg/k8s/token.go
  pkg/secrets-store/provider_client.go
  pkg/util/fileutil/atomic_writer.go
  pkg/version/version.go
  test/e2eprovider/go.mod
  test/e2eprovider/go.sum
Labels: kind/feature, cncf-cla: yes, approved, lgtm, size/XL

#1042 chore: bump version to v1.2.4 in release-1.2
  Makefile
  docker/Makefile
Labels: kind/feature, cncf-cla: yes, size/XS, approved, lgtm

#1044 Automated cherry pick of #1043: release: update manifest and helm charts for v1.2.4
  charts/secrets-store-csi-driver/Chart.yaml
  charts/secrets-store-csi-driver/README.md
  charts/secrets-store-csi-driver/templates/_helpers.tpl
  charts/secrets-store-csi-driver/templates/crds-upgrade-hook.yaml
  charts/secrets-store-csi-driver/templates/csidriver.yaml
  charts/secrets-store-csi-driver/templates/keep-crds-upgrade-hook.yaml
  charts/secrets-store-csi-driver/templates/podsecuritypolicy.yaml
  charts/secrets-store-csi-driver/templates/role-rotation.yaml
  charts/secrets-store-csi-driver/templates/role-rotation_binding.yaml
  charts/secrets-store-csi-driver/templates/role-secretproviderclasses-admin.yaml
  charts/secrets-store-csi-driver/templates/role-secretproviderclasses-viewer.yaml
  charts/secrets-store-csi-driver/templates/role-syncsecret.yaml
  charts/secrets-store-csi-driver/templates/role-syncsecret_binding.yaml
  charts/secrets-store-csi-driver/templates/role-tokenrequest.yaml
  charts/secrets-store-csi-driver/templates/role-tokenrequest_binding.yaml
  charts/secrets-store-csi-driver/templates/role.yaml
  charts/secrets-store-csi-driver/templates/role_binding.yaml
  charts/secrets-store-csi-driver/templates/secrets-store-csi-driver-windows.yaml
  charts/secrets-store-csi-driver/templates/secrets-store-csi-driver.yaml
  charts/secrets-store-csi-driver/templates/serviceaccount.yaml
  charts/secrets-store-csi-driver/values.yaml
  deploy/secrets-store-csi-driver-windows.yaml
  deploy/secrets-store-csi-driver.yaml
  manifest_staging/charts/secrets-store-csi-driver/Chart.yaml
  manifest_staging/charts/secrets-store-csi-driver/README.md
  manifest_staging/charts/secrets-store-csi-driver/values.yaml
  manifest_staging/deploy/secrets-store-csi-driver-windows.yaml
  manifest_staging/deploy/secrets-store-csi-driver.yaml
Labels: cncf-cla: yes, size/L, approved, lgtm

#1043 release: update manifest and helm charts for v1.2.4
  Makefile
  charts/secrets-store-csi-driver/Chart.yaml
  charts/secrets-store-csi-driver/README.md
  charts/secrets-store-csi-driver/templates/_helpers.tpl
  charts/secrets-store-csi-driver/templates/crds-upgrade-hook.yaml
  charts/secrets-store-csi-driver/templates/csidriver.yaml
  charts/secrets-store-csi-driver/templates/keep-crds-upgrade-hook.yaml
  charts/secrets-store-csi-driver/templates/podsecuritypolicy.yaml
  charts/secrets-store-csi-driver/templates/role-rotation.yaml
  charts/secrets-store-csi-driver/templates/role-rotation_binding.yaml
  charts/secrets-store-csi-driver/templates/role-secretproviderclasses-admin.yaml
  charts/secrets-store-csi-driver/templates/role-secretproviderclasses-viewer.yaml
  charts/secrets-store-csi-driver/templates/role-syncsecret.yaml
  charts/secrets-store-csi-driver/templates/role-syncsecret_binding.yaml
  charts/secrets-store-csi-driver/templates/role-tokenrequest.yaml
  charts/secrets-store-csi-driver/templates/role-tokenrequest_binding.yaml
  charts/secrets-store-csi-driver/templates/role.yaml
  charts/secrets-store-csi-driver/templates/role_binding.yaml
  charts/secrets-store-csi-driver/templates/secrets-store-csi-driver-windows.yaml
  charts/secrets-store-csi-driver/templates/secrets-store-csi-driver.yaml
  charts/secrets-store-csi-driver/templates/serviceaccount.yaml
  charts/secrets-store-csi-driver/values.yaml
  deploy/secrets-store-csi-driver-windows.yaml
  deploy/secrets-store-csi-driver.yaml
  docker/Makefile
  manifest_staging/charts/secrets-store-csi-driver/Chart.yaml
  manifest_staging/charts/secrets-store-csi-driver/README.md
  manifest_staging/charts/secrets-store-csi-driver/values.yaml
  manifest_staging/deploy/secrets-store-csi-driver-windows.yaml
  manifest_staging/deploy/secrets-store-csi-driver.yaml
Labels: kind/feature, cncf-cla: yes, size/L, approved, lgtm

#1045 ci: bump kubernetes version to v1.25.0
  .github/workflows/e2e.yaml
Labels: kind/feature, cncf-cla: yes, size/XS, approved, lgtm

#1049 security: fix multiple CVEs
  docker/Dockerfile
Labels: kind/bug, cncf-cla: yes, size/XS, approved, lgtm

#1050 chore: run apt update && apt upgrade -y in dockerfile
  docker/Dockerfile
Labels: cncf-cla: yes, size/XS, approved, kind/cleanup, lgtm

#1053 security: fix CVE-2022-27664
  go.mod
  go.sum
  test/e2eprovider/go.mod
  test/e2eprovider/go.sum
Labels: kind/bug, cncf-cla: yes, approved, lgtm, size/S

#1054 chore: update golangci-lint to v1.49.0
  .golangci.yml
  cmd/secrets-store-csi-driver/main.go
  hack/tools/go.mod
  hack/tools/go.sum
  test/e2eprovider/e2e_provider.go
Labels: cncf-cla: yes, size/L, approved, kind/cleanup, lgtm
