Repository kubernetes-sigs/secrets-store-csi-driver, pull requests merged in 2022-02, with the labels that each got.

#847 docs: remove helm repo url change note in install steps
  docs/book/src/getting-started/installation.md
  manifest_staging/charts/secrets-store-csi-driver/README.md
Labels: cncf-cla: yes, approved, lgtm, size/S

#848 feat: send NodePublishVolumeRequest.VolumeContext in MountRequest to provider
  pkg/secrets-store/nodeserver.go
  pkg/secrets-store/nodeserver_test.go
Labels: cncf-cla: yes, approved, lgtm, size/S

#849 ci: fix shellcheck file paths
  Makefile
Labels: cncf-cla: yes, size/XS, approved, lgtm

#805 feat: add token requests client
  Makefile
  cmd/secrets-store-csi-driver/main.go
  config/rbac-tokenrequest/kustomization.yaml
  config/rbac-tokenrequest/role.yaml
  config/rbac-tokenrequest/role_binding.yaml
  config/rbac/role.yaml
  controllers/secretproviderclasspodstatus_controller.go
  controllers/tokenrequest/tokenrequest.go
  go.mod
  go.sum
  manifest_staging/charts/secrets-store-csi-driver/README.md
  manifest_staging/charts/secrets-store-csi-driver/templates/csidriver.yaml
  manifest_staging/charts/secrets-store-csi-driver/templates/role-tokenrequest.yaml
  manifest_staging/charts/secrets-store-csi-driver/templates/role-tokenrequest_binding.yaml
  manifest_staging/charts/secrets-store-csi-driver/templates/role.yaml
  manifest_staging/charts/secrets-store-csi-driver/values.yaml
  manifest_staging/deploy/rbac-secretproviderclass.yaml
  manifest_staging/deploy/rbac-secretprovidertokenrequest.yaml
  pkg/k8s/token.go
  pkg/k8s/token_test.go
  pkg/rotation/reconciler.go
  pkg/rotation/reconciler_test.go
  pkg/secrets-store/nodeserver.go
  pkg/secrets-store/nodeserver_test.go
  pkg/secrets-store/secrets-store.go
  test/bats/e2e-provider.bats
  test/bats/helpers.bash
  test/e2eprovider/e2e_provider.go
  test/e2eprovider/go.mod
  test/e2eprovider/go.sum
  test/e2eprovider/server/server.go
  test/e2eprovider/server/server_test.go
  test/sanity/sanity_test.go
Labels: cncf-cla: yes, approved, size/XXL, tide/merge-method-squash, lgtm

#853 refactor: use NewSharedInformerFactoryWithOptions for new shared informer
  pkg/k8s/token.go
  pkg/k8s/token_test.go
Labels: cncf-cla: yes, approved, lgtm, size/M

#856 chore: mark `v1alpha1` api version as deprecated
  apis/v1alpha1/secretproviderclass_types.go
  apis/v1alpha1/secretproviderclasspodstatus_types.go
  config/crd/bases/secrets-store.csi.x-k8s.io_secretproviderclasses.yaml
  config/crd/bases/secrets-store.csi.x-k8s.io_secretproviderclasspodstatuses.yaml
  manifest_staging/charts/secrets-store-csi-driver/crds/secrets-store.csi.x-k8s.io_secretproviderclasses.yaml
  manifest_staging/charts/secrets-store-csi-driver/crds/secrets-store.csi.x-k8s.io_secretproviderclasspodstatuses.yaml
  manifest_staging/deploy/secrets-store.csi.x-k8s.io_secretproviderclasses.yaml
  manifest_staging/deploy/secrets-store.csi.x-k8s.io_secretproviderclasspodstatuses.yaml
Labels: cncf-cla: yes, approved, lgtm, size/S

#854 ci: add goreleaser workflow for release
  .github/workflows/create-release.yaml
  .goreleaser.yml
Labels: cncf-cla: yes, approved, lgtm, size/M

#859 chore: bump version to v1.1.0-rc.0 in release-1.1
  Makefile
  docker/Makefile
Labels: cncf-cla: yes, size/XS, approved, lgtm

#861 ci: update e2e_mock_provider_tests kubernetes versions
  .github/workflows/e2e.yaml
Labels: cncf-cla: yes, size/XS, approved, lgtm

#864 Automated cherry pick of #863: release: update manifest and helm charts for v1.1.0-rc.0
  charts/secrets-store-csi-driver/Chart.yaml
  charts/secrets-store-csi-driver/README.md
  charts/secrets-store-csi-driver/crds/secrets-store.csi.x-k8s.io_secretproviderclasses.yaml
  charts/secrets-store-csi-driver/crds/secrets-store.csi.x-k8s.io_secretproviderclasspodstatuses.yaml
  charts/secrets-store-csi-driver/templates/csidriver.yaml
  charts/secrets-store-csi-driver/templates/role-secretproviderclasses-admin.yaml
  charts/secrets-store-csi-driver/templates/role-secretproviderclasses-viewer.yaml
  charts/secrets-store-csi-driver/templates/role-tokenrequest.yaml
  charts/secrets-store-csi-driver/templates/role-tokenrequest_binding.yaml
  charts/secrets-store-csi-driver/templates/role.yaml
  charts/secrets-store-csi-driver/values.yaml
  deploy/rbac-secretproviderclass.yaml
  deploy/rbac-secretprovidertokenrequest.yaml
  deploy/role-secretproviderclasses-admin.yaml
  deploy/role-secretproviderclasses-viewer.yaml
  deploy/secrets-store-csi-driver-windows.yaml
  deploy/secrets-store-csi-driver.yaml
  deploy/secrets-store.csi.x-k8s.io_secretproviderclasses.yaml
  deploy/secrets-store.csi.x-k8s.io_secretproviderclasspodstatuses.yaml
  manifest_staging/charts/secrets-store-csi-driver/Chart.yaml
  manifest_staging/charts/secrets-store-csi-driver/README.md
  manifest_staging/charts/secrets-store-csi-driver/values.yaml
  manifest_staging/deploy/secrets-store-csi-driver-windows.yaml
  manifest_staging/deploy/secrets-store-csi-driver.yaml
Labels: cncf-cla: yes, size/L, approved, lgtm

#863 release: update manifest and helm charts for v1.1.0-rc.0
  Makefile
  charts/secrets-store-csi-driver/Chart.yaml
  charts/secrets-store-csi-driver/README.md
  charts/secrets-store-csi-driver/crds/secrets-store.csi.x-k8s.io_secretproviderclasses.yaml
  charts/secrets-store-csi-driver/crds/secrets-store.csi.x-k8s.io_secretproviderclasspodstatuses.yaml
  charts/secrets-store-csi-driver/templates/csidriver.yaml
  charts/secrets-store-csi-driver/templates/role-secretproviderclasses-admin.yaml
  charts/secrets-store-csi-driver/templates/role-secretproviderclasses-viewer.yaml
  charts/secrets-store-csi-driver/templates/role-tokenrequest.yaml
  charts/secrets-store-csi-driver/templates/role-tokenrequest_binding.yaml
  charts/secrets-store-csi-driver/templates/role.yaml
  charts/secrets-store-csi-driver/values.yaml
  deploy/rbac-secretproviderclass.yaml
  deploy/rbac-secretprovidertokenrequest.yaml
  deploy/role-secretproviderclasses-admin.yaml
  deploy/role-secretproviderclasses-viewer.yaml
  deploy/secrets-store-csi-driver-windows.yaml
  deploy/secrets-store-csi-driver.yaml
  deploy/secrets-store.csi.x-k8s.io_secretproviderclasses.yaml
  deploy/secrets-store.csi.x-k8s.io_secretproviderclasspodstatuses.yaml
  docker/Makefile
  manifest_staging/charts/secrets-store-csi-driver/Chart.yaml
  manifest_staging/charts/secrets-store-csi-driver/README.md
  manifest_staging/charts/secrets-store-csi-driver/values.yaml
  manifest_staging/deploy/secrets-store-csi-driver-windows.yaml
  manifest_staging/deploy/secrets-store-csi-driver.yaml
Labels: cncf-cla: yes, size/L, approved, lgtm

#874 Automated cherry pick of #873: fix: add unit test to validate error shadowed bug
  pkg/secrets-store/nodeserver.go
  pkg/secrets-store/nodeserver_test.go
Labels: cncf-cla: yes, approved, lgtm, size/M

#851 feat: support provider paths under /var/run
  cmd/secrets-store-csi-driver/main.go
  manifest_staging/charts/secrets-store-csi-driver/templates/secrets-store-csi-driver-windows.yaml
  manifest_staging/charts/secrets-store-csi-driver/templates/secrets-store-csi-driver.yaml
  manifest_staging/charts/secrets-store-csi-driver/values.yaml
  manifest_staging/deploy/secrets-store-csi-driver.yaml
  pkg/rotation/reconciler_test.go
  pkg/secrets-store/nodeserver_test.go
  pkg/secrets-store/provider_client.go
  pkg/secrets-store/provider_client_test.go
  test/e2eprovider/e2e-provider-installer.yaml
Labels: cncf-cla: yes, size/L, approved, lgtm

#872 test: conditionally check token requests role and binding
  test/bats/e2e-provider.bats
Labels: cncf-cla: yes, approved, kind/failing-test, lgtm, size/S

#876 Automated cherry pick of #851: feat: support provider paths under /var/run
  cmd/secrets-store-csi-driver/main.go
  manifest_staging/charts/secrets-store-csi-driver/templates/secrets-store-csi-driver-windows.yaml
  manifest_staging/charts/secrets-store-csi-driver/templates/secrets-store-csi-driver.yaml
  manifest_staging/charts/secrets-store-csi-driver/values.yaml
  manifest_staging/deploy/secrets-store-csi-driver.yaml
  pkg/rotation/reconciler_test.go
  pkg/secrets-store/nodeserver_test.go
  pkg/secrets-store/provider_client.go
  pkg/secrets-store/provider_client_test.go
  test/e2eprovider/e2e-provider-installer.yaml
Labels: cncf-cla: yes, size/L, approved, lgtm

#875 Automated cherry pick of #871: chore: bump `node-driver-registrar:v2.5.0` and
  manifest_staging/charts/secrets-store-csi-driver/README.md
  manifest_staging/charts/secrets-store-csi-driver/values.yaml
  manifest_staging/deploy/secrets-store-csi-driver-windows.yaml
  manifest_staging/deploy/secrets-store-csi-driver.yaml
Labels: cncf-cla: yes, approved, lgtm, size/S

#877 chore: make token requests conditional for v1.20+
  manifest_staging/charts/secrets-store-csi-driver/README.md
  manifest_staging/charts/secrets-store-csi-driver/templates/csidriver.yaml
  manifest_staging/charts/secrets-store-csi-driver/values.yaml
Labels: cncf-cla: yes, size/XS, approved, lgtm

#882 chore: bump version to v1.1.0 in release-1.1
  Makefile
  docker/Makefile
Labels: cncf-cla: yes, size/XS, approved, lgtm

#884 Automated cherry pick of #883: release: update manifest and helm charts for v1.1.0
  charts/secrets-store-csi-driver/Chart.yaml
  charts/secrets-store-csi-driver/README.md
  charts/secrets-store-csi-driver/templates/csidriver.yaml
  charts/secrets-store-csi-driver/templates/secrets-store-csi-driver-windows.yaml
  charts/secrets-store-csi-driver/templates/secrets-store-csi-driver.yaml
  charts/secrets-store-csi-driver/values.yaml
  deploy/secrets-store-csi-driver-windows.yaml
  deploy/secrets-store-csi-driver.yaml
  manifest_staging/charts/secrets-store-csi-driver/Chart.yaml
  manifest_staging/charts/secrets-store-csi-driver/README.md
  manifest_staging/charts/secrets-store-csi-driver/values.yaml
  manifest_staging/deploy/secrets-store-csi-driver-windows.yaml
  manifest_staging/deploy/secrets-store-csi-driver.yaml
Labels: cncf-cla: yes, size/L, approved, lgtm

#883 release: update manifest and helm charts for v1.1.0
  Makefile
  charts/secrets-store-csi-driver/Chart.yaml
  charts/secrets-store-csi-driver/README.md
  charts/secrets-store-csi-driver/templates/csidriver.yaml
  charts/secrets-store-csi-driver/templates/secrets-store-csi-driver-windows.yaml
  charts/secrets-store-csi-driver/templates/secrets-store-csi-driver.yaml
  charts/secrets-store-csi-driver/values.yaml
  deploy/secrets-store-csi-driver-windows.yaml
  deploy/secrets-store-csi-driver.yaml
  docker/Makefile
  manifest_staging/charts/secrets-store-csi-driver/Chart.yaml
  manifest_staging/charts/secrets-store-csi-driver/README.md
  manifest_staging/charts/secrets-store-csi-driver/values.yaml
  manifest_staging/deploy/secrets-store-csi-driver-windows.yaml
  manifest_staging/deploy/secrets-store-csi-driver.yaml
Labels: cncf-cla: yes, size/L, approved, lgtm

#850 chore: remove old helm packages and index
  charts/index.yaml
  charts/secrets-store-csi-driver-0.0.10.tgz
  charts/secrets-store-csi-driver-0.0.11.tgz
  charts/secrets-store-csi-driver-0.0.12.tgz
  charts/secrets-store-csi-driver-0.0.13.tgz
  charts/secrets-store-csi-driver-0.0.14.tgz
  charts/secrets-store-csi-driver-0.0.15.tgz
  charts/secrets-store-csi-driver-0.0.16.tgz
  charts/secrets-store-csi-driver-0.0.17.tgz
  charts/secrets-store-csi-driver-0.0.18.tgz
  charts/secrets-store-csi-driver-0.0.19.tgz
  charts/secrets-store-csi-driver-0.0.20.tgz
  charts/secrets-store-csi-driver-0.0.21.tgz
  charts/secrets-store-csi-driver-0.0.22.tgz
  charts/secrets-store-csi-driver-0.0.23.tgz
  charts/secrets-store-csi-driver-0.0.9.tgz
  charts/secrets-store-csi-driver-0.1.0.tgz
  charts/secrets-store-csi-driver-0.2.0.tgz
Labels: cncf-cla: yes, size/L, approved, lgtm

#888 fix: panic when using `--log-format-json` is set to true
  cmd/secrets-store-csi-driver/main.go
Labels: cncf-cla: yes, size/XS, approved, lgtm

#889 Automated cherry pick of #888: fix: panic when using --log-format-json
  cmd/secrets-store-csi-driver/main.go
Labels: cncf-cla: yes, size/XS, approved, lgtm
