Repository kubernetes-sigs/secrets-store-csi-driver, pull requests merged in 2022-11, with the labels that each got.

#1094 ci: ignore slack badge in markdown link check
  .markdownlinkcheck.json
Labels: cncf-cla: yes, size/XS, approved, kind/failing-test, lgtm

#1092 chore: update livenessprobe to v2.8.0
  manifest_staging/charts/secrets-store-csi-driver/README.md
  manifest_staging/charts/secrets-store-csi-driver/values.yaml
  manifest_staging/deploy/secrets-store-csi-driver-windows.yaml
  manifest_staging/deploy/secrets-store-csi-driver.yaml
Labels: kind/feature, cncf-cla: yes, approved, lgtm, size/S

#1096 fix: put annotations in right position of daemonset
  manifest_staging/charts/secrets-store-csi-driver/templates/secrets-store-csi-driver.yaml
Labels: kind/bug, cncf-cla: yes, size/XS, approved, ok-to-test, lgtm

#1095 chore: remove k8s.io/kubernetes dep
  go.mod
  go.sum
  pkg/k8s/token.go
  pkg/k8s/token/token_manager.go
  pkg/k8s/token/token_manager_test.go
  pkg/k8s/token_test.go
Labels: cncf-cla: yes, approved, size/XXL, kind/cleanup, lgtm

#1098 chore: use kubectl 1.25.4 in driver-crds
  Makefile
  docker/crd.Dockerfile
Labels: kind/feature, cncf-cla: yes, size/XS, approved, lgtm

#1085 feat: Support disabling Helm chart CRD hooks
  manifest_staging/charts/secrets-store-csi-driver/README.md
  manifest_staging/charts/secrets-store-csi-driver/templates/crds-upgrade-hook.yaml
  manifest_staging/charts/secrets-store-csi-driver/templates/keep-crds-upgrade-hook.yaml
  manifest_staging/charts/secrets-store-csi-driver/values.yaml
Labels: kind/feature, cncf-cla: yes, size/XS, approved, lgtm

#1090 feat(helm-chart): Add option to override resource requests and limits…
  manifest_staging/charts/secrets-store-csi-driver/README.md
  manifest_staging/charts/secrets-store-csi-driver/templates/crds-upgrade-hook.yaml
  manifest_staging/charts/secrets-store-csi-driver/templates/keep-crds-upgrade-hook.yaml
  manifest_staging/charts/secrets-store-csi-driver/values.yaml
Labels: kind/feature, cncf-cla: yes, approved, ok-to-test, tide/merge-method-squash, lgtm, size/S

#1102 docs: fix typo in concepts doc
  docs/book/src/concepts.md
Labels: cncf-cla: yes, size/XS, approved, ok-to-test, kind/documentation, lgtm
