Repository kubernetes-sigs/secrets-store-csi-driver, pull requests merged in 2022-06, with the labels that each got.

#964 fix: remove files before cleanup mount point in unpublish
  pkg/secrets-store/nodeserver.go
Labels: kind/bug, cncf-cla: yes, approved, lgtm, size/M

#966 chore: update kubernetes deps to v1.24.1
  cmd/secrets-store-csi-driver/main.go
  go.mod
  go.sum
  pkg/secrets-store/provider_client.go
  test/e2eprovider/go.mod
  test/e2eprovider/go.sum
Labels: kind/feature, cncf-cla: yes, size/L, approved, lgtm

#965 fix: multiple podLabels for linux.crds in helm charts
  manifest_staging/charts/secrets-store-csi-driver/templates/crds-upgrade-hook.yaml
  manifest_staging/charts/secrets-store-csi-driver/templates/keep-crds-upgrade-hook.yaml
Labels: kind/bug, cncf-cla: yes, size/XS, approved, ok-to-test, lgtm

#971 fix: increase hook-weight for crd upgrade jobs in helm charts
  manifest_staging/charts/secrets-store-csi-driver/templates/crds-upgrade-hook.yaml
  manifest_staging/charts/secrets-store-csi-driver/templates/keep-crds-upgrade-hook.yaml
Labels: kind/bug, cncf-cla: yes, size/XS, approved, ok-to-test, lgtm

#972 chore: update tools dependencies and generate manifests
  Makefile
  config/crd/bases/secrets-store.csi.x-k8s.io_secretproviderclasses.yaml
  config/crd/bases/secrets-store.csi.x-k8s.io_secretproviderclasspodstatuses.yaml
  config/rbac-rotation/role.yaml
  config/rbac-syncsecret/role.yaml
  config/rbac-tokenrequest/role.yaml
  config/rbac/role.yaml
  hack/tools/go.mod
  hack/tools/go.sum
  hack/tools/tools.go
  manifest_staging/charts/secrets-store-csi-driver/crds/secrets-store.csi.x-k8s.io_secretproviderclasses.yaml
  manifest_staging/charts/secrets-store-csi-driver/crds/secrets-store.csi.x-k8s.io_secretproviderclasspodstatuses.yaml
  manifest_staging/charts/secrets-store-csi-driver/templates/role-rotation.yaml
  manifest_staging/charts/secrets-store-csi-driver/templates/role-syncsecret.yaml
  manifest_staging/charts/secrets-store-csi-driver/templates/role-tokenrequest.yaml
  manifest_staging/charts/secrets-store-csi-driver/templates/role.yaml
  manifest_staging/deploy/secrets-store.csi.x-k8s.io_secretproviderclasses.yaml
  manifest_staging/deploy/secrets-store.csi.x-k8s.io_secretproviderclasspodstatuses.yaml
Labels: kind/feature, cncf-cla: yes, approved, lgtm, size/XL

#974 ci: bump kind version to v0.14.0
  .github/workflows/e2e.yaml
Labels: kind/bug, cncf-cla: yes, size/XS, approved, lgtm

#975 release: update manifest and helm charts for v1.2.0
  Makefile
  charts/secrets-store-csi-driver/Chart.yaml
  charts/secrets-store-csi-driver/README.md
  charts/secrets-store-csi-driver/crds/secrets-store.csi.x-k8s.io_secretproviderclasses.yaml
  charts/secrets-store-csi-driver/crds/secrets-store.csi.x-k8s.io_secretproviderclasspodstatuses.yaml
  charts/secrets-store-csi-driver/templates/crds-upgrade-hook.yaml
  charts/secrets-store-csi-driver/templates/csidriver.yaml
  charts/secrets-store-csi-driver/templates/keep-crds-upgrade-hook.yaml
  charts/secrets-store-csi-driver/templates/role-rotation.yaml
  charts/secrets-store-csi-driver/templates/role-syncsecret.yaml
  charts/secrets-store-csi-driver/templates/role-tokenrequest.yaml
  charts/secrets-store-csi-driver/templates/role.yaml
  charts/secrets-store-csi-driver/templates/secrets-store-csi-driver-windows.yaml
  charts/secrets-store-csi-driver/templates/secrets-store-csi-driver.yaml
  charts/secrets-store-csi-driver/values.yaml
  deploy/secrets-store-csi-driver-windows.yaml
  deploy/secrets-store-csi-driver.yaml
  deploy/secrets-store.csi.x-k8s.io_secretproviderclasses.yaml
  deploy/secrets-store.csi.x-k8s.io_secretproviderclasspodstatuses.yaml
  docker/Makefile
  manifest_staging/charts/secrets-store-csi-driver/Chart.yaml
  manifest_staging/charts/secrets-store-csi-driver/README.md
  manifest_staging/charts/secrets-store-csi-driver/values.yaml
  manifest_staging/deploy/secrets-store-csi-driver-windows.yaml
  manifest_staging/deploy/secrets-store-csi-driver.yaml
Labels: kind/feature, cncf-cla: yes, size/L, approved, lgtm

#977 docs: update supported releases - v1.2.x and v1.1.x
  docs/book/src/getting-started/installation.md
  docs/book/src/introduction.md
Labels: cncf-cla: yes, size/XS, approved, kind/documentation, lgtm

#978 chore: use `google.golang.org/protobuf` and regenerate proto
  Makefile
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  hack/tools/tools.go
  pkg/secrets-store/identityserver.go
  provider/v1alpha1/service.pb.go
  provider/v1alpha1/service.proto
  provider/v1alpha1/service_grpc.pb.go
  test/e2eprovider/go.mod
  test/e2eprovider/go.sum
Labels: kind/feature, cncf-cla: yes, size/L, approved, lgtm

#979 chore: update boilerplate for the generated proto files
  Makefile
  hack/boilerplate.go.txt
  provider/v1alpha1/service_grpc.pb.go
Labels: kind/feature, cncf-cla: yes, approved, lgtm, size/S

#980 security: fix CVE-2022-2068
  Makefile
  docker/Dockerfile
  docker/Makefile
Labels: kind/bug, cncf-cla: yes, size/XS, approved, lgtm
