Repository kubernetes-sigs/secrets-store-csi-driver, pull requests merged in 2022-01, with the labels that each got.

#825 chore: update debian-base to bullseye-v1.1.0
  docker/BASEIMAGE
  docker/Dockerfile
Labels: cncf-cla: yes, approved, lgtm, size/S

#826 security: fix CVE-2021-43618
  docker/Dockerfile
Labels: cncf-cla: yes, size/XS, approved, lgtm

#828 chore: log invalid key in error
  pkg/util/secretutil/secret.go
Labels: cncf-cla: yes, size/XS, approved, lgtm

#834 Automated cherry pick of #822: docs: add slack badge
  Makefile
  README.md
Labels: cncf-cla: yes, size/XS, approved, lgtm

#830 Automated cherry pick of #807: chore: bump node-driver-reegistrar image to v2.4.0
  manifest_staging/charts/secrets-store-csi-driver/README.md
  manifest_staging/charts/secrets-store-csi-driver/values.yaml
  manifest_staging/deploy/secrets-store-csi-driver-windows.yaml
  manifest_staging/deploy/secrets-store-csi-driver.yaml
Labels: cncf-cla: yes, approved, lgtm, size/S

#831 Automated cherry pick of #814: images: use k8s-staging-test-infra/gcb-docker-gcloud
  docker/cloudbuild.yaml
Labels: cncf-cla: yes, size/XS, approved, lgtm

#832 Automated cherry pick of #825: chore: update debian-base to bullseye-v1.1.0
  docker/BASEIMAGE
  docker/Dockerfile
Labels: cncf-cla: yes, approved, lgtm, size/S

#833 Automated cherry pick of #826: security: fix CVE-2021-43618
  docker/Dockerfile
Labels: cncf-cla: yes, size/XS, approved, lgtm

#839 chore: bump version to 1.0.1 in release-1.0
  Makefile
  docker/Makefile
Labels: cncf-cla: yes, size/XS, approved, lgtm

#841 Automated cherry pick of #840: release: update manifests and helm chart for 1.0.1
  charts/secrets-store-csi-driver/Chart.yaml
  charts/secrets-store-csi-driver/README.md
  charts/secrets-store-csi-driver/templates/keep-crds-upgrade-hook.yaml
  charts/secrets-store-csi-driver/templates/secrets-store-csi-driver-windows.yaml
  charts/secrets-store-csi-driver/templates/secrets-store-csi-driver.yaml
  charts/secrets-store-csi-driver/values.yaml
  deploy/secrets-store-csi-driver-windows.yaml
  deploy/secrets-store-csi-driver.yaml
  manifest_staging/charts/secrets-store-csi-driver/Chart.yaml
  manifest_staging/charts/secrets-store-csi-driver/README.md
  manifest_staging/charts/secrets-store-csi-driver/values.yaml
  manifest_staging/deploy/secrets-store-csi-driver-windows.yaml
  manifest_staging/deploy/secrets-store-csi-driver.yaml
Labels: cncf-cla: yes, approved, lgtm, size/M

#840 release: update manifests and helm chart for 1.0.1
  Makefile
  charts/secrets-store-csi-driver/Chart.yaml
  charts/secrets-store-csi-driver/README.md
  charts/secrets-store-csi-driver/templates/keep-crds-upgrade-hook.yaml
  charts/secrets-store-csi-driver/templates/secrets-store-csi-driver-windows.yaml
  charts/secrets-store-csi-driver/templates/secrets-store-csi-driver.yaml
  charts/secrets-store-csi-driver/values.yaml
  deploy/secrets-store-csi-driver-windows.yaml
  deploy/secrets-store-csi-driver.yaml
  docker/Makefile
  manifest_staging/charts/secrets-store-csi-driver/Chart.yaml
  manifest_staging/charts/secrets-store-csi-driver/README.md
  manifest_staging/charts/secrets-store-csi-driver/values.yaml
  manifest_staging/deploy/secrets-store-csi-driver-windows.yaml
  manifest_staging/deploy/secrets-store-csi-driver.yaml
Labels: cncf-cla: yes, approved, lgtm, size/M

#843 security: fix CVE-2021-3995, CVE-2021-3996
  Makefile
  docker/Dockerfile
  docker/Makefile
Labels: cncf-cla: yes, size/XS, approved, lgtm

#844 Automated cherry pick of #843: security: fix CVE-2021-3995, CVE-2021-3996
  Makefile
  docker/Dockerfile
  docker/Makefile
Labels: cncf-cla: yes, size/XS, approved, lgtm

#836 helm: additional cluster roles for secretproviderclasses
  manifest_staging/charts/secrets-store-csi-driver/templates/role-secretproviderclasses-admin.yaml
  manifest_staging/charts/secrets-store-csi-driver/templates/role-secretproviderclasses-viewer.yaml
  manifest_staging/deploy/role-secretproviderclasses-admin.yaml
  manifest_staging/deploy/role-secretproviderclasses-viewer.yaml
Labels: cncf-cla: yes, approved, ok-to-test, tide/merge-method-squash, lgtm, size/M

#845 test: add test for view and admin cluster role
  Makefile
  test/bats/e2e-provider.bats
Labels: cncf-cla: yes, size/XS, approved, ok-to-test, tide/merge-method-squash, lgtm

#846 chore: updates trivy command
  Makefile
Labels: cncf-cla: yes, size/XS, approved, lgtm
