Repository kubernetes-sigs/secrets-store-csi-driver, pull requests merged in 2022-08, with the labels that each got.

#1018 security: fix multiple CVEs
  docker/Dockerfile
Labels: kind/bug, cncf-cla: yes, size/XS, approved, lgtm

#1021 chore: bump version to v1.2.3 in release-1.2
  Makefile
  docker/Makefile
Labels: kind/feature, cncf-cla: yes, size/XS, approved, lgtm

#1023 Automated cherry pick of #1022: release: update manifest and helm charts for v1.2.3
  charts/secrets-store-csi-driver/Chart.yaml
  charts/secrets-store-csi-driver/README.md
  charts/secrets-store-csi-driver/values.yaml
  deploy/secrets-store-csi-driver-windows.yaml
  deploy/secrets-store-csi-driver.yaml
  manifest_staging/charts/secrets-store-csi-driver/Chart.yaml
  manifest_staging/charts/secrets-store-csi-driver/README.md
  manifest_staging/charts/secrets-store-csi-driver/values.yaml
  manifest_staging/deploy/secrets-store-csi-driver-windows.yaml
  manifest_staging/deploy/secrets-store-csi-driver.yaml
Labels: cncf-cla: yes, approved, lgtm, size/M

#1022 release: update manifest and helm charts for v1.2.3
  Makefile
  charts/secrets-store-csi-driver/Chart.yaml
  charts/secrets-store-csi-driver/README.md
  charts/secrets-store-csi-driver/values.yaml
  deploy/secrets-store-csi-driver-windows.yaml
  deploy/secrets-store-csi-driver.yaml
  docker/Makefile
  manifest_staging/charts/secrets-store-csi-driver/Chart.yaml
  manifest_staging/charts/secrets-store-csi-driver/README.md
  manifest_staging/charts/secrets-store-csi-driver/values.yaml
  manifest_staging/deploy/secrets-store-csi-driver-windows.yaml
  manifest_staging/deploy/secrets-store-csi-driver.yaml
Labels: kind/feature, cncf-cla: yes, approved, lgtm, size/M

#1029 security: fix CVE-2022-1996
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/e2eprovider/go.mod
  test/e2eprovider/go.sum
Labels: kind/bug, cncf-cla: yes, size/L, approved, lgtm

#1016 feat: add support for common labels in helm charts
  manifest_staging/charts/secrets-store-csi-driver/README.md
  manifest_staging/charts/secrets-store-csi-driver/templates/_helpers.tpl
  manifest_staging/charts/secrets-store-csi-driver/templates/crds-upgrade-hook.yaml
  manifest_staging/charts/secrets-store-csi-driver/templates/csidriver.yaml
  manifest_staging/charts/secrets-store-csi-driver/templates/keep-crds-upgrade-hook.yaml
  manifest_staging/charts/secrets-store-csi-driver/templates/podsecuritypolicy.yaml
  manifest_staging/charts/secrets-store-csi-driver/templates/role-rotation.yaml
  manifest_staging/charts/secrets-store-csi-driver/templates/role-rotation_binding.yaml
  manifest_staging/charts/secrets-store-csi-driver/templates/role-secretproviderclasses-admin.yaml
  manifest_staging/charts/secrets-store-csi-driver/templates/role-secretproviderclasses-viewer.yaml
  manifest_staging/charts/secrets-store-csi-driver/templates/role-syncsecret.yaml
  manifest_staging/charts/secrets-store-csi-driver/templates/role-syncsecret_binding.yaml
  manifest_staging/charts/secrets-store-csi-driver/templates/role-tokenrequest.yaml
  manifest_staging/charts/secrets-store-csi-driver/templates/role-tokenrequest_binding.yaml
  manifest_staging/charts/secrets-store-csi-driver/templates/role.yaml
  manifest_staging/charts/secrets-store-csi-driver/templates/role_binding.yaml
  manifest_staging/charts/secrets-store-csi-driver/templates/secrets-store-csi-driver-windows.yaml
  manifest_staging/charts/secrets-store-csi-driver/templates/secrets-store-csi-driver.yaml
  manifest_staging/charts/secrets-store-csi-driver/templates/serviceaccount.yaml
  manifest_staging/charts/secrets-store-csi-driver/values.yaml
Labels: kind/feature, cncf-cla: yes, approved, ok-to-test, lgtm, size/M

#1030 fix: update base image reference in script
  Makefile
  docker/BASEIMAGE
  docker/Makefile
Labels: cncf-cla: yes, size/XS, approved, lgtm

#1031 Automated cherry pick of #1029: security: fix CVE-2022-1996
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/e2eprovider/go.mod
  test/e2eprovider/go.sum
Labels: cncf-cla: yes, size/L, approved, lgtm

#1033 chore: update debian-base to bullseye-v1.4.2
  docker/BASEIMAGE
  docker/Dockerfile
Labels: cncf-cla: yes, approved, lgtm, size/S

#1036 security: fix CVE-2022-37434
  docker/Dockerfile
Labels: kind/bug, cncf-cla: yes, size/XS, approved, lgtm

#1028 fix: (fileutil) WritePayloads atomically for nested paths
  pkg/util/fileutil/writer.go
  pkg/util/fileutil/writer_test.go
Labels: kind/bug, cncf-cla: yes, approved, ok-to-test, tide/merge-method-squash, lgtm, size/M

#1038 chore: remove psp
  manifest_staging/charts/secrets-store-csi-driver/templates/crds-upgrade-hook.yaml
  manifest_staging/charts/secrets-store-csi-driver/templates/keep-crds-upgrade-hook.yaml
  manifest_staging/charts/secrets-store-csi-driver/templates/podsecuritypolicy.yaml
  manifest_staging/charts/secrets-store-csi-driver/templates/role.yaml
Labels: cncf-cla: yes, approved, kind/cleanup, lgtm, size/S
