Repository kubernetes-sigs/secrets-store-csi-driver, pull requests merged in 2022-03, with the labels that each got.

#891 chore: bump version to 1.1.1 in release-1.1
  Makefile
  docker/Makefile
Labels: cncf-cla: yes, size/XS, approved, lgtm

#893 Automated cherry pick of #892: release: update manifests and helm chart for 1.1.1
  charts/secrets-store-csi-driver/Chart.yaml
  charts/secrets-store-csi-driver/README.md
  charts/secrets-store-csi-driver/values.yaml
  deploy/secrets-store-csi-driver-windows.yaml
  deploy/secrets-store-csi-driver.yaml
  manifest_staging/charts/secrets-store-csi-driver/Chart.yaml
  manifest_staging/charts/secrets-store-csi-driver/README.md
  manifest_staging/charts/secrets-store-csi-driver/values.yaml
  manifest_staging/deploy/secrets-store-csi-driver-windows.yaml
  manifest_staging/deploy/secrets-store-csi-driver.yaml
Labels: cncf-cla: yes, approved, lgtm, size/M

#892 release: update manifests and helm chart for 1.1.1
  Makefile
  charts/secrets-store-csi-driver/Chart.yaml
  charts/secrets-store-csi-driver/README.md
  charts/secrets-store-csi-driver/values.yaml
  deploy/secrets-store-csi-driver-windows.yaml
  deploy/secrets-store-csi-driver.yaml
  docker/Makefile
  manifest_staging/charts/secrets-store-csi-driver/Chart.yaml
  manifest_staging/charts/secrets-store-csi-driver/README.md
  manifest_staging/charts/secrets-store-csi-driver/values.yaml
  manifest_staging/deploy/secrets-store-csi-driver-windows.yaml
  manifest_staging/deploy/secrets-store-csi-driver.yaml
Labels: cncf-cla: yes, approved, lgtm, size/M

#898 validate additionalProviderPaths does not contain providerPath
  manifest_staging/charts/secrets-store-csi-driver/templates/secrets-store-csi-driver-windows.yaml
  manifest_staging/charts/secrets-store-csi-driver/templates/secrets-store-csi-driver.yaml
Labels: cncf-cla: yes, approved, ok-to-test, lgtm, size/S

#900 security: fix CVE-2022-0778, CVE-2021-4160
  Makefile
  docker/Dockerfile
  docker/Makefile
Labels: cncf-cla: yes, size/XS, approved, lgtm

#901 Automated cherry pick of #900: security: fix CVE-2022-0778, CVE-2021-4160
  Makefile
  docker/Dockerfile
  docker/Makefile
Labels: cncf-cla: yes, size/XS, approved, lgtm

#907 docs: update supported versions and replace v1alpha1 with v1
  docs/book/src/concepts.md
  docs/book/src/introduction.md
  docs/book/src/topics/set-as-env-var.md
Labels: cncf-cla: yes, approved, lgtm, size/S

#908 docs: add subPath volume mount limitation
  docs/book/src/known-limitations.md
Labels: cncf-cla: yes, approved, lgtm, size/S

#903 docs: add command reference
  docs/book/src/SUMMARY.md
  docs/book/src/topics/command-reference.md
Labels: cncf-cla: yes, approved, ok-to-test, lgtm, size/S

#912 chore: upgrade to go 1.18
  .golangci.yml
  docker/Dockerfile
  docker/windows.Dockerfile
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/e2eprovider/Dockerfile
  test/e2eprovider/go.mod
  test/e2eprovider/go.sum
Labels: cncf-cla: yes, approved, size/XXL, lgtm

#914 security: fix CVEs
  docker/Dockerfile
Labels: cncf-cla: yes, size/XS, approved, lgtm

#916 chore: update golangci-lint to v1.45.2 and pin to go 1.17
  .golangci.yml
  hack/tools/go.mod
  hack/tools/go.sum
Labels: cncf-cla: yes, approved, lgtm, size/XL

#915 Automated cherry pick of #914: security: fix CVEs
  docker/Dockerfile
Labels: cncf-cla: yes, size/XS, approved, lgtm

#917 chore: upgrade makefile test binary versions
  Makefile
Labels: cncf-cla: yes, approved, lgtm, size/S

#918 chore: bump version 1.1.2
  Makefile
  docker/Makefile
Labels: cncf-cla: yes, size/XS, approved, lgtm

#919 release: update manifests and helm chart for 1.1.2
  Makefile
  charts/secrets-store-csi-driver/Chart.yaml
  charts/secrets-store-csi-driver/README.md
  charts/secrets-store-csi-driver/templates/secrets-store-csi-driver-windows.yaml
  charts/secrets-store-csi-driver/templates/secrets-store-csi-driver.yaml
  charts/secrets-store-csi-driver/values.yaml
  deploy/secrets-store-csi-driver-windows.yaml
  deploy/secrets-store-csi-driver.yaml
  docker/Makefile
  manifest_staging/charts/secrets-store-csi-driver/Chart.yaml
  manifest_staging/charts/secrets-store-csi-driver/README.md
  manifest_staging/charts/secrets-store-csi-driver/values.yaml
  manifest_staging/deploy/secrets-store-csi-driver-windows.yaml
  manifest_staging/deploy/secrets-store-csi-driver.yaml
Labels: cncf-cla: yes, approved, lgtm, size/M
