Repository kubernetes-sigs/secrets-store-csi-driver, pull requests merged in 2022-04, with the labels that each got.

#924 Automated cherry pick of #923: security: fix CVE-2018-25032 and update to
  Makefile
  docker/Dockerfile
  docker/Makefile
Labels: cncf-cla: yes, approved, lgtm, size/S

#910 test: add e2e for akeyless csi provider
  Makefile
  test/bats/akeyless.bats
  test/bats/tests/akeyless/pod-inline-volume-secretproviderclass.yaml
  test/bats/tests/akeyless/secretproviderclass.yaml
Labels: cncf-cla: yes, size/L, approved, ok-to-test, lgtm

#926 docs: update instructions on generating release notes
  docs/RELEASE.md
Labels: cncf-cla: yes, approved, lgtm, size/S

#927 ci: update kubernetes version matrix in staging e2e workflow
  .github/workflows/e2e.yaml
Labels: cncf-cla: yes, size/XS, approved, lgtm

#925 chore: change default to `/var/run` for providers path
  cmd/secrets-store-csi-driver/main.go
  manifest_staging/charts/secrets-store-csi-driver/README.md
  manifest_staging/charts/secrets-store-csi-driver/values.yaml
  manifest_staging/deploy/secrets-store-csi-driver.yaml
Labels: cncf-cla: yes, size/L, approved, lgtm

#930 test: use helm charts for azure provider
  test/bats/azure.bats
Labels: cncf-cla: yes, approved, lgtm, size/S

#933 test: use helm upgrade --install for azure e2e
  test/bats/azure.bats
Labels: cncf-cla: yes, size/XS, approved, lgtm

#934 security: fix CVE-2022-1271
  docker/Dockerfile
Labels: cncf-cla: yes, size/XS, approved, lgtm

#935 Automated cherry pick of #934: security: fix CVE-2022-1271
  docker/Dockerfile
Labels: cncf-cla: yes, size/XS, approved, lgtm
