Repository kubernetes-sigs/secrets-store-csi-driver, pull requests merged in 2023-03, with the labels that each got.

#1187 chore: bump version to v1.3.2 in release-1.3
  Makefile
  docker/Makefile
Labels: kind/feature, cncf-cla: yes, size/XS, approved, lgtm

#1194 Automated cherry pick of #1193: release: update manifest and helm charts for v1.3.2
  charts/secrets-store-csi-driver/Chart.yaml
  charts/secrets-store-csi-driver/README.md
  charts/secrets-store-csi-driver/values.yaml
  deploy/secrets-store-csi-driver-windows.yaml
  deploy/secrets-store-csi-driver.yaml
  manifest_staging/charts/secrets-store-csi-driver/Chart.yaml
  manifest_staging/charts/secrets-store-csi-driver/README.md
  manifest_staging/charts/secrets-store-csi-driver/values.yaml
  manifest_staging/deploy/secrets-store-csi-driver-windows.yaml
  manifest_staging/deploy/secrets-store-csi-driver.yaml
Labels: cncf-cla: yes, approved, lgtm, size/M

#1193 release: update manifest and helm charts for v1.3.2
  charts/secrets-store-csi-driver/Chart.yaml
  charts/secrets-store-csi-driver/README.md
  charts/secrets-store-csi-driver/values.yaml
  deploy/secrets-store-csi-driver-windows.yaml
  deploy/secrets-store-csi-driver.yaml
  manifest_staging/charts/secrets-store-csi-driver/Chart.yaml
  manifest_staging/charts/secrets-store-csi-driver/README.md
  manifest_staging/charts/secrets-store-csi-driver/values.yaml
  manifest_staging/deploy/secrets-store-csi-driver-windows.yaml
  manifest_staging/deploy/secrets-store-csi-driver.yaml
Labels: kind/feature, cncf-cla: yes, approved, lgtm, size/M

#1195 chore: update golangci-lint to v1.52.1
  .golangci.yml
  Makefile
  hack/tools/go.mod
  hack/tools/go.sum
  pkg/rotation/reconciler.go
  pkg/util/fileutil/atomic_writer_test.go
Labels: cncf-cla: yes, size/L, approved, kind/cleanup, lgtm
