Repository kubernetes-sigs/secrets-store-csi-driver, pull requests merged in 2023-05, with the labels that each got.

#1232 test: more usage of t.TempDir()
  pkg/rotation/reconciler_test.go
  pkg/util/secretutil/secret_test.go
Labels: cncf-cla: yes, approved, kind/cleanup, lgtm, size/M

#1231 ci: [StepSecurity] Apply security best practices
  .github/dependabot.yml
  .github/workflows/chart.yaml
  .github/workflows/codecov.yaml
  .github/workflows/codeql.yaml
  .github/workflows/create-release.yaml
  .github/workflows/dependency-review.yaml
  .github/workflows/e2e.yaml
  .github/workflows/markdown-link-check.yaml
  .github/workflows/scorecards.yaml
  .local/Dockerfile
  docker/Dockerfile
  test/e2eprovider/Dockerfile
Labels: kind/feature, cncf-cla: yes, size/L, approved, lgtm

#1246 docs: add openssf badge
  README.md
Labels: cncf-cla: yes, size/XS, approved, kind/documentation, lgtm

#1255 Use dl.k8s.io instead of hardcoded GCS URIs
  Makefile
  docker/crd.Dockerfile
Labels: cncf-cla: yes, size/XS, approved, kind/cleanup, lgtm

#1254 chore: bump k8s deps to `v1.26.4`
  .golangci.yml
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  pkg/metrics/prometheus_exporter.go
  pkg/rotation/reconciler.go
  pkg/rotation/reconciler_test.go
  pkg/rotation/stats_reporter.go
  pkg/secrets-store/mocks/stats_reporter_mock.go
  pkg/secrets-store/nodeserver.go
  pkg/secrets-store/secrets-store.go
  pkg/secrets-store/stats_reporter.go
  test/bats/e2e-provider.bats
  test/bats/gcp.bats
  test/bats/helpers.bash
  test/e2eprovider/go.mod
  test/e2eprovider/go.sum
Labels: kind/feature, cncf-cla: yes, approved, tide/merge-method-squash, lgtm, size/XL

#1247 chore: update node-driver-registrar:v2.8.0, livenessprobe:v2.10.0
  manifest_staging/charts/secrets-store-csi-driver/README.md
  manifest_staging/charts/secrets-store-csi-driver/values.yaml
  manifest_staging/deploy/secrets-store-csi-driver-windows.yaml
  manifest_staging/deploy/secrets-store-csi-driver.yaml
Labels: kind/feature, cncf-cla: yes, approved, lgtm, size/S

#1261 fix: make manifest diff
  Makefile
  config/crd/bases/secrets-store.csi.x-k8s.io_secretproviderclasses.yaml
  config/crd/bases/secrets-store.csi.x-k8s.io_secretproviderclasspodstatuses.yaml
  config/rbac-rotation/role.yaml
  config/rbac-syncsecret/role.yaml
  config/rbac-tokenrequest/role.yaml
  config/rbac/role.yaml
  manifest_staging/charts/secrets-store-csi-driver/crds/secrets-store.csi.x-k8s.io_secretproviderclasses.yaml
  manifest_staging/charts/secrets-store-csi-driver/crds/secrets-store.csi.x-k8s.io_secretproviderclasspodstatuses.yaml
  manifest_staging/charts/secrets-store-csi-driver/templates/role-rotation.yaml
  manifest_staging/charts/secrets-store-csi-driver/templates/role-syncsecret.yaml
  manifest_staging/charts/secrets-store-csi-driver/templates/role-tokenrequest.yaml
  manifest_staging/charts/secrets-store-csi-driver/templates/role.yaml
  manifest_staging/deploy/rbac-secretproviderclass.yaml
  manifest_staging/deploy/rbac-secretproviderrotation.yaml
  manifest_staging/deploy/rbac-secretprovidersyncing.yaml
  manifest_staging/deploy/rbac-secretprovidertokenrequest.yaml
  manifest_staging/deploy/secrets-store.csi.x-k8s.io_secretproviderclasses.yaml
  manifest_staging/deploy/secrets-store.csi.x-k8s.io_secretproviderclasspodstatuses.yaml
Labels: cncf-cla: yes, approved, kind/cleanup, lgtm, size/M
