Repository kubernetes-sigs/secrets-store-csi-driver, pull requests merged in 2023-07, with the labels that each got.

#1297 chore: update debian-base to bookworm-v1.0.0
  docker/BASEIMAGE
  docker/Dockerfile
Labels: kind/feature, cncf-cla: yes, size/XS, approved, lgtm

#1307 docs: mention sig-auth subproject in readme
  README.md
Labels: cncf-cla: yes, size/XS, approved, kind/documentation, lgtm

#1308 docs: update matrix for aws provider helm chart
  docs/book/src/providers.md
Labels: cncf-cla: yes, size/XS, approved, ok-to-test, kind/documentation, lgtm
