Repository kubernetes-sigs/secrets-store-csi-driver, pull requests merged in 2023-06, with the labels that each got.

#1268 docs: remove unnecessary "the" in concepts
  docs/book/src/concepts.md
Labels: cncf-cla: yes, size/XS, approved, ok-to-test, kind/documentation, lgtm

#1276 Automated cherry pick of #1275: release: update manifest and helm charts for v1.3.4
  charts/secrets-store-csi-driver/Chart.yaml
  charts/secrets-store-csi-driver/README.md
  charts/secrets-store-csi-driver/crds/secrets-store.csi.x-k8s.io_secretproviderclasses.yaml
  charts/secrets-store-csi-driver/crds/secrets-store.csi.x-k8s.io_secretproviderclasspodstatuses.yaml
  charts/secrets-store-csi-driver/templates/role-rotation.yaml
  charts/secrets-store-csi-driver/templates/role-syncsecret.yaml
  charts/secrets-store-csi-driver/templates/role-tokenrequest.yaml
  charts/secrets-store-csi-driver/templates/role.yaml
  charts/secrets-store-csi-driver/values.yaml
  deploy/rbac-secretproviderclass.yaml
  deploy/rbac-secretproviderrotation.yaml
  deploy/rbac-secretprovidersyncing.yaml
  deploy/rbac-secretprovidertokenrequest.yaml
  deploy/secrets-store-csi-driver-windows.yaml
  deploy/secrets-store-csi-driver.yaml
  deploy/secrets-store.csi.x-k8s.io_secretproviderclasses.yaml
  deploy/secrets-store.csi.x-k8s.io_secretproviderclasspodstatuses.yaml
  manifest_staging/charts/secrets-store-csi-driver/Chart.yaml
  manifest_staging/charts/secrets-store-csi-driver/README.md
  manifest_staging/charts/secrets-store-csi-driver/values.yaml
  manifest_staging/deploy/secrets-store-csi-driver-windows.yaml
  manifest_staging/deploy/secrets-store-csi-driver.yaml
Labels: cncf-cla: yes, approved, lgtm, size/M

#1275 release: update manifest and helm charts for v1.3.4
  Makefile
  charts/secrets-store-csi-driver/Chart.yaml
  charts/secrets-store-csi-driver/README.md
  charts/secrets-store-csi-driver/crds/secrets-store.csi.x-k8s.io_secretproviderclasses.yaml
  charts/secrets-store-csi-driver/crds/secrets-store.csi.x-k8s.io_secretproviderclasspodstatuses.yaml
  charts/secrets-store-csi-driver/templates/role-rotation.yaml
  charts/secrets-store-csi-driver/templates/role-syncsecret.yaml
  charts/secrets-store-csi-driver/templates/role-tokenrequest.yaml
  charts/secrets-store-csi-driver/templates/role.yaml
  charts/secrets-store-csi-driver/values.yaml
  deploy/rbac-secretproviderclass.yaml
  deploy/rbac-secretproviderrotation.yaml
  deploy/rbac-secretprovidersyncing.yaml
  deploy/rbac-secretprovidertokenrequest.yaml
  deploy/secrets-store-csi-driver-windows.yaml
  deploy/secrets-store-csi-driver.yaml
  deploy/secrets-store.csi.x-k8s.io_secretproviderclasses.yaml
  deploy/secrets-store.csi.x-k8s.io_secretproviderclasspodstatuses.yaml
  docker/Makefile
  manifest_staging/charts/secrets-store-csi-driver/Chart.yaml
  manifest_staging/charts/secrets-store-csi-driver/README.md
  manifest_staging/charts/secrets-store-csi-driver/values.yaml
  manifest_staging/deploy/secrets-store-csi-driver-windows.yaml
  manifest_staging/deploy/secrets-store-csi-driver.yaml
Labels: kind/feature, cncf-cla: yes, approved, lgtm, size/M

#1282 feat: enable using image digest in helm charts
  manifest_staging/charts/secrets-store-csi-driver/README.md
  manifest_staging/charts/secrets-store-csi-driver/templates/secrets-store-csi-driver-windows.yaml
  manifest_staging/charts/secrets-store-csi-driver/templates/secrets-store-csi-driver.yaml
  manifest_staging/charts/secrets-store-csi-driver/values.yaml
Labels: cncf-cla: yes, approved, ok-to-test, lgtm, size/M

#1215 test: improve nodeserver testing
  pkg/secrets-store/nodeserver_test.go
Labels: cncf-cla: yes, size/L, approved, kind/cleanup, lgtm
