Repository kubernetes-sigs/secrets-store-csi-driver, pull requests merged in 2023-04, with the labels that each got.

#1200 test: replace tmpdir with t.TempDir()
  pkg/secrets-store/nodeserver_test.go
  pkg/secrets-store/provider_client_test.go
  pkg/test_utils/tmpdir/tmpdir.go
  pkg/util/fileutil/filesystem_test.go
  pkg/util/fileutil/writer_test.go
Labels: cncf-cla: yes, size/L, approved, kind/cleanup, lgtm

#1201 chore: remove unused providerVolumePath code paths
  cmd/secrets-store-csi-driver/main.go
  pkg/rotation/reconciler.go
  pkg/rotation/reconciler_test.go
  pkg/secrets-store/nodeserver.go
  pkg/secrets-store/nodeserver_test.go
  pkg/secrets-store/secrets-store.go
  test/sanity/sanity_test.go
Labels: cncf-cla: yes, approved, kind/cleanup, lgtm, size/M

#1206 chore: updates error message
  pkg/rotation/reconciler.go
Labels: kind/bug, cncf-cla: yes, size/XS, approved, lgtm

#1209 fix: update nodeserver publish logs
  pkg/secrets-store/nodeserver.go
Labels: kind/bug, cncf-cla: yes, size/XS, approved, lgtm

#1212 security: bump kubernetes version to v1.27.0 in driver-crds
  Makefile
  docker/crd.Dockerfile
Labels: kind/bug, cncf-cla: yes, size/XS, approved, lgtm

#1211 chore: bump kind version to v0.18.0
  Makefile
Labels: cncf-cla: yes, size/XS, approved, lgtm

#1213 chore: update to go 1.20
  .golangci.yml
  docker/Dockerfile
  docker/windows.Dockerfile
  test/e2eprovider/Dockerfile
Labels: kind/feature, cncf-cla: yes, size/XS, approved, lgtm

#1219 chore: allow retries on pre-upgrade hook jobs
  manifest_staging/charts/secrets-store-csi-driver/templates/crds-upgrade-hook.yaml
  manifest_staging/charts/secrets-store-csi-driver/templates/keep-crds-upgrade-hook.yaml
Labels: cncf-cla: yes, size/XS, approved, ok-to-test, kind/cleanup, lgtm

#1202 chore: cleanup WritePayloads to be easier to use
  pkg/secrets-store/provider_client.go
  pkg/secrets-store/provider_client_test.go
  pkg/util/fileutil/writer.go
Labels: cncf-cla: yes, approved, kind/cleanup, lgtm, size/M

#1220 chore: bump version to v1.3.3 in release-1.3
  Makefile
  docker/Makefile
Labels: kind/feature, cncf-cla: yes, size/XS, approved, lgtm

#1222 Automated cherry pick of #1221: release: update manifest and helm charts for v1.3.3
  Makefile
  charts/secrets-store-csi-driver/Chart.yaml
  charts/secrets-store-csi-driver/README.md
  charts/secrets-store-csi-driver/templates/crds-upgrade-hook.yaml
  charts/secrets-store-csi-driver/templates/keep-crds-upgrade-hook.yaml
  charts/secrets-store-csi-driver/values.yaml
  deploy/secrets-store-csi-driver-windows.yaml
  deploy/secrets-store-csi-driver.yaml
  manifest_staging/charts/secrets-store-csi-driver/Chart.yaml
  manifest_staging/charts/secrets-store-csi-driver/README.md
  manifest_staging/charts/secrets-store-csi-driver/values.yaml
  manifest_staging/deploy/secrets-store-csi-driver-windows.yaml
  manifest_staging/deploy/secrets-store-csi-driver.yaml
Labels: cncf-cla: yes, approved, lgtm, size/M

#1221 release: update manifest and helm charts for v1.3.3
  Makefile
  charts/secrets-store-csi-driver/Chart.yaml
  charts/secrets-store-csi-driver/README.md
  charts/secrets-store-csi-driver/templates/crds-upgrade-hook.yaml
  charts/secrets-store-csi-driver/templates/keep-crds-upgrade-hook.yaml
  charts/secrets-store-csi-driver/values.yaml
  deploy/secrets-store-csi-driver-windows.yaml
  deploy/secrets-store-csi-driver.yaml
  docker/Makefile
  manifest_staging/charts/secrets-store-csi-driver/Chart.yaml
  manifest_staging/charts/secrets-store-csi-driver/README.md
  manifest_staging/charts/secrets-store-csi-driver/values.yaml
  manifest_staging/deploy/secrets-store-csi-driver-windows.yaml
  manifest_staging/deploy/secrets-store-csi-driver.yaml
Labels: kind/feature, cncf-cla: yes, approved, lgtm, size/M

#1223 ci: update kubernetes versions for staging image tests
  .github/workflows/e2e.yaml
Labels: cncf-cla: yes, size/XS, approved, kind/cleanup, lgtm

#1224 ci: add codecov.yml
  .github/workflows/codecov.yaml
  .gitignore
  Makefile
  codecov.yml
Labels: kind/feature, cncf-cla: yes, approved, lgtm, size/M

#1225 chore: enable gocritic linter and fix errors
  .golangci.yml
  pkg/k8s/token/token_manager.go
  pkg/k8s/token/token_manager_test.go
  pkg/rotation/reconciler.go
  pkg/secrets-store/provider_client.go
  pkg/secrets-store/server.go
  pkg/secrets-store/utils.go
  pkg/util/fileutil/atomic_writer_test.go
  pkg/util/k8sutil/volume.go
  pkg/util/secretutil/secret.go
  pkg/util/secretutil/secret_test.go
  test/e2eprovider/e2e_provider.go
  test/e2eprovider/go.mod
  test/e2eprovider/go.sum
  test/e2eprovider/server/server_test.go
  test/sanity/sanity_test.go
Labels: kind/feature, cncf-cla: yes, size/L, approved, lgtm
