Repository kubernetes-sigs/secrets-store-csi-driver, pull requests merged in 2023-01, with the labels that each got.

#1130 chore: update `node-driver-registrar:v2.7.0` and `livenessprobe:v2.9.0`
  manifest_staging/charts/secrets-store-csi-driver/README.md
  manifest_staging/charts/secrets-store-csi-driver/values.yaml
  manifest_staging/deploy/secrets-store-csi-driver-windows.yaml
  manifest_staging/deploy/secrets-store-csi-driver.yaml
Labels: kind/feature, cncf-cla: yes, approved, lgtm, size/S

#1134 feat: Better JSON logging
  cmd/secrets-store-csi-driver/main.go
  go.mod
  go.sum
  pkg/k8s/token_test.go
  test/e2eprovider/go.mod
  test/e2eprovider/go.sum
Labels: kind/feature, cncf-cla: yes, size/L, approved, kind/cleanup, lgtm

#1143 chore: bump version to v1.3.1 in release-1.3
  Makefile
  docker/Makefile
Labels: kind/feature, cncf-cla: yes, size/XS, approved, lgtm

#1146 chore: pin buildx to `v0.10.6`
  Makefile
Labels: cncf-cla: yes, size/XS, approved, kind/failing-test, lgtm

#1147 Automated cherry pick of #1146: chore: pin buildx to `v0.10.6`
  Makefile
Labels: cncf-cla: yes, size/XS, approved, lgtm

#1148 Automated cherry pick of #1144: release: update manifest and helm charts for v1.3.1
  charts/secrets-store-csi-driver/Chart.yaml
  charts/secrets-store-csi-driver/README.md
  charts/secrets-store-csi-driver/values.yaml
  deploy/secrets-store-csi-driver-windows.yaml
  deploy/secrets-store-csi-driver.yaml
  manifest_staging/charts/secrets-store-csi-driver/Chart.yaml
  manifest_staging/charts/secrets-store-csi-driver/README.md
  manifest_staging/charts/secrets-store-csi-driver/values.yaml
  manifest_staging/deploy/secrets-store-csi-driver-windows.yaml
  manifest_staging/deploy/secrets-store-csi-driver.yaml
Labels: cncf-cla: yes, approved, lgtm, size/M

#1144 release: update manifest and helm charts for v1.3.1
  charts/secrets-store-csi-driver/Chart.yaml
  charts/secrets-store-csi-driver/README.md
  charts/secrets-store-csi-driver/values.yaml
  deploy/secrets-store-csi-driver-windows.yaml
  deploy/secrets-store-csi-driver.yaml
  manifest_staging/charts/secrets-store-csi-driver/Chart.yaml
  manifest_staging/charts/secrets-store-csi-driver/README.md
  manifest_staging/charts/secrets-store-csi-driver/values.yaml
  manifest_staging/deploy/secrets-store-csi-driver-windows.yaml
  manifest_staging/deploy/secrets-store-csi-driver.yaml
Labels: kind/feature, cncf-cla: yes, approved, lgtm, size/M
