Repository kubernetes-sigs/secrets-store-csi-driver, pull requests merged in 2024-05, with the labels that each got.

#1498 test: add e2e for conjur csi provider
  Makefile
  test/bats/conjur.bats
  test/bats/tests/conjur/conjur_v1_secretproviderclass.yaml
  test/bats/tests/conjur/pod-conjur-rotation.yaml
  test/bats/tests/conjur/pod-secrets-store-inline-volume-crd.yaml
  test/bats/tests/conjur/policy/authn-jwt.yaml
  test/bats/tests/conjur/policy/host.yaml
  test/bats/tests/conjur/policy/variables.yaml
Labels: cncf-cla: yes, size/L, approved, ok-to-test, lgtm

#1531 docs: adds troubleshooting guide for kubeletRootDir
  docs/book/src/troubleshooting.md
Labels: cncf-cla: yes, approved, kind/documentation, lgtm, size/S

#1532 Automated cherry pick of #1530: chore: update debian-base to bookworm-v1.0.3
  docker/BASEIMAGE
  docker/Dockerfile
Labels: cncf-cla: yes, size/XS, approved, lgtm

#1530 chore: update debian-base to bookworm-v1.0.3
  docker/BASEIMAGE
  docker/Dockerfile
Labels: kind/feature, cncf-cla: yes, size/XS, approved, lgtm

#1534 Automated cherry pick of #1502: chore: bump kubectl to v1.29.4 in driver-crds for CVE-2023-45288
  docker/crd.Dockerfile
Labels: cncf-cla: yes, size/XS, approved, lgtm
