Repository kubernetes-sigs/secrets-store-csi-driver, pull requests merged in 2024-06, with the labels that each got.

#1543 test: remove target path check in fake provider server
  provider/fake/fake_server.go
Labels: cncf-cla: yes, size/XS, approved, kind/cleanup, lgtm

#1521 docs: Add Conjur provider
  docs/book/src/concepts.md
  docs/book/src/getting-started/installation.md
  docs/book/src/introduction.md
  docs/book/src/providers.md
Labels: cncf-cla: yes, approved, ok-to-test, kind/documentation, lgtm, size/S

#1545 Automated cherry pick of #1543: test: remove target path check in fake provider server
  provider/fake/fake_server.go
Labels: cncf-cla: yes, size/XS, approved, lgtm

#1547 chore: bump version to v1.4.4 in release-1.4
  Makefile
  docker/Makefile
Labels: kind/feature, cncf-cla: yes, size/XS, approved, lgtm

#1555 ci: use `--clean` instead of `--rm-dist`
  .github/workflows/create-release.yaml
Labels: cncf-cla: yes, size/XS, approved, lgtm

#1556 Automated cherry pick of #1555: ci: use `--clean` instead of `--rm-dist`
  .github/workflows/create-release.yaml
Labels: cncf-cla: yes, size/XS, approved, lgtm

#1557 ci: use `--verbose` instead of `--debug` in goreleaser
  .github/workflows/create-release.yaml
Labels: cncf-cla: yes, size/XS, approved, lgtm

#1558 Automated cherry pick of #1557: ci: use `--verbose` instead of `--debug` in goreleaser
  .github/workflows/create-release.yaml
Labels: cncf-cla: yes, size/XS, approved, lgtm

#1548 release: update manifest and helm charts for v1.4.4
  Makefile
  charts/secrets-store-csi-driver/Chart.yaml
  charts/secrets-store-csi-driver/README.md
  charts/secrets-store-csi-driver/values.yaml
  deploy/secrets-store-csi-driver-windows.yaml
  deploy/secrets-store-csi-driver.yaml
  docker/Makefile
  manifest_staging/charts/secrets-store-csi-driver/Chart.yaml
  manifest_staging/charts/secrets-store-csi-driver/README.md
  manifest_staging/charts/secrets-store-csi-driver/values.yaml
  manifest_staging/deploy/secrets-store-csi-driver-windows.yaml
  manifest_staging/deploy/secrets-store-csi-driver.yaml
Labels: kind/feature, cncf-cla: yes, approved, lgtm, size/M

#1561 Akeyless now provides Rotation
  docs/book/src/providers.md
Labels: cncf-cla: yes, size/XS, approved, ok-to-test, lgtm

#1565 feat: handles sha string in tag
  manifest_staging/charts/secrets-store-csi-driver/templates/secrets-store-csi-driver-windows.yaml
  manifest_staging/charts/secrets-store-csi-driver/templates/secrets-store-csi-driver.yaml
Labels: kind/feature, cncf-cla: yes, approved, lgtm, size/S
