Repository kubernetes-sigs/secrets-store-csi-driver, pull requests merged in 2024-01, with the labels that each got.

#1406 Automated cherry pick of #1405: ci: add script for aks windows cluster
  test/bats/tests/azure/job_templates/kubernetes_windows.json
  test/scripts/run-e2e-windows.sh
Labels: cncf-cla: yes, size/L, approved, lgtm

#1378 docs: updates security section
  docs/book/src/concepts.md
Labels: cncf-cla: yes, size/XS, approved, kind/documentation, lgtm

#1407 security: bump golang.org/x/crypto to v0.17.0 to fix CVE-2023-48795
  go.mod
  go.sum
  test/e2eprovider/go.mod
  test/e2eprovider/go.sum
Labels: kind/bug, cncf-cla: yes, approved, lgtm, size/M

#1409 Automated cherry pick of #1407: security: bump golang.org/x/crypto to v0.17.0 to fix
  go.mod
  go.sum
  test/e2eprovider/go.mod
  test/e2eprovider/go.sum
Labels: cncf-cla: yes, approved, lgtm, size/M

#1411 Automated cherry pick of #1410: ci: remove low quota regions for aks windows job
  test/scripts/run-e2e-windows.sh
Labels: cncf-cla: yes, size/XS, approved, lgtm

#1410 ci: remove low quota regions for aks windows job
  test/scripts/run-e2e-windows.sh
Labels: cncf-cla: yes, size/XS, approved, kind/failing-test, lgtm

#1393 chore: update to go 1.21.6 in docker
  .local/Dockerfile
  docker/Dockerfile
  docker/windows.Dockerfile
  test/e2eprovider/Dockerfile
Labels: kind/feature, cncf-cla: yes, size/XS, approved, ok-to-test, lgtm

#1412 Automated cherry pick of #1393: chore: update to go 1.21.6 in docker
  .local/Dockerfile
  docker/Dockerfile
  docker/windows.Dockerfile
  test/e2eprovider/Dockerfile
Labels: cncf-cla: yes, size/XS, approved, lgtm

#1413 docs: Make link to Reloader a link
  docs/book/src/topics/secret-auto-rotation.md
Labels: cncf-cla: yes, size/XS, approved, ok-to-test, tide/merge-method-squash, kind/documentation, lgtm

#1424 Automated cherry pick of #1423: release: update manifest and helm charts for v1.4.1
  charts/secrets-store-csi-driver/Chart.yaml
  charts/secrets-store-csi-driver/README.md
  charts/secrets-store-csi-driver/values.yaml
  deploy/secrets-store-csi-driver-windows.yaml
  deploy/secrets-store-csi-driver.yaml
  manifest_staging/charts/secrets-store-csi-driver/Chart.yaml
  manifest_staging/charts/secrets-store-csi-driver/README.md
  manifest_staging/charts/secrets-store-csi-driver/values.yaml
  manifest_staging/deploy/secrets-store-csi-driver-windows.yaml
  manifest_staging/deploy/secrets-store-csi-driver.yaml
Labels: cncf-cla: yes, approved, lgtm, size/M

#1423 release: update manifest and helm charts for v1.4.1
  Makefile
  charts/secrets-store-csi-driver/Chart.yaml
  charts/secrets-store-csi-driver/README.md
  charts/secrets-store-csi-driver/values.yaml
  deploy/secrets-store-csi-driver-windows.yaml
  deploy/secrets-store-csi-driver.yaml
  docker/Makefile
  manifest_staging/charts/secrets-store-csi-driver/Chart.yaml
  manifest_staging/charts/secrets-store-csi-driver/README.md
  manifest_staging/charts/secrets-store-csi-driver/values.yaml
  manifest_staging/deploy/secrets-store-csi-driver-windows.yaml
  manifest_staging/deploy/secrets-store-csi-driver.yaml
Labels: kind/feature, cncf-cla: yes, approved, lgtm, size/M
