Repository kubernetes-sigs/secrets-store-csi-driver, pull requests merged in 2024-03, with the labels that each got.

#1457 chore: update debian-base to bookworm-v1.0.1
  docker/BASEIMAGE
  docker/Dockerfile
Labels: kind/feature, cncf-cla: yes, size/XS, approved, lgtm

#1458 Automated cherry pick of #1457: chore: update debian-base to bookworm-v1.0.1
  docker/BASEIMAGE
  docker/Dockerfile
Labels: cncf-cla: yes, size/XS, approved, lgtm

#1459 chore: update node-driver-registrar:v2.10.0, livenessprobe:v2.12.0
  manifest_staging/charts/secrets-store-csi-driver/README.md
  manifest_staging/charts/secrets-store-csi-driver/templates/secrets-store-csi-driver-windows.yaml
  manifest_staging/charts/secrets-store-csi-driver/templates/secrets-store-csi-driver.yaml
  manifest_staging/charts/secrets-store-csi-driver/values.yaml
  manifest_staging/deploy/secrets-store-csi-driver-windows.yaml
  manifest_staging/deploy/secrets-store-csi-driver.yaml
Labels: kind/feature, cncf-cla: yes, approved, lgtm, size/M

#1460 Automated cherry pick of #1459: chore: update node-driver-registrar:v2.10.0,
  manifest_staging/charts/secrets-store-csi-driver/README.md
  manifest_staging/charts/secrets-store-csi-driver/templates/secrets-store-csi-driver-windows.yaml
  manifest_staging/charts/secrets-store-csi-driver/templates/secrets-store-csi-driver.yaml
  manifest_staging/charts/secrets-store-csi-driver/values.yaml
  manifest_staging/deploy/secrets-store-csi-driver-windows.yaml
  manifest_staging/deploy/secrets-store-csi-driver.yaml
Labels: cncf-cla: yes, approved, lgtm, size/M

#1461 chore: bump version to v1.4.2 in release-1.4
  Makefile
  docker/Makefile
Labels: cncf-cla: yes, size/XS, approved, lgtm

#1465 Automated cherry pick of #1463: release: update manifest and helm charts for v1.4.2
  charts/secrets-store-csi-driver/Chart.yaml
  charts/secrets-store-csi-driver/README.md
  charts/secrets-store-csi-driver/templates/secrets-store-csi-driver-windows.yaml
  charts/secrets-store-csi-driver/templates/secrets-store-csi-driver.yaml
  charts/secrets-store-csi-driver/values.yaml
  deploy/secrets-store-csi-driver-windows.yaml
  deploy/secrets-store-csi-driver.yaml
  manifest_staging/charts/secrets-store-csi-driver/Chart.yaml
  manifest_staging/charts/secrets-store-csi-driver/README.md
  manifest_staging/charts/secrets-store-csi-driver/values.yaml
  manifest_staging/deploy/secrets-store-csi-driver-windows.yaml
  manifest_staging/deploy/secrets-store-csi-driver.yaml
Labels: cncf-cla: yes, size/L, approved, lgtm

#1463 release: update manifest and helm charts for v1.4.2
  Makefile
  charts/secrets-store-csi-driver/Chart.yaml
  charts/secrets-store-csi-driver/README.md
  charts/secrets-store-csi-driver/templates/secrets-store-csi-driver-windows.yaml
  charts/secrets-store-csi-driver/templates/secrets-store-csi-driver.yaml
  charts/secrets-store-csi-driver/values.yaml
  deploy/secrets-store-csi-driver-windows.yaml
  deploy/secrets-store-csi-driver.yaml
  docker/Makefile
  manifest_staging/charts/secrets-store-csi-driver/Chart.yaml
  manifest_staging/charts/secrets-store-csi-driver/README.md
  manifest_staging/charts/secrets-store-csi-driver/values.yaml
  manifest_staging/deploy/secrets-store-csi-driver-windows.yaml
  manifest_staging/deploy/secrets-store-csi-driver.yaml
Labels: kind/feature, cncf-cla: yes, size/L, approved, lgtm

#1467 security: CVE-2024-24786: bump google.golang.org/protobuf to v1.33.0
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/e2eprovider/go.mod
  test/e2eprovider/go.sum
Labels: cncf-cla: yes, approved, lgtm, size/M

#1473 Automated cherry pick of #1472: security: bump kubectl to v1.29.3 in driver-crds for
  docker/crd.Dockerfile
Labels: cncf-cla: yes, size/XS, approved, lgtm

#1474 Automated cherry pick of #1467: CVE-2024-24786: bump google.golang.org/protobuf to v1.33.0
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/e2eprovider/go.mod
  test/e2eprovider/go.sum
Labels: cncf-cla: yes, approved, lgtm, size/M

#1478 fix: support more than one linux.crds.annotations entry
  manifest_staging/charts/secrets-store-csi-driver/templates/crds-upgrade-hook.yaml
  manifest_staging/charts/secrets-store-csi-driver/templates/keep-crds-upgrade-hook.yaml
Labels: kind/bug, cncf-cla: yes, size/XS, approved, ok-to-test, lgtm
