Repository kubernetes-sigs/secrets-store-csi-driver, pull requests merged in 2024-10, with the labels that each got.

#1661 Automated cherry pick of #1660: chore: bumps base images
  docker/BASEIMAGE
  docker/Dockerfile
Labels: cncf-cla: yes, size/XS, approved, lgtm

#1659 chore: bumps version for v1.4.6 release
  Makefile
  docker/Makefile
Labels: cncf-cla: yes, size/XS, approved, lgtm

#1663 release: update manifest and helm charts for v1.4.6
  Makefile
  apis/v1/zz_generated.deepcopy.go
  apis/v1alpha1/zz_generated.deepcopy.go
  charts/secrets-store-csi-driver/Chart.yaml
  charts/secrets-store-csi-driver/README.md
  charts/secrets-store-csi-driver/crds/secrets-store.csi.x-k8s.io_secretproviderclasses.yaml
  charts/secrets-store-csi-driver/crds/secrets-store.csi.x-k8s.io_secretproviderclasspodstatuses.yaml
  charts/secrets-store-csi-driver/values.yaml
  config/crd/bases/secrets-store.csi.x-k8s.io_secretproviderclasses.yaml
  config/crd/bases/secrets-store.csi.x-k8s.io_secretproviderclasspodstatuses.yaml
  deploy/secrets-store-csi-driver-windows.yaml
  deploy/secrets-store-csi-driver.yaml
  deploy/secrets-store.csi.x-k8s.io_secretproviderclasses.yaml
  deploy/secrets-store.csi.x-k8s.io_secretproviderclasspodstatuses.yaml
  hack/tools/go.mod
  hack/tools/go.sum
  hack/tools/tools.go
  manifest_staging/charts/secrets-store-csi-driver/Chart.yaml
  manifest_staging/charts/secrets-store-csi-driver/README.md
  manifest_staging/charts/secrets-store-csi-driver/crds/secrets-store.csi.x-k8s.io_secretproviderclasses.yaml
  manifest_staging/charts/secrets-store-csi-driver/crds/secrets-store.csi.x-k8s.io_secretproviderclasspodstatuses.yaml
  manifest_staging/charts/secrets-store-csi-driver/values.yaml
  manifest_staging/deploy/secrets-store-csi-driver-windows.yaml
  manifest_staging/deploy/secrets-store-csi-driver.yaml
  manifest_staging/deploy/secrets-store.csi.x-k8s.io_secretproviderclasses.yaml
  manifest_staging/deploy/secrets-store.csi.x-k8s.io_secretproviderclasspodstatuses.yaml
  pkg/version/version.go
Labels: cncf-cla: yes, approved, lgtm, size/XL

#1664 ci: update goreleaser config for v2
  .goreleaser.yml
Labels: cncf-cla: yes, size/XS, approved, lgtm

#1662 release: update manifest and helm charts for v1.4.6
  Makefile
  apis/v1/zz_generated.deepcopy.go
  apis/v1alpha1/zz_generated.deepcopy.go
  charts/secrets-store-csi-driver/Chart.yaml
  charts/secrets-store-csi-driver/README.md
  charts/secrets-store-csi-driver/crds/secrets-store.csi.x-k8s.io_secretproviderclasses.yaml
  charts/secrets-store-csi-driver/crds/secrets-store.csi.x-k8s.io_secretproviderclasspodstatuses.yaml
  charts/secrets-store-csi-driver/values.yaml
  config/crd/bases/secrets-store.csi.x-k8s.io_secretproviderclasses.yaml
  config/crd/bases/secrets-store.csi.x-k8s.io_secretproviderclasspodstatuses.yaml
  deploy/secrets-store-csi-driver-windows.yaml
  deploy/secrets-store-csi-driver.yaml
  deploy/secrets-store.csi.x-k8s.io_secretproviderclasses.yaml
  deploy/secrets-store.csi.x-k8s.io_secretproviderclasspodstatuses.yaml
  docker/Makefile
  hack/tools/go.mod
  hack/tools/go.sum
  hack/tools/tools.go
  manifest_staging/charts/secrets-store-csi-driver/Chart.yaml
  manifest_staging/charts/secrets-store-csi-driver/README.md
  manifest_staging/charts/secrets-store-csi-driver/crds/secrets-store.csi.x-k8s.io_secretproviderclasses.yaml
  manifest_staging/charts/secrets-store-csi-driver/crds/secrets-store.csi.x-k8s.io_secretproviderclasspodstatuses.yaml
  manifest_staging/charts/secrets-store-csi-driver/values.yaml
  manifest_staging/deploy/secrets-store-csi-driver-windows.yaml
  manifest_staging/deploy/secrets-store-csi-driver.yaml
  manifest_staging/deploy/secrets-store.csi.x-k8s.io_secretproviderclasses.yaml
  manifest_staging/deploy/secrets-store.csi.x-k8s.io_secretproviderclasspodstatuses.yaml
  pkg/version/version.go
Labels: kind/feature, cncf-cla: yes, approved, lgtm, size/XL

#1665 Automated cherry pick of #1593: chore: bump kind version and k8s version in test matrix
  .github/workflows/e2e.yaml
  Makefile
Labels: cncf-cla: yes, size/XS, approved, lgtm
