Repository kubernetes-sigs/secrets-store-csi-driver, pull requests merged in 2025-01, with the labels that each got.

#1720 security: bump golang.org/x/net to v0.33.0 to fix CVE-2024-45338
  go.mod
  go.sum
  test/e2eprovider/go.mod
  test/e2eprovider/go.sum
Labels: cncf-cla: yes, approved, lgtm, size/S

#1725 security: bump golang.org/x/net to v0.33.0 to fix CVE-2024-45338
  go.mod
  go.sum
  test/e2eprovider/go.mod
  test/e2eprovider/go.sum
Labels: cncf-cla: yes, approved, lgtm, size/M

#1701 test: add e2e test setup for GCP provider
  test/bats/gcp.bats
  test/scripts/run-e2e-gcp.sh
Labels: cncf-cla: yes, size/L, approved, ok-to-test, lgtm

#1742 chore: bump version to v1.4.8 in release-1.4
  Makefile
  docker/Makefile
Labels: cncf-cla: yes, size/XS, approved, lgtm

#1745 release: update manifest and helm charts for v1.4.8
  charts/secrets-store-csi-driver/Chart.yaml
  charts/secrets-store-csi-driver/README.md
  charts/secrets-store-csi-driver/values.yaml
  deploy/secrets-store-csi-driver-windows.yaml
  deploy/secrets-store-csi-driver.yaml
  manifest_staging/charts/secrets-store-csi-driver/Chart.yaml
  manifest_staging/charts/secrets-store-csi-driver/README.md
  manifest_staging/charts/secrets-store-csi-driver/values.yaml
  manifest_staging/deploy/secrets-store-csi-driver-windows.yaml
  manifest_staging/deploy/secrets-store-csi-driver.yaml
Labels: cncf-cla: yes, approved, lgtm, size/M

#1744 release: update manifest and helm charts for v1.4.8
  Makefile
  charts/secrets-store-csi-driver/Chart.yaml
  charts/secrets-store-csi-driver/README.md
  charts/secrets-store-csi-driver/values.yaml
  deploy/secrets-store-csi-driver-windows.yaml
  deploy/secrets-store-csi-driver.yaml
  docker/Makefile
  manifest_staging/charts/secrets-store-csi-driver/Chart.yaml
  manifest_staging/charts/secrets-store-csi-driver/README.md
  manifest_staging/charts/secrets-store-csi-driver/values.yaml
  manifest_staging/deploy/secrets-store-csi-driver-windows.yaml
  manifest_staging/deploy/secrets-store-csi-driver.yaml
Labels: cncf-cla: yes, approved, lgtm, size/M
